"use client";
/* eslint-disable react-hooks/set-state-in-effect */

import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { AlertTriangle, Pencil, Plus, Search, ShieldCheck, Trash2, X } from "lucide-react";
import { apiRequest } from "@/lib/api-client";
import type { BackendRoleDto } from "@/lib/backend-dtos";
import { useAuthorization } from "@/lib/access-control";
import { PermissionSelector, normalizePermissionGroups, type PermissionGroup } from "./permission-selector";
import { pageRequest } from "@/lib/page-request";
import { toBackendRole, type UsersRolesPageContract } from "@/lib/page-contracts";

function RoleDialog({role,groups,canManagePermissions,close,saved}:{role:BackendRoleDto|null;groups:PermissionGroup[];canManagePermissions:boolean;close:()=>void;saved:()=>Promise<void>}){
  const[key]=useState(role?.role??"");const[roleKey,setRoleKey]=useState(role?.role??"");const[name,setName]=useState(role?.displayName??"");const[description,setDescription]=useState(role?.description??"");const[selected,setSelected]=useState(role?.capabilities??[]);const[pending,setPending]=useState(false);const[error,setError]=useState("");
  async function submit(event:FormEvent){event.preventDefault();setPending(true);setError("");const body={role:roleKey.trim(),displayName:name.trim(),description:description.trim(),capabilities:selected};try{await apiRequest<BackendRoleDto>(role?`/api/backend/roles/${encodeURIComponent(key)}`:"/api/backend/roles",{method:role?"PATCH":"POST",body:JSON.stringify(body)});await saved();close()}catch(cause){setError(cause instanceof Error?cause.message:`Role ${role?"update":"creation"} failed.`)}finally{setPending(false)}}
  return <div className="fixed inset-0 z-[80] flex items-end justify-center bg-black/65 sm:items-center sm:p-5"><section role="dialog" aria-modal="true" aria-labelledby="role-dialog-title" className="max-h-[94vh] w-full max-w-3xl overflow-y-auto rounded-t-2xl border bg-background p-5 shadow-2xl sm:rounded-2xl"><header className="flex justify-between gap-3"><div><h2 id="role-dialog-title" className="font-bold">{role?"Edit Role":"Create Role"}</h2><p className="text-xs text-muted-foreground">Use the canonical permission catalogue. Role keys are stable identifiers.</p></div><button onClick={close} aria-label="Close role form" className="grid size-9 place-items-center rounded-lg border"><X className="size-4"/></button></header><form onSubmit={submit} className="mt-5 space-y-4"><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs">Role key<input required disabled={Boolean(role)} value={roleKey} onChange={event=>setRoleKey(event.target.value)} className="mt-1 h-10 w-full rounded-lg border bg-background px-3 disabled:opacity-60"/></label><label className="text-xs">Display name<input required value={name} onChange={event=>setName(event.target.value)} className="mt-1 h-10 w-full rounded-lg border bg-background px-3"/></label></div><label className="block text-xs">Description<textarea required value={description} onChange={event=>setDescription(event.target.value)} className="mt-1 min-h-20 w-full rounded-lg border bg-background p-3"/></label><fieldset disabled={!canManagePermissions}><legend className="mb-2 text-xs font-semibold">Permissions</legend><PermissionSelector groups={groups} selected={selected} onChange={setSelected} readOnly={!canManagePermissions}/></fieldset>{error&&<p role="alert" className="rounded-lg bg-destructive/10 p-3 text-xs text-destructive">{error}</p>}<button disabled={pending||!roleKey.trim()||!name.trim()} className="h-10 w-full rounded-lg bg-primary text-xs font-semibold text-primary-foreground disabled:opacity-40">{pending?"Saving…":role?"Save Role":"Create Role"}</button></form></section></div>
}

export function RoleManagement(){
  const access=useAuthorization();const canView=access.hasPermission("roles.view");const canCreate=access.hasPermission("roles.create");const canUpdate=access.hasPermission("roles.update");const canDelete=access.hasAnyPermission(["roles.delete","roles.retire"]);const canManagePermissions=access.hasPermission("roles.permissions.manage");const[roles,setRoles]=useState<BackendRoleDto[]>([]);const[groups,setGroups]=useState<PermissionGroup[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[query,setQuery]=useState("");const[editing,setEditing]=useState<BackendRoleDto|null|undefined>();
  const load=useCallback(async()=>{try{const response=await pageRequest<UsersRolesPageContract>("roles");setRoles(response.roles.map(toBackendRole));const byModule=new Map<string,typeof response.permissions>();for(const permission of response.permissions)byModule.set(permission.module,[...(byModule.get(permission.module)??[]),permission]);setGroups(normalizePermissionGroups([...byModule].map(([module,permissions])=>({module,permissions}))));setError("")}catch(cause){setError(cause instanceof Error?cause.message:"Roles could not be loaded.")}finally{setLoading(false)}},[]);
  useEffect(()=>{if(canView)void load()},[canView,load]);
  const sorted=useMemo(()=>roles.filter(role=>`${role.role} ${role.displayName} ${role.description}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>(a.displayName||a.role).localeCompare(b.displayName||b.role)),[roles,query]);
  async function remove(role:BackendRoleDto){if(!canDelete||role.isSystem||!confirm(`Retire role "${role.displayName||role.role}"?`))return;try{await apiRequest(`/api/backend/roles/${encodeURIComponent(role.role)}`,{method:"DELETE"});await load()}catch(cause){setError(cause instanceof Error?cause.message:"Role retirement failed.")}}
  if(access.loading||loading)return <div className="h-56 animate-pulse rounded-xl bg-muted"/>;if(!canView)return <p role="alert" className="rounded-xl border p-5 text-sm text-muted-foreground">Access Denied: roles.view is required.</p>;
  return <div className="space-y-4"><header className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-lg font-bold">Roles</h2><p className="text-xs text-muted-foreground">Built-in and custom roles with persisted permissions.</p></div>{canCreate&&<button onClick={()=>setEditing(null)} className="inline-flex h-9 items-center gap-2 rounded-lg bg-primary px-3 text-xs font-semibold text-primary-foreground"><Plus className="size-4"/>Create Role</button>}</header><label className="relative block max-w-sm"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><span className="sr-only">Search roles</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search roles…" className="h-10 w-full rounded-lg border bg-card pl-9 pr-3 text-xs"/></label>{error&&<p role="alert" className="flex items-center gap-2 rounded-lg bg-destructive/10 p-3 text-xs text-destructive"><AlertTriangle className="size-4"/>{error}</p>}<div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{sorted.map(role=><article key={role.role} className="rounded-lg border bg-card p-3"><div className="flex items-start gap-2"><ShieldCheck className="mt-0.5 size-4 shrink-0 text-primary"/><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-bold">{role.displayName||role.role}</h3><p className="font-mono text-xs text-muted-foreground">{role.role}</p><p className="mt-1 line-clamp-2 text-xs text-muted-foreground">{role.description}</p><p className="mt-2 font-mono text-xs text-primary">{role.capabilities.length} permissions {role.isSystem?"· System · Protected":"· Custom"}</p></div>{!role.isSystem&&(canUpdate||canDelete)&&<div className="flex gap-1">{canUpdate&&<button onClick={()=>setEditing(role)} aria-label={`Edit ${role.displayName||role.role}`} className="grid size-7 place-items-center rounded-md border"><Pencil className="size-3"/></button>}{canDelete&&<button onClick={()=>void remove(role)} aria-label={`Retire ${role.displayName||role.role}`} className="grid size-7 place-items-center rounded-md border text-destructive"><Trash2 className="size-3"/></button>}</div>}</div></article>)}{!sorted.length&&<p className="col-span-full rounded-lg border p-8 text-center text-xs text-muted-foreground">No roles match this search.</p>}</div>{editing!==undefined&&<RoleDialog role={editing} groups={groups} canManagePermissions={canManagePermissions} close={()=>setEditing(undefined)} saved={async()=>{await load();await access.refresh()}}/>}</div>
}
