import { Building2, ClipboardList, Cpu, FileText, LayoutDashboard, Radio, UserRoundCheck, Zap, type LucideIcon } from "lucide-react";
export const permissionTypes=["View","Create","Edit","Delete","Approve","Export"] as const; export type Permission=(typeof permissionTypes)[number]; export type ResourceKey="dashboard"|"facilities"|"assets"|"sensors"|"reports"|"users"|"audit"|"apis";
export type Resource={key:ResourceKey;label:string;description:string;icon:LucideIcon}; export type RoleColor="violet"|"blue"|"teal"|"green"|"amber"|"slate"; export type Role={id:string;name:string;description:string;color:RoleColor;userCount:number;system:boolean;inheritsFrom?:string;department:string;createdBy:string;lastModified:string;permissions:Record<ResourceKey,Permission[]>}; export type AssignedUser={id:string;name:string;email:string;roleId:string;department:string;site:string;status:"Active"|"Inactive"};
export const resources:Resource[]=[{key:"dashboard",label:"Dashboard",description:"Analytics & KPI command center",icon:LayoutDashboard},{key:"facilities",label:"Facilities",description:"Sites, facilities & production",icon:Building2},{key:"assets",label:"Assets",description:"Asset registry & maintenance",icon:Cpu},{key:"sensors",label:"Sensors",description:"Sensor intelligence center",icon:Radio},{key:"reports",label:"Reports",description:"Report generation & export",icon:FileText},{key:"users",label:"Users",description:"User accounts & MFA management",icon:UserRoundCheck},{key:"audit",label:"Audit Logs",description:"Audit log center & compliance",icon:ClipboardList},{key:"apis",label:"APIs",description:"API keys & integrations",icon:Zap}];
const empty=():Record<ResourceKey,Permission[]>=>Object.fromEntries(resources.map(r=>[r.key,[]])) as unknown as Record<ResourceKey,Permission[]>; const allow=(value:Partial<Record<ResourceKey,Permission[]>>)=>({...empty(),...value}); const all=Object.fromEntries(resources.map(r=>[r.key,[...permissionTypes]])) as Record<ResourceKey,Permission[]>;
export const roles:Role[]=[
{id:"administrator",name:"Administrator",description:"Full system access — all resources, all permissions.",color:"violet",userCount:1,system:true,department:"IT",createdBy:"System",lastModified:"2025-01-01",permissions:all},
{id:"plant-manager",name:"Plant Manager",description:"Operational access — manage sites, assets, sensors, and generate reports.",color:"blue",userCount:9,system:true,inheritsFrom:"Administrator",department:"Operations",createdBy:"Admin User",lastModified:"2025-03-12",permissions:allow({dashboard:["View","Export"],facilities:["View","Create","Edit","Approve"],assets:["View","Create","Edit"],sensors:["View","Create","Edit","Delete"],reports:["View","Create","Export"],users:["View"],apis:["View"]})},
{id:"quality-inspector",name:"Quality Inspector",description:"Quality-focused read and edit access to assets and reports.",color:"teal",userCount:2,system:false,department:"Quality",createdBy:"Admin User",lastModified:"2025-04-08",permissions:allow({dashboard:["View"],facilities:["View"],assets:["View","Edit"],sensors:["View"],reports:["View","Create","Export"]})},
{id:"finance-analyst",name:"Finance Analyst",description:"Financial analytics access — dashboard, reports, and audit log viewing.",color:"green",userCount:2,system:false,department:"Finance",createdBy:"Admin User",lastModified:"2025-05-15",permissions:allow({dashboard:["View","Export"],facilities:["View"],assets:["View"],sensors:["View"],reports:["View","Create","Export"],audit:["View","Export"],apis:["View"]})},
{id:"audit-viewer",name:"Audit Viewer",description:"Compliance and audit access — read-only across all modules plus full audit log.",color:"amber",userCount:1,system:false,department:"Compliance",createdBy:"Admin User",lastModified:"2025-06-01",permissions:allow({dashboard:["View"],facilities:["View"],assets:["View"],sensors:["View"],reports:["View","Export"],users:["View"],audit:["View","Export"]})},
{id:"viewer",name:"Viewer",description:"Read-only access to dashboard, facilities, assets, sensors, and reports.",color:"slate",userCount:1,system:true,department:"General",createdBy:"System",lastModified:"2025-01-01",permissions:allow({dashboard:["View"],facilities:["View"],assets:["View"],sensors:["View"],reports:["View"]})}];
const row=(id:string,name:string,email:string,roleId:string,department:string,site:string,status:"Active"|"Inactive"="Active"):AssignedUser=>({id,name,email,roleId,department,site,status}); export const assignedUsers=[row("u1","Admin User","admin@divu.io","administrator","IT","Detroit Assembly"),row("u2","Sarah Johnson","s.johnson@divu.io","plant-manager","Operations","Detroit Assembly"),row("u3","Carlos Rivera","c.rivera@divu.io","plant-manager","Operations","São Paulo"),row("u4","Mike Davis","m.davis@divu.io","plant-manager","Operations","Detroit Assembly"),row("u5","Kenji Tanaka","k.tanaka@divu.io","plant-manager","Operations","Osaka Production"),row("u6","James Okafor","j.okafor@divu.io","plant-manager","Operations","São Paulo"),row("u7","Thomas Wright","t.wright@divu.io","plant-manager","Operations","Detroit Assembly"),row("u8","Yuki Nakamura","y.nakamura@divu.io","plant-manager","Operations","Osaka Production"),row("u9","Ravi Patel","r.patel@divu.io","plant-manager","Engineering","Frankfurt Industrial"),row("u10","Fatima Al-Hassan","f.alhassan@divu.io","plant-manager","Operations","Detroit Assembly","Inactive"),row("u11","Anna Müller","a.muller@divu.io","quality-inspector","Quality","Frankfurt Industrial"),row("u12","Elena Petrov","e.petrov@divu.io","quality-inspector","Quality","Frankfurt Industrial"),row("u13","Lisa Chen","l.chen@divu.io","finance-analyst","Finance","Detroit Assembly"),row("u14","David Park","d.park@divu.io","finance-analyst","Finance","Detroit Assembly"),row("u15","Maria Santos","m.santos@divu.io","audit-viewer","Compliance","São Paulo"),row("u16","Viewer User","viewer@divu.io","viewer","General","Detroit Assembly")];
export const permissionCount=(role:Role)=>Object.values(role.permissions).flat().length; export const roleColor={violet:"bg-violet-100 text-violet-700 border-violet-200 dark:bg-violet-500/20 dark:text-violet-300",blue:"bg-blue-100 text-blue-700 border-blue-200 dark:bg-blue-500/20 dark:text-blue-300",teal:"bg-teal-100 text-teal-700 border-teal-200 dark:bg-teal-500/20 dark:text-teal-300",green:"bg-emerald-100 text-emerald-700 border-emerald-200 dark:bg-emerald-500/20 dark:text-emerald-300",amber:"bg-amber-100 text-amber-700 border-amber-200 dark:bg-amber-500/20 dark:text-amber-300",slate:"bg-slate-100 text-slate-700 border-slate-200 dark:bg-slate-500/20 dark:text-slate-300"} as const;
