"use client";
import { useState } from "react";
import { Plus } from "lucide-react";
import { PermissionMatrix } from "./permission-matrix";
import { RoleAssignmentsPanel } from "./role-assignments-panel";
import { RoleCardsGrid } from "./role-cards";
import { CreateRoleModal, RoleDetailsModal } from "./role-modals";
import { roles, type Role } from "./roles-data";
import { DepartmentsPanel } from "./departments-panel";
export function RolesStatsCards(){const cards=[["Total Roles","6","bg-card"],["Total Users","32","bg-blue-50/80 dark:bg-blue-500/10"],["Resources","8","bg-teal-50/80 dark:bg-teal-500/10"],["Permission Types","6","bg-violet-50/80 dark:bg-violet-500/10"]];return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label,value,bg])=><div key={label} className={`rounded-xl border border-border/70 px-3 py-3 ${bg}`}><p className="text-lg font-bold">{value}</p><p className="text-[11px] text-muted-foreground">{label}</p></div>)}</div>}
export function RolesTabs({active,onChange}:{active:"matrix"|"roles"|"assignments"|"departments";onChange:(tab:"matrix"|"roles"|"assignments"|"departments")=>void}){return <div className="flex border-b">{[["matrix","Permission Matrix"],["roles","Roles"],["assignments","Role Assignments"],["departments","Departments"]].map(([id,label])=><button key={id} type="button" onClick={()=>onChange(id as "matrix"|"roles"|"assignments"|"departments")} className={`border-b-2 px-4 py-3 text-xs font-medium ${active===id?"border-primary text-primary":"border-transparent text-muted-foreground hover:text-foreground"}`}>{label}</button>)}</div>}
export function RolesPage(){const[tab,setTab]=useState<"matrix"|"roles"|"assignments"|"departments">("matrix");const[detail,setDetail]=useState<Role|null>(null);const[createOpen,setCreateOpen]=useState(false);return <div className="space-y-4 pb-5"><header className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-2xl font-bold tracking-tight">RBAC Administration</h1><p className="mt-1 text-sm text-muted-foreground">Role-based access control — define permissions across all platform resources</p></div><button type="button" onClick={()=>setCreateOpen(true)} className="inline-flex h-9 items-center justify-center gap-1.5 rounded-lg bg-primary px-3 text-xs font-semibold text-primary-foreground hover:bg-primary/90"><Plus className="size-3.5"/>Create Role</button></header><RolesStatsCards/><RolesTabs active={tab} onChange={setTab}/>{tab==="matrix"&&<PermissionMatrix/>}{tab==="roles"&&<RoleCardsGrid roles={roles} onDetails={setDetail}/>} {tab==="assignments"&&<RoleAssignmentsPanel roles={roles}/>} {tab==="departments"&&<DepartmentsPanel/>} {detail&&<RoleDetailsModal role={detail} onClose={()=>setDetail(null)}/>} {createOpen&&<CreateRoleModal onClose={()=>setCreateOpen(false)}/>}</div>}
