import type { GovernancePolicy } from "./governance-data";

export const governancePolicies: GovernancePolicy[] = [
  { id: "POL-001", name: "Sensor Telemetry Retention", owner: "Governance Team", description: "Retention and archival rules for industrial telemetry streams.", appliesTo: "Sensor Telemetry", status: "Active", retentionPeriod: "7 Years", reviewFrequency: "Annual", archiveRule: "Archive after retention period", deletionRule: "Delete after retention expires", piiHandling: "No PII Collected", encryptionRequired: true, classification: "Restricted", riskLevel: "High", approvalRequired: true, complianceStandard: "ISO 27001", createdBy: "Admin User", createdAt: "2026-01-15", updatedAt: "2026-06-15" },
  { id: "POL-002", name: "Financial Records Compliance", owner: "Finance Team", description: "Privacy controls for financial analytics and records.", appliesTo: "Financial Analytics", status: "Active", retentionPeriod: "7 Years", reviewFrequency: "Semi-Annual", archiveRule: "Archive after audit approval", deletionRule: "Require admin approval before deletion", piiHandling: "Restrict PII to Administrators", encryptionRequired: true, classification: "Confidential", riskLevel: "Critical", approvalRequired: true, complianceStandard: "SOC 2", createdBy: "Admin User", createdAt: "2026-02-10", updatedAt: "2026-05-30" },
  { id: "POL-003", name: "User PII Data Policy", owner: "Compliance Team", description: "Handling, masking, and erasure requirements for identities.", appliesTo: "User Activity", status: "Under Review", retentionPeriod: "3 Years", reviewFrequency: "Quarterly", archiveRule: "Do not archive automatically", deletionRule: "Legal hold prevents deletion", piiHandling: "Encrypt PII Fields", encryptionRequired: true, classification: "Confidential", riskLevel: "High", approvalRequired: true, complianceStandard: "PIPEDA", createdBy: "Admin User", createdAt: "2026-03-02", updatedAt: "2026-07-01" },
  { id: "POL-004", name: "Operations Log Archive", owner: "Operations Team", description: "Lifecycle standard for manufacturing operations events.", appliesTo: "Downtime Events", status: "Active", retentionPeriod: "5 Years", reviewFrequency: "Annual", archiveRule: "Archive after inactivity", deletionRule: "Delete after retention expires", piiHandling: "No PII Collected", encryptionRequired: false, classification: "Internal", riskLevel: "Medium", approvalRequired: false, complianceStandard: "Internal Policy", createdBy: "Admin User", createdAt: "2026-01-08", updatedAt: "2026-04-20" },
  { id: "POL-005", name: "API Access Audit Trail", owner: "Security Team", description: "Audit, masking, and retention requirements for API gateway logs.", appliesTo: "API Clients", status: "Draft", retentionPeriod: "1 Year", reviewFrequency: "Quarterly", archiveRule: "Archive after audit approval", deletionRule: "Require admin approval before deletion", piiHandling: "Mask PII in Reports", encryptionRequired: true, classification: "Restricted", riskLevel: "High", approvalRequired: true, complianceStandard: "NIST CSF", createdBy: "Admin User", createdAt: "2026-05-26", updatedAt: "2026-07-10" },
  { id: "POL-006", name: "Public Data Standard", owner: "Governance Team", description: "Publication, review, and lifecycle requirements for approved public datasets.", appliesTo: "Reports", status: "Active", retentionPeriod: "3 Years", reviewFrequency: "Annual", archiveRule: "Archive after retention period", deletionRule: "Require admin approval before deletion", piiHandling: "No PII Collected", encryptionRequired: false, classification: "Public", riskLevel: "Low", approvalRequired: true, complianceStandard: "Internal Policy", createdBy: "Admin User", createdAt: "2026-04-12", updatedAt: "2026-07-01" },
];
