import type { ReportTemplate, RecentReport, ScheduledReportRow } from "./report-types";

export const mockTemplates: ReportTemplate[] = [
  // Maintenance Reports (4)
  {
    id: "maintenance-logs",
    category: "Maintenance",
    name: "Maintenance Logs",
    description: "All maintenance tasks, completed work orders, and technician activity logs",
    owner: "Maintenance Team",
    site: "Detroit",
    last: "Today, 10:32 AM",
    schedule: "Weekly",
    records: 1248,
    source: "Assets",
    formats: ["PDF", "Excel", "CSV"],
    status: "Ready",
  },
  {
    id: "equipment-history",
    category: "Maintenance",
    name: "Equipment History",
    description: "Full maintenance history per equipment asset including breakdowns and repairs",
    owner: "Maintenance Team",
    site: "Detroit",
    last: "Yesterday",
    schedule: "Monthly",
    records: 892,
    source: "Assets",
    formats: ["PDF", "Excel"],
    status: "Ready",
  },
  {
    id: "preventive-maintenance",
    category: "Maintenance",
    name: "Preventive Maintenance Schedule",
    description: "Upcoming PM tasks, due dates, assigned technicians, and compliance status",
    owner: "Plant Manager",
    site: "All Sites",
    last: "June 10",
    schedule: "Monthly",
    records: 156,
    source: "Assets",
    formats: ["PDF", "Excel", "CSV"],
    status: "Ready",
  },
  {
    id: "work-order-summary",
    category: "Maintenance",
    name: "Work Order Summary",
    description: "Work order completion, delays, backlog, and repair performance",
    owner: "Maintenance Team",
    site: "Frankfurt",
    last: "June 11",
    schedule: "Weekly",
    records: 640,
    source: "Assets",
    formats: ["PDF", "Excel"],
    status: "Ready",
  },
  // Production Reports (3)
  {
    id: "production-summary",
    category: "Production",
    name: "Production Summary",
    description: "Monthly production volumes, targets vs. actuals, and trend analysis",
    owner: "Plant Manager",
    site: "All Sites",
    last: "June 8",
    schedule: "Weekly",
    records: 2180,
    source: "Operations",
    formats: ["PDF", "Excel"],
    status: "Ready",
  },
  {
    id: "oee-report",
    category: "Production",
    name: "OEE Report",
    description: "Overall Equipment Effectiveness — availability, performance, and quality metrics",
    owner: "Operations",
    site: "Osaka",
    last: "Today, 07:00 AM",
    schedule: "Daily",
    records: 960,
    source: "Operations",
    formats: ["PDF", "Excel", "CSV"],
    status: "Ready",
  },
  {
    id: "line-performance",
    category: "Production",
    name: "Line Performance",
    description: "Per-line throughput, downtime events, and quality rejection rates",
    owner: "Production Team",
    site: "Frankfurt",
    last: "June 11",
    schedule: "Weekly",
    records: 1540,
    source: "Operations",
    formats: ["PDF", "Excel"],
    status: "Ready",
  },
  // Quality Reports (3)
  {
    id: "scrap-analysis",
    category: "Quality",
    name: "Scrap Analysis",
    description: "Scrap rates, rejection reasons, and material waste by line and product type",
    owner: "Quality Team",
    site: "Detroit",
    last: "June 11",
    schedule: "Weekly",
    records: 578,
    source: "Downtime",
    formats: ["PDF", "Excel", "CSV"],
    status: "Ready",
  },
  {
    id: "quality-inspection",
    category: "Quality",
    name: "Quality Inspection Report",
    description: "Inspection results, pass/fail rates, and out-of-spec items by batch and equipment",
    owner: "Quality Team",
    site: "All Sites",
    last: "Today, 09:45 AM",
    schedule: "Daily",
    records: 1024,
    source: "Downtime",
    formats: ["PDF", "Excel"],
    status: "Ready",
  },
  {
    id: "defect-report",
    category: "Quality",
    name: "Defect Report",
    description: "Defect categories, root cause analysis, and resolution actions per product family",
    owner: "Quality Manager",
    site: "Detroit",
    last: "June 9",
    schedule: "Weekly",
    records: 234,
    source: "Downtime",
    formats: ["PDF", "Excel", "CSV"],
    status: "Ready",
  },
  // Financial Reports (3)
  {
    id: "cost-analysis",
    category: "Financial",
    name: "Cost Analysis",
    description: "Operating costs, labor, materials, and overhead breakdown by department and site",
    owner: "Finance Team",
    site: "All Sites",
    last: "June 10",
    schedule: "Monthly",
    records: 412,
    source: "Financial Analytics",
    formats: ["PDF", "Excel"],
    status: "Ready",
  },
  {
    id: "profitability-report",
    category: "Financial",
    name: "Profitability Report",
    description: "Revenue, margin analysis, and cost-per-unit by product line and production site",
    owner: "Finance Director",
    site: "All Sites",
    last: "June 5",
    schedule: "Monthly",
    records: 189,
    source: "Financial Analytics",
    formats: ["PDF", "Excel"],
    status: "Ready",
  },
  {
    id: "downtime-cost-report",
    category: "Financial",
    name: "Downtime Cost Report",
    description: "Financial impact of production stoppages — cost per hour, per line, per reason code",
    owner: "Operations",
    site: "Detroit",
    last: "June 11",
    schedule: "Weekly",
    records: 302,
    source: "Financial Analytics",
    formats: ["PDF", "Excel", "CSV"],
    status: "Ready",
  },
  // Security Reports (3)
  {
    id: "security-summary",
    category: "Security",
    name: "Security Summary",
    description: "Authentication events, locked accounts, failed logins, and suspicious access patterns",
    owner: "Security Team",
    site: "All Sites",
    last: "Yesterday",
    schedule: "Daily",
    records: 760,
    source: "Security Operations",
    formats: ["PDF", "CSV"],
    status: "Ready",
  },
  {
    id: "api-access-report",
    category: "Security",
    name: "API Access Report",
    description: "API client usage, token status, unauthorized requests, and rate-limit violations",
    owner: "Security Team",
    site: "Production",
    last: "Today, 08:15 AM",
    schedule: "Daily",
    records: 1840,
    source: "API Security",
    formats: ["PDF", "Excel", "CSV"],
    status: "Ready",
  },
  {
    id: "audit-compliance",
    category: "Audit",
    name: "Audit Compliance Report",
    description: "Tamper-evident audit events, user actions, approvals, declines, and governance evidence",
    owner: "Compliance Team",
    site: "All Sites",
    last: "June 12",
    schedule: "Weekly",
    records: 2430,
    source: "Audit Log",
    formats: ["PDF", "CSV"],
    status: "Ready",
  },
];

export const mockScheduled: ScheduledReportRow[] = [
  { id: "sr-1", name: "Daily Production Report", frequency: "Daily", time: "06:00 AM", recipients: "Plant Managers", next: "Tomorrow", source: "Operations", active: true, category: "Production" },
  { id: "sr-2", name: "Weekly Maintenance Summary", frequency: "Weekly", time: "08:00 AM", recipients: "Maintenance Team", next: "Monday", source: "Assets", active: true, category: "Maintenance" },
  { id: "sr-3", name: "Monthly Financial Report", frequency: "Monthly", time: "09:00 AM", recipients: "Finance Team", next: "July 1", source: "Financial Analytics", active: true, category: "Financial" },
  { id: "sr-4", name: "Daily Security Digest", frequency: "Daily", time: "07:00 AM", recipients: "Security Team", next: "Tomorrow", source: "Security Operations", active: true, category: "Security" },
  { id: "sr-5", name: "Weekly OEE Report", frequency: "Weekly", time: "05:00 PM", recipients: "Operations", next: "Friday", source: "Operations", active: false, category: "Production" },
];

export const mockRecent: RecentReport[] = [
  { id: "r-1", name: "Maintenance Logs", date: "Today, 10:32 AM", generatedBy: "Sarah Johnson", format: "PDF", size: "2.3 MB", pages: 12 },
  { id: "r-2", name: "OEE Report", date: "Today, 07:00 AM", generatedBy: "Admin User", format: "Excel", size: "1.8 MB", pages: 8 },
  { id: "r-3", name: "Production Summary", date: "Yesterday", generatedBy: "Carlos Rivera", format: "PDF", size: "4.1 MB", pages: 18 },
  { id: "r-4", name: "Security Summary", date: "Yesterday", generatedBy: "Admin User", format: "PDF", size: "1.2 MB", pages: 6 },
  { id: "r-5", name: "Downtime Cost Report", date: "June 11", generatedBy: "Finance Team", format: "Excel", size: "0.9 MB", pages: 5 },
  { id: "r-6", name: "Quality Inspection Report", date: "June 10", generatedBy: "Quality Manager", format: "CSV", size: "0.6 MB", pages: 4 },
  { id: "r-7", name: "API Access Report", date: "June 10", generatedBy: "Security Team", format: "PDF", size: "1.6 MB", pages: 9 },
];

export const sites = ["All Sites", "Detroit", "Frankfurt", "Osaka", "São Paulo", "Dubai"];

export const owners = [
  "All Owners",
  "Maintenance Team",
  "Plant Manager",
  "Operations",
  "Production Team",
  "Quality Team",
  "Quality Manager",
  "Finance Team",
  "Finance Director",
  "Security Team",
  "Compliance Team",
  "Admin User",
];

export const categories = [
  "All",
  "Maintenance",
  "Production",
  "Quality",
  "Financial",
  "Security",
  "Governance",
  "Audit",
  "API Security",
] as const;

export const statuses = ["All", "Ready", "Generating", "Scheduled", "Error"] as const;

export const formats = ["All", "PDF", "Excel", "CSV"] as const;
