"use client";
import { useMemo,useState } from "react";
import { Download,Plus } from "lucide-react";
import { CreateUserModal } from "./create-user-modal";
import { UserFilters } from "./user-filters";
import { UserSecurityWarning } from "./user-security-warning";
import { UserStatsCards } from "./user-stats-cards";
import { initialUsers,type UserRole,type UserStatus } from "./users-data";
import { UsersTable } from "./users-table";
export function UsersPage(){const[query,setQuery]=useState("");const[site,setSite]=useState("All Sites");const[role,setRole]=useState<UserRole|"All Roles">("All Roles");const[status,setStatus]=useState<UserStatus|"All">("All");const[createOpen,setCreateOpen]=useState(false);const filteredUsers=useMemo(()=>{const search=query.trim().toLowerCase();return initialUsers.filter(user=>(!search||[user.name,user.email,user.role,...user.sites].join(" ").toLowerCase().includes(search))&&(site==="All Sites"||user.sites.includes(site))&&(role==="All Roles"||user.role===role)&&(status==="All"||user.status===status));},[query,role,site,status]);const usersWithoutMfa=initialUsers.filter(user=>user.status==="Active"&&user.mfa==="Disabled").length;return <div className="space-y-4 pb-5"><header className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-2xl font-bold tracking-tight">User Management</h1><p className="mt-1 text-sm text-muted-foreground">Manage accounts, roles, site access, and security settings</p></div><div className="flex gap-2"><button type="button" className="inline-flex h-9 items-center justify-center gap-1.5 rounded-lg border bg-card px-3 text-xs font-semibold hover:bg-muted"><Download className="size-3.5"/>Export</button><button type="button" onClick={()=>setCreateOpen(true)} className="inline-flex h-9 items-center justify-center gap-1.5 rounded-lg bg-primary px-3 text-xs font-semibold text-primary-foreground hover:bg-primary/90"><Plus className="size-3.5"/>Create User</button></div></header><UserSecurityWarning usersWithoutMfa={usersWithoutMfa}/><UserStatsCards users={initialUsers}/><UserFilters query={query} site={site} role={role} status={status} resultCount={filteredUsers.length} totalCount={initialUsers.length} onQueryChange={setQuery} onSiteChange={setSite} onRoleChange={setRole} onStatusChange={setStatus}/><UsersTable users={filteredUsers}/>{createOpen&&<CreateUserModal onClose={()=>setCreateOpen(false)}/>}</div>}
