export type UserStatus = "Active" | "Locked" | "Disabled" | "Pending";
export type MfaStatus = "Enforced" | "Enabled" | "Disabled";
export type UserRole = "Administrator" | "Plant Manager" | "Viewer" | "Quality Inspector" | "Finance Analyst" | "Audit Viewer";
export type PlatformUser = { id: string; name: string; email: string; initials: string; role: UserRole; sites: string[]; lastLogin: string; status: UserStatus; mfa: MfaStatus; failedAttempts?: number };
export const siteOptions = ["All Sites", "Detroit", "Frankfurt", "Osaka", "São Paulo", "Dubai", "Johannesburg"];
export const roleOptions: (UserRole | "All Roles")[] = ["All Roles", "Administrator", "Plant Manager", "Viewer", "Quality Inspector", "Finance Analyst", "Audit Viewer"];
export const statusOptions: (UserStatus | "All")[] = ["All", "Active", "Locked", "Disabled", "Pending"];
const userRows: [string, string, string, string, UserRole, string[], string, UserStatus, MfaStatus, number?][] = [
  ["u01","Admin User","admin@divu.io","AU","Administrator",["Detroit","Frankfurt","Osaka","São Paulo","Dubai"],"15m ago","Active","Enforced"], ["u02","Carlos Rivera","c.rivera@divu.io","CR","Plant Manager",["Detroit"],"4h ago","Active","Enabled"], ["u03","Anna Müller","a.muller@divu.io","AM","Plant Manager",["Frankfurt"],"2h ago","Active","Enabled"], ["u04","Kenji Tanaka","k.tanaka@divu.io","KT","Plant Manager",["Osaka"],"Yesterday","Active","Enabled"], ["u05","Lucas Ferreira","l.ferreira@divu.io","LF","Plant Manager",["São Paulo"],"6h ago","Active","Disabled"], ["u06","Rania Al-Hassan","r.alhassan@divu.io","RA","Plant Manager",["Dubai"],"3d ago","Active","Disabled"], ["u07","Sipho Ndlovu","s.ndlovu@divu.io","SN","Plant Manager",["Detroit","Osaka"],"2d ago","Active","Enabled"], ["u08","Sarah Johnson","s.johnson@divu.io","SJ","Viewer",["Detroit","Frankfurt"],"Yesterday","Locked","Disabled",3], ["u09","John Smith","j.smith@divu.io","JS","Viewer",["Detroit"],"8h ago","Active","Disabled"], ["u10","Mike Davis","m.davis@divu.io","MD","Viewer",["Detroit","Frankfurt"],"57m ago","Active","Enabled"], ["u11","Marcus Lee","m.lee@divu.io","ML","Viewer",["Frankfurt","Osaka"],"5d ago","Active","Disabled"], ["u12","Priya Sharma","p.sharma@divu.io","PS","Quality Inspector",["Detroit","São Paulo"],"1h ago","Active","Enforced"], ["u13","Elena Vasquez","e.vasquez@divu.io","EV","Finance Analyst",["Detroit","Frankfurt","São Paulo"],"3h ago","Active","Enforced"], ["u14","James Okafor","j.okafor@divu.io","JO","Audit Viewer",["Detroit","Frankfurt","Osaka","São Paulo","Dubai"],"7d ago","Active","Enabled"], ["u15","Former Employee","former@divu.io","FE","Viewer",[],"120d ago","Disabled","Disabled"], ["u16","Pending Invite","new.hire@client.com","PI","Viewer",["Detroit"],"Never","Pending","Disabled"]
];
export const initialUsers: PlatformUser[] = userRows.map(([id,name,email,initials,role,sites,lastLogin,status,mfa,failedAttempts]) => ({ id, name, email, initials, role, sites, lastLogin, status, mfa, ...(failedAttempts ? { failedAttempts } : {}) }));
