"use client";

import { useEffect, useState, type FormEvent } from "react";
import { Activity, Bell, Check, Copy, Edit3, LogOut, Monitor, ShieldCheck, X } from "lucide-react";

type Profile = { name:string; email:string; phone:string; department:string; jobTitle:string; site:string; timezone:string };
type Modal = "edit" | "password" | "sessions" | "token" | "logout" | null;
const initialProfile: Profile = { name:"Admin User", email:"admin@example.com", phone:"+1 (555) 000-0000", department:"Information Technology", jobTitle:"Platform Administrator", site:"Detroit Assembly", timezone:"America/Edmonton" };
const input = "mt-1.5 h-10 w-full rounded-lg border bg-background px-3 text-xs outline-none focus:ring-2 focus:ring-ring/30";

function Card({title, icon, children}:{title:string;icon?:React.ReactNode;children:React.ReactNode}){return <section className="rounded-xl border bg-card shadow-[var(--dv-shadow)]"><header className="flex items-center justify-between border-b px-4 py-3"><h2 className="text-sm font-bold">{title}</h2>{icon}</header>{children}</section>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:()=>void}){return <button type="button" role="switch" aria-checked={checked} onClick={onChange} className="grid min-h-12 w-full grid-cols-[minmax(0,1fr)_2.25rem] items-center gap-4 border-b px-4 py-3 text-left text-xs last:border-0"><span className="min-w-0">{label}</span><span className={`relative h-5 w-9 justify-self-end rounded-full ${checked?"bg-primary":"bg-muted"}`}><span className={`absolute top-0.5 size-4 rounded-full bg-white shadow transition-transform ${checked?"translate-x-[18px]":"translate-x-0.5"}`}/></span></button>}
function ModalShell({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){useEffect(()=>{const fn=(e:KeyboardEvent)=>e.key==="Escape"&&onClose();addEventListener("keydown",fn);return()=>removeEventListener("keydown",fn)},[onClose]);return <div className="fixed inset-0 z-[60] flex items-end justify-center bg-black/60 backdrop-blur-sm sm:items-center sm:p-5" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><section role="dialog" aria-modal="true" aria-label={title} className="max-h-[94vh] w-full max-w-xl overflow-y-auto rounded-t-2xl border bg-card shadow-2xl sm:rounded-2xl"><header className="flex items-center justify-between border-b p-4"><h2 className="font-bold">{title}</h2><button type="button" onClick={onClose} aria-label={`Close ${title}`} className="grid size-8 place-items-center rounded-lg hover:bg-muted"><X className="size-4"/></button></header>{children}</section></div>}

export function ProfilePage(){
 const [profile,setProfile]=useState(initialProfile); const [prefs,setPrefs]=useState({email:true,push:true,digest:false,api:false,security:true,reports:true}); const [modal,setModal]=useState<Modal>(null); const [success,setSuccess]=useState("");
 const activities=[["Viewed Financial Analytics","5 min ago"],["Updated governance policy","1 hour ago"],["Acknowledged governance alert","2 hours ago"],["Exported compliance report","3 hours ago"],["Reviewed audit log entries","Yesterday"]];
 const info=[["Full Name",profile.name],["Email Address",profile.email],["Phone",profile.phone],["Department",profile.department],["Role","Super Admin"],["Plant Access","All plants"],["User ID","1"],["Account Status","Active"],["Member Since","January 2024"],["Last Login","2026-01-10 09:14 UTC"]];
 return <div className="space-y-5 pb-8"><header className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-primary">Account</p><h1 className="mt-1 text-2xl font-bold tracking-tight">My Profile</h1><p className="mt-1 text-sm text-muted-foreground">Manage your account information and preferences</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={()=>setModal("logout")} className="inline-flex h-10 items-center gap-2 rounded-lg border border-destructive/30 px-4 text-xs font-semibold text-destructive hover:bg-destructive/10"><LogOut className="size-4"/>Log Out</button><button type="button" onClick={()=>setModal("edit")} className="inline-flex h-10 items-center gap-2 rounded-lg bg-primary px-4 text-xs font-semibold text-primary-foreground"><Edit3 className="size-4"/>Edit Profile</button></div></header>{success&&<div role="status" className="flex items-center gap-2 rounded-lg border border-emerald-500/30 bg-emerald-500/10 p-3 text-xs text-emerald-700 dark:text-emerald-300"><Check className="size-4"/>{success}</div>}
 <div className="grid gap-4 lg:grid-cols-[18rem_minmax(0,1fr)]"><div className="space-y-4"><Card title="Profile Summary"><div className="flex flex-col items-center p-5 text-center"><span className="grid size-20 place-items-center rounded-full border-2 border-primary bg-primary/10 text-2xl font-bold text-primary">AU</span><h2 className="mt-3 font-bold">{profile.name}</h2><p className="text-xs text-muted-foreground">{profile.email}</p><div className="mt-3 flex gap-2"><span className="rounded-md bg-primary/10 px-2 py-1 font-mono text-[9px] text-primary">Super Admin</span><span className="rounded-md bg-[var(--dv-badge-ok-bg)] px-2 py-1 font-mono text-[9px] text-[var(--dv-badge-ok-text)]">Active</span></div></div><div className="grid grid-cols-2 border-t p-4 text-center"><div><p className="text-[9px] text-muted-foreground">Member Since</p><strong className="text-xs">Jan 2024</strong></div><div><p className="text-[9px] text-muted-foreground">Last Login</p><strong className="text-xs">2 hrs ago</strong></div></div></Card><Card title="Recent Activity" icon={<Activity className="size-4 text-muted-foreground"/>}><div>{activities.map(([name,time])=><div key={name} className="flex gap-3 border-b p-3 last:border-0"><span className="grid size-8 shrink-0 place-items-center rounded-lg bg-muted"><Activity className="size-3.5"/></span><div><p className="text-[11px] font-semibold">{name}</p><p className="mt-1 font-mono text-[8px] text-muted-foreground">{time}</p></div></div>)}</div></Card></div>
 <div className="space-y-4"><Card title="Account Information"><dl>{info.map(([label,value])=><div key={label} className="grid gap-1 border-b px-4 py-3 last:border-0 sm:grid-cols-[11rem_1fr]"><dt className="text-[10px] text-muted-foreground">{label}</dt><dd className="text-xs font-semibold">{value}</dd></div>)}</dl></Card><Card title="Notification Preferences" icon={<Bell className="size-4 text-muted-foreground"/>}>{([['email','Email Notifications'],['push','Alert Push Notifications'],['digest','Weekly Summary Digest'],['api','API Activity Alerts'],['security','Security Incident Alerts'],['reports','Report Completion Alerts']] as const).map(([key,label])=><Toggle key={key} label={label} checked={prefs[key]} onChange={()=>setPrefs(s=>({...s,[key]:!s[key]}))}/>) }<p className="p-3 text-[9px] text-muted-foreground">TODO: persist preferences through the profile API.</p></Card><Card title="Security" icon={<ShieldCheck className="size-4 text-muted-foreground"/>}><SecurityRow title="Password" detail="Last changed 90 days ago" action="Change" onClick={()=>setModal("password")}/><SecurityRow title="Two-Factor Authentication" detail="Authenticator app enabled" action="Enabled"/><SecurityRow title="Active Sessions" detail="2 active sessions" action="Manage" onClick={()=>setModal("sessions")}/><SecurityRow title="API Access" detail="No personal API token active" action="Create Token" onClick={()=>setModal("token")}/></Card></div></div>
 {modal==="edit"&&<EditModal profile={profile} onClose={()=>setModal(null)} onSave={(p)=>{setProfile(p);setModal(null);setSuccess("Profile updated successfully.")}}/>}{modal==="password"&&<PasswordModal onClose={()=>setModal(null)} onSave={()=>{setModal(null);setSuccess("Password updated successfully.")}}/>}{modal==="sessions"&&<SessionsModal onClose={()=>setModal(null)}/>} {modal==="token"&&<TokenModal onClose={()=>setModal(null)}/>} {modal==="logout"&&<LogoutModal onClose={()=>setModal(null)}/>}</div>
}
function SecurityRow({title,detail,action,onClick}:{title:string;detail:string;action:string;onClick?:()=>void}){return <div className="grid items-center gap-3 border-b px-4 py-3 last:border-0 sm:grid-cols-[minmax(0,1fr)_7rem]"><div className="min-w-0"><p className="text-xs font-semibold">{title}</p><p className="mt-1 text-[9px] text-muted-foreground">{detail}</p></div><button type="button" onClick={onClick} className={`inline-flex h-8 w-28 items-center justify-center justify-self-start rounded-lg border px-3 text-[10px] font-semibold sm:justify-self-end ${action==="Enabled"?"border-emerald-500/20 bg-emerald-500/10 text-emerald-600":"hover:bg-muted"}`}>{action}</button></div>}
function EditModal({profile,onClose,onSave}:{profile:Profile;onClose:()=>void;onSave:(p:Profile)=>void}){const [form,setForm]=useState(profile);const field=(key:keyof Profile,label:string)=><label className="text-[10px] font-semibold">{label}<input value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className={input}/></label>;return <ModalShell title="Edit Profile" onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave(form)}} className="space-y-4 p-5"><div className="grid gap-4 sm:grid-cols-2">{field("name","Full Name")}{field("email","Email Address")}{field("phone","Phone")}{field("department","Department")}{field("jobTitle","Job Title")}{field("site","Default Site")}{field("timezone","Time Zone")}</div><Actions onClose={onClose} submit="Save Changes"/></form></ModalShell>}
function PasswordModal({onClose,onSave}:{onClose:()=>void;onSave:()=>void}){const [next,setNext]=useState("");const [confirm,setConfirm]=useState("");const [error,setError]=useState("");function submit(e:FormEvent){e.preventDefault();if(next.length<12||next!==confirm){setError("Passwords must match and contain at least 12 characters.");return}onSave()}return <ModalShell title="Change Password" onClose={onClose}><form onSubmit={submit} className="space-y-4 p-5">{["Current Password","New Password","Confirm New Password"].map((label,i)=><label key={label} className="block text-[10px] font-semibold">{label}<input required type="password" value={i===1?next:i===2?confirm:undefined} onChange={i===1?e=>setNext(e.target.value):i===2?e=>setConfirm(e.target.value):undefined} className={input}/></label>)}<p className="text-[9px] text-muted-foreground">Use 12+ characters with uppercase, lowercase, number, and symbol.</p>{error&&<p className="text-xs text-destructive">{error}</p>}<Actions onClose={onClose} submit="Update Password"/></form></ModalShell>}
function SessionsModal({onClose}:{onClose:()=>void}){const [sessions,setSessions]=useState([["Chrome on Windows","Current session · Calgary, AB · Active now",true],["Edge on Windows","2 hours ago · Calgary, AB",false],["Mobile Browser","Yesterday · Unknown location",false]] as [string,string,boolean][]);return <ModalShell title="Manage Active Sessions" onClose={onClose}><div className="space-y-3 p-5">{sessions.map(([name,detail,current])=><div key={name} className="flex items-center gap-3 rounded-lg border p-3"><Monitor className="size-4"/><div className="min-w-0 flex-1"><p className="text-xs font-semibold">{name}</p><p className="text-[9px] text-muted-foreground">{detail}</p></div>{!current&&<button type="button" onClick={()=>setSessions(s=>s.filter(x=>x[0]!==name))} className="h-8 rounded-lg border px-2 text-[9px] text-destructive">Revoke Session</button>}</div>)}<button type="button" onClick={onClose} className="h-10 w-full rounded-lg border text-xs font-semibold">Close</button></div></ModalShell>}
function TokenModal({onClose}:{onClose:()=>void}){const [created,setCreated]=useState(false);const [copied,setCopied]=useState(false);const [name,setName]=useState("");const [scopes,setScopes]=useState<string[]>(["read:profile"]);const token="divu_user_sk_••••••••••••A91F";return <ModalShell title="Create Personal API Token" onClose={onClose}><div className="space-y-4 p-5">{!created?<><label className="block text-[10px] font-semibold">Token Name<input value={name} onChange={e=>setName(e.target.value)} className={input}/></label><label className="block text-[10px] font-semibold">Expiry<select className={input}><option>30 days</option><option>90 days</option><option>1 year</option></select></label><fieldset><legend className="text-[10px] font-semibold">Scopes</legend><div className="mt-2 grid grid-cols-2 gap-2">{["read:profile","read:reports","read:audit","read:notifications"].map(scope=><label key={scope} className="rounded-lg border p-2 text-[10px]"><input type="checkbox" checked={scopes.includes(scope)} onChange={()=>setScopes(s=>s.includes(scope)?s.filter(x=>x!==scope):[...s,scope])} className="mr-2"/>{scope}</label>)}</div></fieldset><p className="rounded-lg border border-amber-500/30 bg-amber-500/10 p-3 text-[10px] text-amber-700 dark:text-amber-300">The token will be displayed once after creation. Copy and store it securely.</p><div className="grid grid-cols-2 gap-3"><button type="button" onClick={onClose} className="h-10 rounded-lg border text-xs">Cancel</button><button type="button" disabled={!name||!scopes.length} onClick={()=>setCreated(true)} className="h-10 rounded-lg bg-primary text-xs text-primary-foreground disabled:opacity-40">Generate Token</button></div></>:<><div className="rounded-lg bg-emerald-950 p-4 font-mono text-xs text-emerald-300">{token}</div><button type="button" onClick={()=>{navigator.clipboard?.writeText(token);setCopied(true)}} className="inline-flex h-10 w-full items-center justify-center gap-2 rounded-lg bg-primary text-xs text-primary-foreground"><Copy className="size-4"/>{copied?"Copied":"Copy Token"}</button></>}</div></ModalShell>}
function Actions({onClose,submit}:{onClose:()=>void;submit:string}){return <div className="flex items-center justify-end gap-3 border-t pt-4"><button type="button" onClick={onClose} className="h-10 w-32 rounded-lg border text-xs font-semibold">Cancel</button><button type="submit" className="h-10 w-32 rounded-lg bg-primary text-xs font-semibold text-primary-foreground">{submit}</button></div>}
function LogoutModal({onClose}:{onClose:()=>void}){async function logout(){await fetch("/api/auth/logout",{method:"POST"}).catch(()=>undefined);sessionStorage.removeItem("divu-access-token");localStorage.removeItem("divu-session");localStorage.removeItem("divu-user");window.location.assign("/login");}return <ModalShell title="Confirm Log Out" onClose={onClose}><div className="p-5"><div className="flex gap-3 rounded-xl border border-destructive/25 bg-destructive/10 p-4"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-destructive/15 text-destructive"><LogOut className="size-5"/></span><div><h3 className="text-sm font-semibold">Do you want to log out?</h3><p className="mt-1 text-xs leading-5 text-muted-foreground">You will need to sign in again to access the DIVU Analytics platform.</p></div></div><div className="mt-5 flex items-center justify-end gap-3"><button type="button" onClick={onClose} className="h-10 w-28 rounded-lg border text-xs font-semibold hover:bg-muted">Cancel</button><button type="button" onClick={logout} className="h-10 w-28 rounded-lg bg-destructive text-xs font-semibold text-destructive-foreground hover:bg-destructive/90">Log Out</button></div></div></ModalShell>}
