"use client";

import { useState } from "react";
import { BarChart3, Boxes, DollarSign, Filter, TrendingDown, TrendingUp, TriangleAlert } from "lucide-react";
import { cn } from "@/lib/utils";
import { lines, monthly, products, siteColor, sites } from "./financial-data";

type Tab = "overview" | "sites" | "products" | "oee" | "costs";
const tabs: { id: Tab; label: string }[] = [{ id: "overview", label: "Overview" }, { id: "sites", label: "Revenue by Site" }, { id: "products", label: "Margin by Product" }, { id: "oee", label: "OEE vs Profit" }, { id: "costs", label: "Cost Trends" }];
const fmt = (value: number) => value.toLocaleString("en-US");

function Card({ title, subtitle, children, className }: { title: string; subtitle?: string; children: React.ReactNode; className?: string }) {
  return <section className={cn("overflow-hidden rounded-xl border bg-card shadow-[var(--dv-shadow)]", className)}><header className="px-5 pt-5"><h2 className="text-base font-semibold">{title}</h2>{subtitle && <p className="mt-1 text-xs text-muted-foreground">{subtitle}</p>}</header><div className="p-5">{children}</div></section>;
}

function Kpis() {
  const data = [
    { label: "Revenue", value: "$11.8M", change: "+4.4%", note: "YTD 2026 · All Sites", icon: DollarSign, good: true },
    { label: "COGS", value: "$7.3M", change: "-4.5%", note: "Cost of Goods Sold", icon: BarChart3, good: false },
    { label: "Gross Margin", value: "38.1%", change: "+4.2%", note: "$4.5M absolute", icon: TrendingUp, good: true },
    { label: "Downtime Cost", value: "$358K", change: "-23.6%", note: "Est. production loss", icon: TriangleAlert, good: false },
    { label: "Scrap Cost", value: "$129K", change: "-13.6%", note: "Material waste YTD", icon: Boxes, good: false },
  ];
  return <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{data.map(({ icon: Icon, ...item }) => <article key={item.label} className="rounded-xl border bg-card p-5 shadow-[var(--dv-shadow)]"><div className="flex items-start justify-between"><span className="grid size-10 place-items-center rounded-lg bg-primary/10 text-primary"><Icon className="size-[18px]" /></span><span className={cn("flex items-center gap-1 text-xs font-semibold", item.good ? "text-[var(--dv-badge-ok-text)]" : "text-[var(--dv-badge-cr-text)]")}>{item.good ? <TrendingUp className="size-3" /> : <TrendingDown className="size-3" />}{item.change}</span></div><p className="mt-5 text-2xl font-bold tracking-tight">{item.value}</p><p className="mt-1 text-xs font-medium text-muted-foreground">{item.label}</p><p className="mt-2 text-[11px] text-muted-foreground">{item.note}</p></article>)}</div>;
}

function Bars({ data, max, suffix = "K" }: { data: { label: string; value: number; color?: string }[]; max: number; suffix?: string }) {
  return <div className="space-y-3">{data.map((item) => <div key={item.label} className="grid grid-cols-[6.5rem_1fr_4rem] items-center gap-3 text-xs"><span className="truncate text-muted-foreground">{item.label}</span><div className="h-7 overflow-hidden rounded bg-muted"><div className="h-full rounded" style={{ width: `${Math.max(2, item.value / max * 100)}%`, background: item.color ?? "var(--chart-1)" }} /></div><span className="font-mono text-[10px] text-muted-foreground">{fmt(item.value)}{suffix}</span></div>)}</div>;
}

function TrendChart({ values, max, color = "var(--chart-1)", target }: { values: number[]; max: number; color?: string; target?: number }) {
  const pts = values.map((v, i) => `${50 + i * 118},${190 - v / max * 150}`).join(" ");
  return <svg viewBox="0 0 680 225" className="h-auto w-full min-w-[34rem]" role="img" aria-label="Monthly trend chart"><g className="text-muted-foreground" stroke="currentColor" strokeOpacity=".2">{[40,90,140,190].map(y => <line key={y} x1="50" x2="650" y1={y} y2={y} strokeDasharray="4 4" />)}</g>{target && <line x1="50" x2="650" y1={190-target/max*150} y2={190-target/max*150} stroke="var(--chart-3)" strokeDasharray="6 4" />}<polyline points={pts} fill="none" stroke={color} strokeWidth="3" strokeLinejoin="round" />{values.map((v,i)=><circle key={i} cx={50+i*118} cy={190-v/max*150} r="4" fill={color} />)}{monthly.map((m,i)=><text key={m.month} x={50+i*118} y="215" textAnchor="middle" fill="currentColor" className="text-[11px] text-muted-foreground">{m.month}</text>)}</svg>;
}

const cell = "px-3 py-3 text-right whitespace-nowrap";
function Overview() {
  const rows = [
    ["Revenue ($K)", ...monthly.map(x=>fmt(x.revenue)), "11,840"], ["COGS ($K)", ...monthly.map(x=>fmt(x.cogs)), "7,331"],
    ["Gross Margin ($K)", ...monthly.map(x=>fmt(x.margin)), "4,509"], ["Downtime Cost ($K)", ...monthly.map(x=>x.downtime), "358"],
    ["Scrap Cost ($K)", ...monthly.map(x=>x.scrap), "129"], ["Gross Margin %", ...monthly.map(x=>`${x.gm}%`), "38.1%"],
  ];
  return <div className="space-y-5"><Card title="P&L Summary — YTD 2026" subtitle="Revenue, COGS, and margin breakdown by month"><div className="overflow-x-auto"><table className="w-full min-w-[46rem] text-xs"><thead className="text-muted-foreground"><tr><th className="px-3 py-3 text-left">Metric</th>{[...monthly.map(x=>x.month),"YTD"].map(x=><th className={cell} key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,ri)=><tr key={String(r[0])} className="border-t"><th className={cn("px-3 py-3 text-left", [0,2,5].includes(ri)&&"font-semibold")}>{r[0]}</th>{r.slice(1).map((v,i)=><td key={i} className={cn(cell,ri===0&&"font-semibold text-primary",ri===2&&"font-semibold text-[var(--dv-badge-ok-text)]",ri>=3&&"text-[var(--dv-badge-wa-text)]",i===6&&"bg-muted/70 font-semibold")}>{v}</td>)}</tr>)}</tbody></table></div></Card><Card title="Revenue vs Gross Margin — Monthly" subtitle="6-month trend with gross margin %"><div className="overflow-x-auto"><TrendChart values={monthly.map(x=>x.revenue)} max={2300} /></div><div className="mt-2 flex justify-center gap-5 text-[10px] text-muted-foreground"><span className="text-primary">● Revenue</span><span>● COGS</span><span className="text-[var(--dv-badge-ok-text)]">● Gross Margin</span></div></Card></div>;
}

function Sites() { const total={site:"Total / Avg",revenue:13420,cogs:8342,margin:5078,gm:38.1,downtime:377,scrap:154,oee:75}; return <div className="space-y-5"><div className="grid gap-5 xl:grid-cols-2"><Card title="Revenue by Site" subtitle="YTD 2026 · $K"><Bars max={10000} data={sites.map(s=>({label:s.site,value:s.revenue,color:s.color}))}/></Card><Card title="Gross Margin by Site" subtitle="% and absolute ($K)"><Bars max={3500} data={sites.map(s=>({label:s.site,value:s.margin,color:s.color}))}/></Card></div><FinancialTable title="Site Financial Summary" headers={["Site","Revenue","COGS","Gross Margin","GM %","Downtime","Scrap","OEE"]} rows={[...sites,total].map(s=>[s.site,`$${fmt(s.revenue)}K`,`$${fmt(s.cogs)}K`,`$${fmt(s.margin)}K`,`${s.gm}%`,`$${s.downtime}K`,`$${s.scrap}K`,`${s.oee}%`])}/></div> }

function Products() { return <div className="space-y-5"><div className="grid gap-5 xl:grid-cols-2"><Card title="Gross Margin by Product" subtitle="% margin — higher is better"><Bars max={50} suffix="%" data={products.map((p,i)=>({label:p.product,value:p.gm,color:i===0?"var(--chart-2)":i===5?"var(--chart-5)":"var(--chart-1)"}))}/></Card><Card title="Revenue vs Scrap Rate by Product" subtitle="Bubble = revenue, X-axis = scrap %"><div className="relative h-64 border-b border-l">{products.map((p,i)=><span key={p.product} title={`${p.product}: $${p.revenue}K, ${p.scrap}% scrap`} className="absolute grid place-items-center rounded-full bg-primary/70 text-[8px] text-white" style={{left:`${p.scrap/6*85+3}%`,bottom:`${p.revenue/4000*80+3}%`,width:24+p.revenue/180,height:24+p.revenue/180}}>{i+1}</span>)}</div><p className="mt-3 text-center text-[10px] text-muted-foreground">Scrap rate →</p></Card></div><FinancialTable title="Product Financial Detail" headers={["Product","Revenue $K","COGS $K","Gross Margin","GM %","Units","Scrap Rate"]} rows={products.map(p=>[p.product,`$${fmt(p.revenue)}`,`$${fmt(p.cogs)}`,`$${fmt(p.margin)}`,`${p.gm}%`,fmt(p.units),`${p.scrap}%`])}/></div> }

function Oee() { return <div className="space-y-5"><Card title="OEE vs Profit Margin — Production Lines" subtitle="Each dot = one production line. Size = revenue. Target zone: OEE ≥85%, Margin ≥38%"><div className="overflow-x-auto"><svg viewBox="0 0 800 330" className="min-w-[42rem]" role="img" aria-label="OEE versus profit margin scatter plot"><rect x="80" y="30" width="670" height="250" fill="var(--muted)" opacity=".2"/><g stroke="currentColor" strokeOpacity=".2" strokeDasharray="4 4">{[80,247,415,582,750].map(x=><line key={x} x1={x} x2={x} y1="30" y2="280"/>)}{[30,113,196,280].map(y=><line key={y} x1="80" x2="750" y1={y} y2={y}/>)}</g><line x1="616" x2="616" y1="30" y2="280" stroke="var(--chart-2)" strokeDasharray="6 4"/><line x1="80" x2="750" y1="130" y2="130" stroke="var(--chart-1)" strokeDasharray="6 4"/>{lines.map(l=><circle key={l[0]} cx={80+(l[2]-45)/55*670} cy={280-(l[3]-15)/35*250} r={7+l[4]/250} fill={siteColor(l[1])} fillOpacity=".75" stroke={siteColor(l[1])} strokeWidth="2"/>)}<text x="616" y="20" textAnchor="middle" fill="var(--chart-2)" fontSize="10">OEE 85%</text><text x="754" y="126" fill="var(--chart-1)" fontSize="10">38%</text><text x="415" y="315" textAnchor="middle" fill="currentColor" fontSize="11">OEE %</text></svg></div></Card><FinancialTable title="Line-Level OEE vs Profitability" headers={["Line","Site","OEE %","Profit Margin %","Revenue $K","Assessment"]} rows={lines.map(l=>[l[0],l[1],`${l[2]}%`,`${l[3]}%`,`$${l[4]}K`,<Badge key={l[0]} value={l[5]}/>])}/></div> }

function Badge({value}:{value:string}) { return <span className={cn("rounded-full px-2.5 py-1 text-[10px] font-semibold",value==="On Target"&&"bg-[var(--dv-badge-ok-bg)] text-[var(--dv-badge-ok-text)]",value==="Needs Attention"&&"bg-[var(--dv-badge-wa-bg)] text-[var(--dv-badge-wa-text)]",value==="Critical"&&"bg-[var(--dv-badge-cr-bg)] text-[var(--dv-badge-cr-text)]")}>{value}</span> }
function Costs() { return <div className="grid gap-5 xl:grid-cols-2"><Card title="Downtime Cost Trend" subtitle="Monthly estimated production loss ($K) — target <$55K/month"><div className="overflow-x-auto"><TrendChart values={monthly.map(x=>x.downtime)} max={85} color="var(--chart-3)" target={55}/></div></Card><Card title="Scrap Cost Trend" subtitle="Monthly material waste ($K) — target <$22K/month"><div className="overflow-x-auto"><TrendChart values={monthly.map(x=>x.scrap)} max={30} color="var(--chart-5)" target={22}/></div></Card><Card title="Combined Cost Impact — Monthly" subtitle="Downtime + scrap cost vs gross margin" className="xl:col-span-2"><div className="overflow-x-auto"><TrendChart values={monthly.map(x=>x.downtime+x.scrap)} max={110} color="var(--chart-5)"/></div></Card><Card title="Cost as % of Revenue — Trend" subtitle="Downtime and scrap as a share of monthly revenue" className="xl:col-span-2"><div className="overflow-x-auto"><TrendChart values={monthly.map(x=>(x.downtime+x.scrap)/x.revenue*100)} max={5} color="var(--chart-5)" target={3}/></div></Card></div> }

function FinancialTable({title,headers,rows}:{title:string;headers:string[];rows:(string|number|React.ReactNode)[][]}) { return <Card title={title} subtitle="YTD 2026 — all values in $K unless stated"><div className="overflow-x-auto"><table className="w-full min-w-[48rem] text-xs"><thead><tr>{headers.map((h,i)=><th key={h} className={cn("px-3 py-3 text-muted-foreground",i?"text-right":"text-left")}>{h}</th>)}</tr></thead><tbody>{rows.map((r,ri)=><tr key={ri} className={cn("border-t",ri===rows.length-1&&"bg-muted/60 font-semibold")}>{r.map((v,i)=><td key={i} className={cn("px-3 py-3 whitespace-nowrap",i?"text-right":"font-medium",(i===1||i===3)&&"text-primary")}>{v}</td>)}</tr>)}</tbody></table></div></Card> }

export function FinancialAnalytics() {
  const [tab,setTab]=useState<Tab>("overview");
  return <div className="space-y-5 pb-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-2xl font-bold tracking-tight">Financial Analytics</h1><p className="mt-1 text-sm text-muted-foreground">Manufacturing P&amp;L, cost intelligence, and profitability analysis</p></div><div className="flex items-center gap-2 rounded-xl border bg-card p-2 shadow-[var(--dv-shadow)]"><Filter className="ml-1 size-4 text-muted-foreground"/><select aria-label="Site" className="h-9 rounded-lg border bg-background px-3 text-xs outline-none" defaultValue="All Sites"><option>All Sites</option>{sites.map(s=><option key={s.site}>{s.site}</option>)}</select><select aria-label="Period" className="h-9 rounded-lg border bg-background px-3 text-xs outline-none" defaultValue="YTD 2026"><option>YTD 2026</option><option>FY 2025</option></select></div></header><Kpis/><nav className="overflow-x-auto border-b" role="tablist" aria-label="Financial analysis views"><div className="flex min-w-max">{tabs.map(t=><button key={t.id} role="tab" aria-selected={tab===t.id} onClick={()=>setTab(t.id)} className={cn("h-12 border-b-2 px-4 text-xs font-medium transition-colors",tab===t.id?"border-primary text-primary":"border-transparent text-muted-foreground hover:text-foreground")}>{t.label}</button>)}</div></nav>{tab==="overview"&&<Overview/>}{tab==="sites"&&<Sites/>}{tab==="products"&&<Products/>}{tab==="oee"&&<Oee/>}{tab==="costs"&&<Costs/>}</div>;
}
