"use client";

import { Eye, Lock, Pencil, PlugZap, ShieldCheck, Trash2 } from "lucide-react";
import type { IndustrialDataSource } from "./data-input-data";
import { DataInputStatusBadge } from "./data-input-status-badge";

export function DataSourceCard({ source, onView, onEdit, onTest, onDelete }: { source: IndustrialDataSource; onView: () => void; onEdit: () => void; onTest: () => void; onDelete: () => void }) {
  return <article className="rounded-xl border bg-card p-5 shadow-[var(--dv-shadow)]"><div className="flex items-start gap-3"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><PlugZap className="size-5" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{source.name}</p><p className="mt-1 text-xs text-muted-foreground">{source.type} · {source.facility}</p></div><DataInputStatusBadge status={source.status} /></div><div className="mt-4 grid grid-cols-2 gap-3 border-y py-4 text-xs"><div><p className="text-[10px] uppercase text-muted-foreground">Dataset</p><p className="mt-1 font-medium">{source.dataset}</p></div><div><p className="text-[10px] uppercase text-muted-foreground">Sync</p><p className="mt-1 font-medium">{source.syncFrequency}</p></div><div><p className="text-[10px] uppercase text-muted-foreground">Authentication</p><p className="mt-1 font-medium">{source.authenticationMethod}</p></div><div><p className="text-[10px] uppercase text-muted-foreground">Records</p><p className="mt-1 font-mono font-semibold">{source.totalRecords.toLocaleString()}</p></div></div><p className="mt-4 truncate rounded-lg bg-muted/60 px-3 py-2 font-mono text-[9px] text-muted-foreground">{source.endpoint}</p><div className="mt-3 flex flex-wrap gap-2">{source.encryption && <span className="inline-flex items-center gap-1 rounded bg-[var(--dv-badge-ok-bg)] px-2 py-1 text-[9px] text-[var(--dv-badge-ok-text)]"><Lock className="size-3" />Encrypted</span>}{source.validation && <span className="inline-flex items-center gap-1 rounded bg-primary/10 px-2 py-1 text-[9px] text-primary"><ShieldCheck className="size-3" />Validation</span>}</div><div className="mt-4 flex flex-wrap justify-end gap-1 border-t pt-3"><button type="button" onClick={onView} title="View source" className="grid size-8 place-items-center rounded-md text-muted-foreground hover:bg-muted hover:text-foreground"><Eye className="size-3.5" /></button><button type="button" onClick={onEdit} title="Edit source" className="grid size-8 place-items-center rounded-md text-muted-foreground hover:bg-muted hover:text-foreground"><Pencil className="size-3.5" /></button><button type="button" onClick={onTest} title="Test connection" className="grid size-8 place-items-center rounded-md text-primary hover:bg-primary/10"><PlugZap className="size-3.5" /></button><button type="button" onClick={onDelete} title="Delete source" className="grid size-8 place-items-center rounded-md text-muted-foreground hover:bg-destructive/10 hover:text-destructive"><Trash2 className="size-3.5" /></button></div></article>;
}
