"use client";

import { Eye, RotateCcw, Trash2 } from "lucide-react";
import type { DataImportRecord } from "./data-input-data";
import { DataInputStatusBadge } from "./data-input-status-badge";

export function RecentImportsTable({ imports, onDelete, onRetry }: { imports: DataImportRecord[]; onDelete: (id: string) => void; onRetry: (id: string) => void }) {
  return <section><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-semibold">Recent Imports</h2><span className="font-mono text-[10px] text-muted-foreground">{imports.length} audited jobs</span></div><div className="overflow-hidden rounded-xl border bg-card shadow-[var(--dv-shadow)]"><div className="overflow-x-auto"><table className="w-full min-w-[940px] text-left"><thead className="border-b bg-muted/40"><tr>{["ID", "Source", "Dataset", "Records", "Validation", "Processing", "Time", "Actions"].map((heading) => <th key={heading} className="px-4 py-3 font-mono text-[9px] uppercase tracking-[0.1em] text-muted-foreground">{heading}</th>)}</tr></thead><tbody>{imports.map((item) => <tr key={item.id} className="border-b last:border-0 hover:bg-muted/30"><td className="px-4 py-3 font-mono text-[10px] text-primary">{item.id}<span className="mt-1 block text-[8px] text-muted-foreground">{item.auditReference}</span></td><td className="max-w-48 px-4 py-3"><p className="truncate text-xs font-semibold">{item.source}</p><p className="mt-0.5 text-[10px] text-muted-foreground">{item.facility}</p></td><td className="px-4 py-3 text-xs">{item.dataset}</td><td className="px-4 py-3 font-mono text-xs font-semibold">{item.records.toLocaleString()}</td><td className="px-4 py-3"><DataInputStatusBadge status={item.validationStatus} /></td><td className="px-4 py-3"><DataInputStatusBadge status={item.processingStatus} /></td><td className="whitespace-nowrap px-4 py-3 font-mono text-[10px] text-muted-foreground">{item.importTime}</td><td className="px-4 py-3"><div className="flex gap-1"><button type="button" title="View audited import" className="grid size-8 place-items-center rounded-md text-muted-foreground hover:bg-muted hover:text-foreground"><Eye className="size-3.5" /></button>{item.processingStatus === "Failed" && <button type="button" title="Retry import" onClick={() => onRetry(item.id)} className="grid size-8 place-items-center rounded-md text-primary hover:bg-primary/10"><RotateCcw className="size-3.5" /></button>}<button type="button" title="Remove local import record" onClick={() => onDelete(item.id)} className="grid size-8 place-items-center rounded-md text-muted-foreground hover:bg-destructive/10 hover:text-destructive"><Trash2 className="size-3.5" /></button></div></td></tr>)}</tbody></table></div></div></section>;
}
