"use client";
import { Activity, Clock3, X } from "lucide-react";
import type { AuditEvent } from "./audit-log-data";
import { AuditActionBadge, AuditResourceBadge, AuditStatusBadge } from "./audit-log-badges";
import { useEffect } from "react";

export function AuditEventRow({ event, onSelect }: { event: AuditEvent; onSelect: (event: AuditEvent) => void }) {
  return <button type="button" onClick={() => onSelect(event)} className="grid w-full gap-2 border-t px-3 py-3 text-left transition-colors first:border-t-0 hover:bg-muted/40 sm:grid-cols-[minmax(0,1fr)_auto] sm:px-4">
    <div className="flex min-w-0 gap-3"><span className="mt-0.5 grid size-7 shrink-0 place-items-center rounded-lg bg-primary/10 text-primary"><Activity className="size-3.5" /></span><div className="min-w-0"><div className="flex flex-wrap items-center gap-x-2 gap-y-1"><span className="text-xs font-bold">{event.user}</span><span className="text-[10px] text-muted-foreground">{event.role}</span><AuditActionBadge action={event.action} /><AuditResourceBadge resource={event.resource} /></div><p className="mt-0.5 text-[11px] font-medium">{event.source}</p><p className="mt-1 truncate text-[10px] text-muted-foreground">{event.detail}</p></div></div>
    <div className="flex items-center justify-between gap-3 pl-10 sm:block sm:min-w-24 sm:pl-0 sm:text-right"><AuditStatusBadge status={event.status} /><div className="mt-1 text-[9px] text-muted-foreground"><span className="inline-flex items-center gap-1"><Clock3 className="size-2.5" />{event.relativeTime}</span><span className="ml-3 font-mono sm:ml-0 sm:block">{event.ip}</span></div></div>
  </button>;
}

export function AuditEventDetailModal({ event, onClose }: { event: AuditEvent; onClose: () => void }) {
  useEffect(() => { const handler = (e: KeyboardEvent) => e.key === "Escape" && onClose(); window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, [onClose]);
  const fields = [["User", event.user], ["Role", event.role], ["IP Address", event.ip], ["Site", event.site], ["Session ID", event.sessionId], ["Duration", event.duration ?? "Not recorded"], ["Timestamp", event.timestamp], ["Event ID", event.id]];
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/65 backdrop-blur-sm sm:items-center sm:p-5" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><section role="dialog" aria-modal="true" aria-labelledby="audit-event-title" className="max-h-[92vh] w-full max-w-lg overflow-y-auto rounded-t-2xl border bg-card shadow-2xl sm:rounded-2xl"><header className="flex items-start gap-3 border-b p-5"><span className="grid size-10 place-items-center rounded-xl bg-primary/10 text-primary"><Activity className="size-5" /></span><div className="min-w-0 flex-1"><h2 id="audit-event-title" className="font-bold">{event.action} — {event.resource}</h2><p className="mt-0.5 text-xs text-muted-foreground">{event.source}</p></div><button type="button" onClick={onClose} aria-label="Close event details" className="grid size-8 place-items-center rounded-lg hover:bg-muted"><X className="size-4" /></button></header><div className="space-y-4 p-5"><div className="flex gap-2"><AuditStatusBadge status={event.status} /><AuditResourceBadge resource={event.resource} /></div><p className="rounded-xl border bg-muted/40 p-4 text-xs leading-5">{event.detail}</p><dl className="grid grid-cols-2 gap-x-5 gap-y-4">{fields.map(([label, value]) => <div key={label}><dt className="text-[9px] text-muted-foreground">{label}</dt><dd className="mt-1 break-words font-mono text-[11px] font-semibold">{value}</dd></div>)}</dl><button type="button" onClick={onClose} className="h-9 w-full rounded-lg border text-xs font-semibold hover:bg-muted">Close</button></div></section></div>;
}
