export type AuditStatus = "Success" | "Warning" | "Failed" | "Blocked";

export type AuditEvent = {
  id: string; user: string; role: string; action: string; resource: string;
  source: string; detail: string; status: AuditStatus; timestamp: string;
  relativeTime: string; ip: string; site: string; sessionId: string; duration?: string;
};

const coreEvents: Omit<AuditEvent, "id">[] = [
  { user: "Admin User", role: "Administrator", action: "Login", resource: "Authentication", source: "Web App", detail: "Successful login from Chrome/Windows", status: "Success", timestamp: "Jul 13, 2026, 10:41:30 PM", relativeTime: "5m ago", ip: "203.0.113.12", site: "Detroit", sessionId: "sess-9a1f", duration: "340ms" },
  { user: "Carlos Rivera", role: "Plant Manager", action: "Approve", resource: "Activity", source: "Delete Product Request", detail: "Approved deletion of Industrial Valve Set — Type A", status: "Success", timestamp: "Jul 13, 2026, 10:35:30 PM", relativeTime: "11m ago", ip: "192.168.1.45", site: "Detroit", sessionId: "sess-7c2d", duration: "120ms" },
  { user: "Sarah Johnson", role: "Plant Manager", action: "Delete", resource: "Sensor", source: "Flow Meter D3", detail: "Delete request submitted — awaiting Super Admin approval", status: "Warning", timestamp: "Jul 13, 2026, 10:29:10 PM", relativeTime: "17m ago", ip: "192.168.1.88", site: "Detroit", sessionId: "sess-41bc" },
  { user: "Marcus Lee", role: "Plant Manager", action: "Update", resource: "Role", source: "Viewer Role Permissions", detail: "Permission escalation rejected — insufficient privileges", status: "Failed", timestamp: "Jul 13, 2026, 10:22:02 PM", relativeTime: "24m ago", ip: "10.0.0.34", site: "Osaka", sessionId: "sess-84de", duration: "92ms" },
  { user: "Admin User", role: "Administrator", action: "Configure", resource: "Settings", source: "Dark Mode Toggle", detail: "System theme configuration updated", status: "Success", timestamp: "Jul 13, 2026, 10:15:11 PM", relativeTime: "31m ago", ip: "203.0.113.12", site: "Detroit", sessionId: "sess-9a1f" },
  { user: "Anna Müller", role: "Plant Manager", action: "Export", resource: "Report", source: "Maintenance Logs Jun 2026", detail: "Exported CSV — 3 records — 2.4KB", status: "Success", timestamp: "Jul 13, 2026, 10:01:00 PM", relativeTime: "45m ago", ip: "192.168.2.11", site: "Berlin", sessionId: "sess-a02c" },
  { user: "John Smith", role: "Viewer", action: "Access Denied", resource: "Financial", source: "Revenue Dashboard", detail: "Role ‘Viewer’ does not have financial_view permission", status: "Blocked", timestamp: "Jul 13, 2026, 9:48:00 PM", relativeTime: "58m ago", ip: "172.16.0.22", site: "Austin", sessionId: "sess-19fd" },
  { user: "Admin User", role: "Administrator", action: "Decline", resource: "Activity", source: "Maintenance Request", detail: "Activity request declined after compliance review", status: "Success", timestamp: "Jul 13, 2026, 9:40:00 PM", relativeTime: "1h ago", ip: "203.0.113.12", site: "Detroit", sessionId: "sess-9a1f" },
  { user: "Kenji Tanaka", role: "Plant Manager", action: "View", resource: "Asset", source: "CNC Lathe #4", detail: "Viewed asset details and maintenance history", status: "Success", timestamp: "Jul 13, 2026, 9:36:00 PM", relativeTime: "1h ago", ip: "192.168.3.19", site: "Osaka", sessionId: "sess-73ab" },
  { user: "Kenji Tanaka", role: "Plant Manager", action: "Update", resource: "Sensor", source: "Vision Inspection Calibration", detail: "Sensor recalibrated — accuracy restored to 99.8%", status: "Success", timestamp: "Jul 13, 2026, 8:46:00 PM", relativeTime: "2h ago", ip: "192.168.3.19", site: "Osaka", sessionId: "sess-73ab" },
  { user: "Lucas Ferreira", role: "Plant Manager", action: "Update", resource: "Asset", source: "Press Line 2", detail: "Preventive maintenance schedule updated", status: "Success", timestamp: "Jul 13, 2026, 8:20:00 PM", relativeTime: "2h ago", ip: "10.20.3.14", site: "São Paulo", sessionId: "sess-f19a" },
  { user: "Rania Al-Hassan", role: "Plant Manager", action: "Login", resource: "Authentication", source: "Web App", detail: "Unrecognized device challenged with MFA", status: "Warning", timestamp: "Jul 13, 2026, 6:30:00 PM", relativeTime: "4h ago", ip: "198.51.100.7", site: "Dubai", sessionId: "sess-2e41" },
  { user: "Mike Davis", role: "Viewer", action: "Access Denied", resource: "Dashboard", source: "Executive KPI Dashboard", detail: "Dashboard access blocked by role policy", status: "Blocked", timestamp: "Jul 13, 2026, 5:10:00 PM", relativeTime: "5h ago", ip: "172.18.4.12", site: "Austin", sessionId: "sess-c13d" },
  { user: "John Smith", role: "Viewer", action: "Access Denied", resource: "Report", source: "Quarterly Risk Report", detail: "Report export blocked by data classification policy", status: "Blocked", timestamp: "Jul 13, 2026, 4:55:00 PM", relativeTime: "6h ago", ip: "172.16.0.22", site: "Austin", sessionId: "sess-19fd" },
  { user: "Sipho Ndlovu", role: "Plant Manager", action: "Update", resource: "Site", source: "Johannesburg Plant", detail: "Emergency contact roster updated", status: "Success", timestamp: "Jul 12, 2026, 4:30:00 PM", relativeTime: "Yesterday", ip: "10.31.1.8", site: "Johannesburg", sessionId: "sess-d70e" },
  { user: "Admin User", role: "Administrator", action: "Create", resource: "User", source: "User Management", detail: "Provisioned a new read-only operator account", status: "Success", timestamp: "Jul 12, 2026, 3:10:00 PM", relativeTime: "Yesterday", ip: "203.0.113.12", site: "Detroit", sessionId: "sess-9a1f" },
  { user: "Carlos Rivera", role: "Plant Manager", action: "View", resource: "Dashboard", source: "Operations Overview", detail: "Viewed plant production dashboard", status: "Success", timestamp: "Jul 12, 2026, 2:30:00 PM", relativeTime: "Yesterday", ip: "192.168.1.45", site: "Detroit", sessionId: "sess-7c2d" },
  { user: "Anna Müller", role: "Plant Manager", action: "Update", resource: "Sensor", source: "Temperature Probe B7", detail: "Updated alert threshold from 85°C to 82°C", status: "Success", timestamp: "Jul 12, 2026, 1:15:00 PM", relativeTime: "Yesterday", ip: "192.168.2.11", site: "Berlin", sessionId: "sess-a02c" },
  { user: "Sarah Johnson", role: "Plant Manager", action: "Update", resource: "Role", source: "Operator Permissions", detail: "Role update rejected by separation-of-duties policy", status: "Failed", timestamp: "Jul 12, 2026, 12:20:00 PM", relativeTime: "Yesterday", ip: "192.168.1.88", site: "Detroit", sessionId: "sess-41bc" },
  { user: "Marcus Lee", role: "Plant Manager", action: "Login", resource: "Authentication", source: "Mobile App", detail: "Successful login with passkey", status: "Success", timestamp: "Jul 12, 2026, 11:10:00 AM", relativeTime: "Yesterday", ip: "10.0.0.34", site: "Osaka", sessionId: "sess-84de" },
  { user: "Admin User", role: "Administrator", action: "Configure", resource: "Settings", source: "Session Policy", detail: "Reduced privileged session timeout to 15 minutes", status: "Success", timestamp: "Jul 12, 2026, 10:00:00 AM", relativeTime: "Yesterday", ip: "203.0.113.12", site: "Detroit", sessionId: "sess-9a1f" },
  { user: "Lucas Ferreira", role: "Plant Manager", action: "Export", resource: "Report", source: "Asset Availability", detail: "Exported weekly availability report", status: "Success", timestamp: "Jul 12, 2026, 9:30:00 AM", relativeTime: "Yesterday", ip: "10.20.3.14", site: "São Paulo", sessionId: "sess-f19a" },
  { user: "Carlos Rivera", role: "Plant Manager", action: "Update", resource: "Activity", source: "Shift Handover", detail: "Updated shift handover notes", status: "Success", timestamp: "Jul 12, 2026, 8:30:00 AM", relativeTime: "Yesterday", ip: "192.168.1.45", site: "Detroit", sessionId: "sess-7c2d" },
  { user: "Mike Davis", role: "Viewer", action: "View", resource: "Asset", source: "Packaging Robot 6", detail: "Viewed asset status summary", status: "Success", timestamp: "Jul 11, 2026, 5:00:00 PM", relativeTime: "2d ago", ip: "172.18.4.12", site: "Austin", sessionId: "sess-c13d" },
  { user: "Rania Al-Hassan", role: "Plant Manager", action: "Approve", resource: "Activity", source: "Maintenance Work Order", detail: "Approved scheduled pump maintenance", status: "Success", timestamp: "Jul 11, 2026, 3:00:00 PM", relativeTime: "2d ago", ip: "198.51.100.7", site: "Dubai", sessionId: "sess-2e41" },
  { user: "Admin User", role: "Administrator", action: "Update", resource: "Role", source: "Plant Manager Role", detail: "Added sensor calibration permission", status: "Success", timestamp: "Jul 11, 2026, 1:00:00 PM", relativeTime: "2d ago", ip: "203.0.113.12", site: "Detroit", sessionId: "sess-9a1f" },
  { user: "Anna Müller", role: "Plant Manager", action: "View", resource: "Financial", source: "Maintenance Budget", detail: "Viewed approved maintenance budget", status: "Success", timestamp: "Jul 11, 2026, 11:00:00 AM", relativeTime: "2d ago", ip: "192.168.2.11", site: "Berlin", sessionId: "sess-a02c" },
  { user: "Sipho Ndlovu", role: "Plant Manager", action: "Login", resource: "Authentication", source: "Web App", detail: "Successful login from managed workstation", status: "Success", timestamp: "Jul 11, 2026, 8:00:00 AM", relativeTime: "2d ago", ip: "10.31.1.8", site: "Johannesburg", sessionId: "sess-d70e" },
  { user: "John Smith", role: "Viewer", action: "Delete", resource: "User", source: "User Management", detail: "Account deletion blocked — administrator permission required", status: "Blocked", timestamp: "Jul 10, 2026, 4:00:00 PM", relativeTime: "3d ago", ip: "172.16.0.22", site: "Austin", sessionId: "sess-19fd" },
  { user: "Kenji Tanaka", role: "Plant Manager", action: "View", resource: "Site", source: "Osaka Plant", detail: "Viewed site compliance controls", status: "Success", timestamp: "Jul 10, 2026, 2:00:00 PM", relativeTime: "3d ago", ip: "192.168.3.19", site: "Osaka", sessionId: "sess-73ab" },
];

export const auditEvents: AuditEvent[] = coreEvents.map((event, index) => ({ ...event, id: `e${String(index + 1).padStart(3, "0")}` }));
export const auditStats = { Total: 30, Success: 22, Warning: 2, Failed: 2, Blocked: 4 } as const;
export const resourceOrder = ["Authentication", "Activity", "Sensor", "Role", "Settings", "Report", "Financial", "Asset", "Dashboard", "Site", "User"];

