"use client";
import { useMemo, useState } from "react";
import { ChevronRight, Download, Filter, History, List, Search, Shield, UserRound } from "lucide-react";
import { auditEvents, auditStats, resourceOrder, type AuditEvent, type AuditStatus } from "./audit-log-data";
import { AuditEventDetailModal, AuditEventRow } from "./audit-event";

type Tab = "timeline" | "resources" | "users";
const users = [...new Set(auditEvents.map((event) => event.user))];
const actions = [...new Set(auditEvents.map((event) => event.action))];

function StatsCards() { const config = [{ key: "Total", label: "Total Events", style: "bg-card" }, { key: "Success", label: "Success", style: "bg-emerald-500/8" }, { key: "Warning", label: "Warning", style: "bg-amber-500/8" }, { key: "Failed", label: "Failed", style: "bg-red-500/8" }, { key: "Blocked", label: "Blocked", style: "bg-slate-500/8" }] as const; return <div className="grid grid-cols-2 gap-2 lg:grid-cols-5">{config.map((item) => <div key={item.key} className={`rounded-xl border p-4 ${item.style}`}><div className="flex items-center gap-2"><span className="size-2 rounded-full bg-primary"/><strong className="text-lg">{auditStats[item.key]}</strong></div><p className="mt-1 pl-4 text-[10px] text-muted-foreground">{item.label}</p></div>)}</div>; }

function Select({ value, onChange, children, label }: { value: string; onChange: (value: string) => void; children: React.ReactNode; label: string }) { return <select aria-label={label} value={value} onChange={(e) => onChange(e.target.value)} className="h-9 rounded-lg border bg-card px-3 text-[11px] outline-none focus:ring-2 focus:ring-ring">{children}</select>; }

function Timeline({ events, onSelect }: { events: AuditEvent[]; onSelect: (event: AuditEvent) => void }) { return <section className="overflow-hidden rounded-xl border bg-card"><header className="flex items-center justify-between bg-muted/50 px-4 py-3 font-mono text-[9px] uppercase tracking-wider text-muted-foreground"><span>Audit events — newest first</span><span>{events.length} results</span></header>{events.length ? events.map((event) => <AuditEventRow key={event.id} event={event} onSelect={onSelect} />) : <p className="p-10 text-center text-sm text-muted-foreground">No audit events match these filters.</p>}</section>; }

function ResourceHistory({ onSelect }: { onSelect: (event: AuditEvent) => void }) { const [resource, setResource] = useState(""); const events = auditEvents.filter((event) => event.resource === resource); return <div className="space-y-4"><div className="flex items-center gap-3"><span className="text-[11px] text-muted-foreground">View history for:</span><Select label="Select resource history" value={resource} onChange={setResource}><option value="">— Select a resource —</option>{resourceOrder.map((item) => <option key={item}>{item}</option>)}</Select></div>{!resource ? <div className="grid gap-2 md:grid-cols-2 xl:grid-cols-3">{resourceOrder.map((item) => { const matches = auditEvents.filter((event) => event.resource === item); const issues = matches.filter((event) => event.status !== "Success").length; return <button key={item} onClick={() => setResource(item)} className="flex items-center gap-3 rounded-xl border bg-card p-3 text-left hover:bg-muted/40"><span className="grid size-9 place-items-center rounded-xl bg-primary/10 text-primary"><Shield className="size-4" /></span><span className="flex-1"><strong className="block text-xs">{item}</strong><span className="text-[9px] text-muted-foreground">{matches.length} events</span></span>{issues > 0 && <span className="rounded-full bg-red-500/10 px-2 py-1 text-[9px] text-red-600">{issues} issues</span>}<ChevronRight className="size-4 text-muted-foreground" /></button>; })}</div> : <div className="space-y-3"><button onClick={() => setResource("")} className="text-[10px] text-primary">← All Resources</button><Timeline events={events} onSelect={onSelect} /></div>}</div>; }

function UserHistory({ onSelect }: { onSelect: (event: AuditEvent) => void }) { const [user, setUser] = useState(""); const events = auditEvents.filter((event) => event.user === user); const role = events[0]?.role; const initials = (name: string) => name.split(" ").map((part) => part[0]).join("").slice(0, 2); return <div className="space-y-4"><div className="flex items-center gap-3"><span className="text-[11px] text-muted-foreground">View history for:</span><Select label="Select user history" value={user} onChange={setUser}><option value="">— Select a user —</option>{users.map((item) => <option key={item}>{item}</option>)}</Select></div>{!user ? <div className="grid gap-2 md:grid-cols-2 xl:grid-cols-3">{users.map((item) => { const matches = auditEvents.filter((event) => event.user === item); const issues = matches.filter((event) => event.status !== "Success").length; return <button key={item} onClick={() => setUser(item)} className="flex items-center gap-3 rounded-xl border bg-card p-3 text-left hover:bg-muted/40"><span className="grid size-9 place-items-center rounded-full bg-blue-600 text-[10px] font-bold text-white">{initials(item)}</span><span className="flex-1"><strong className="block text-xs">{item}</strong><span className="text-[9px] text-muted-foreground">{matches[0].role} · {matches.length} events</span><span className="block text-[9px] text-muted-foreground">Last seen: {matches[0].relativeTime}</span></span>{issues > 0 && <span className="rounded-full bg-red-500/10 px-2 py-1 text-[9px] text-red-600">{issues} issues</span>}<ChevronRight className="size-4 text-muted-foreground" /></button>; })}</div> : <div className="space-y-3"><section className="flex flex-wrap items-center gap-3 rounded-xl border bg-card p-4"><span className="grid size-10 place-items-center rounded-full bg-blue-600 text-xs font-bold text-white">{initials(user)}</span><div className="mr-auto"><strong className="text-sm">{user}</strong><p className="text-[10px] text-muted-foreground">{role} · {events[0]?.site}</p></div><div className="flex flex-wrap gap-3 font-mono text-[9px]"><span>Total: {events.length}</span>{(["Success", "Warning", "Failed", "Blocked"] as AuditStatus[]).map((status) => <span key={status}>{status}: {events.filter((e) => e.status === status).length}</span>)}</div><button onClick={() => setUser("")} className="text-[10px] text-primary">← All Users</button></section><Timeline events={events} onSelect={onSelect} /></div>}</div>; }

export function AuditLogPage() {
  const [tab, setTab] = useState<Tab>("timeline"); const [query, setQuery] = useState(""); const [user, setUser] = useState("All Users"); const [action, setAction] = useState("All Actions"); const [resource, setResource] = useState("All Resources"); const [status, setStatus] = useState("All"); const [selected, setSelected] = useState<AuditEvent | null>(null);
  const filtered = useMemo(() => { const q = query.toLowerCase().trim(); return auditEvents.filter((event) => (!q || [event.user, event.action, event.resource, event.ip, event.detail, event.source].join(" ").toLowerCase().includes(q)) && (user === "All Users" || event.user === user) && (action === "All Actions" || event.action === action) && (resource === "All Resources" || event.resource === resource) && (status === "All" || event.status === status)); }, [query, user, action, resource, status]);
  const exportCsv = () => { const rows = [["Event ID", "Timestamp", "User", "Role", "Action", "Resource", "Source", "Status", "IP Address", "Details"], ...filtered.map((e) => [e.id, e.timestamp, e.user, e.role, e.action, e.resource, e.source, e.status, e.ip, e.detail])]; const csv = rows.map((row) => row.map((cell) => `"${cell.replaceAll('"', '""')}"`).join(",")).join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = "divu-audit-log.csv"; link.click(); URL.revokeObjectURL(url); };
  return <div className="space-y-4 pb-6"><header className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-2xl font-bold tracking-tight">Audit Log Center</h1><p className="mt-1 text-xs text-muted-foreground">Complete tamper-evident record of all user actions, system events, and security incidents</p></div><button onClick={exportCsv} className="inline-flex h-9 items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 text-xs font-semibold text-white hover:bg-blue-700"><Download className="size-3.5" />Export CSV</button></header><StatsCards />
    <section className="flex flex-col gap-2 rounded-xl border bg-card p-2 lg:flex-row"><div className="flex min-w-0 flex-1 items-center gap-2"><Filter className="size-4 text-muted-foreground"/><label className="flex h-9 min-w-0 flex-1 items-center gap-2 rounded-lg border bg-muted/20 px-3"><Search className="size-3.5 text-muted-foreground"/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search user, action, resource, IP, detail..." className="min-w-0 flex-1 bg-transparent text-[11px] outline-none" /></label></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><Select label="Filter by user" value={user} onChange={setUser}><option>All Users</option>{users.map((item) => <option key={item}>{item}</option>)}</Select><Select label="Filter by action" value={action} onChange={setAction}><option>All Actions</option>{actions.map((item) => <option key={item}>{item}</option>)}</Select><Select label="Filter by resource" value={resource} onChange={setResource}><option>All Resources</option>{resourceOrder.map((item) => <option key={item}>{item}</option>)}</Select><Select label="Filter by status" value={status} onChange={setStatus}><option>All</option>{["Success", "Warning", "Failed", "Blocked"].map((item) => <option key={item}>{item}</option>)}</Select></div><span className="self-center whitespace-nowrap px-2 font-mono text-[9px] text-muted-foreground">{filtered.length} of 30 events</span></section>
    <nav className="flex border-b" aria-label="Audit log views">{([{ id: "timeline", label: "Timeline", icon: List }, { id: "resources", label: "Resource History", icon: History }, { id: "users", label: "User History", icon: UserRound }] as const).map(({ id, label, icon: Icon }) => <button key={id} onClick={() => setTab(id)} className={`flex h-10 items-center gap-2 border-b-2 px-3 text-[11px] font-medium ${tab === id ? "border-primary text-primary" : "border-transparent text-muted-foreground"}`}><Icon className="size-3.5" />{label}</button>)}</nav>
    {tab === "timeline" && <Timeline events={filtered} onSelect={setSelected} />}{tab === "resources" && <ResourceHistory onSelect={setSelected} />}{tab === "users" && <UserHistory onSelect={setSelected} />}{selected && <AuditEventDetailModal event={selected} onClose={() => setSelected(null)} />}
  </div>;
}
