"use client";

import { Download, Filter, RefreshCw, Search } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { apiRequest } from "@/lib/api-client";
import type { AuditRecordDto } from "@/lib/backend-dtos";
import { AuditEventDetailModal, AuditEventRow } from "./audit-event";
import type { AuditEvent } from "./audit-log-data";

function mapRecord(record: AuditRecordDto): AuditEvent {
  const date = new Date(record.loggedAt);
  const resource = record.tableAffected.replaceAll("_", " ").replace(/\b\w/g, (value) => value.toUpperCase());
  return { id:String(record.auditId), user:record.username, role:"Not provided", action:record.action, resource, source:record.tableAffected, detail:record.newValues||record.oldValues||"No change details supplied.", status:"Success", timestamp:Number.isNaN(date.getTime())?record.loggedAt:date.toLocaleString(), relativeTime:Number.isNaN(date.getTime())?"Unknown":date.toLocaleDateString(), ip:"Not provided", site:"Not provided", sessionId:"Not provided" };
}

function Select({value,onChange,children,label}:{value:string;onChange:(value:string)=>void;children:React.ReactNode;label:string}){return <select aria-label={label} value={value} onChange={e=>onChange(e.target.value)} className="h-9 rounded-lg border bg-card px-3 text-[11px] outline-none focus:ring-2 focus:ring-ring">{children}</select>}

export function AuditLogPage(){const[records,setRecords]=useState<AuditEvent[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[query,setQuery]=useState("");const[user,setUser]=useState("All Users");const[action,setAction]=useState("All Actions");const[resource,setResource]=useState("All Resources");const[selected,setSelected]=useState<AuditEvent|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const data=await apiRequest<AuditRecordDto[]>("/api/backend/audit");setRecords(data.map(mapRecord));}catch(cause){setError(cause instanceof Error?cause.message:"Audit events could not be loaded.");}finally{setLoading(false)}},[]);useEffect(()=>{
  // The effect starts the external gateway synchronization on mount.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  void load()
 },[load]);
 const users=useMemo(()=>[...new Set(records.map(event=>event.user))],[records]);const actions=useMemo(()=>[...new Set(records.map(event=>event.action))],[records]);const resources=useMemo(()=>[...new Set(records.map(event=>event.resource))],[records]);
 const filtered=useMemo(()=>{const q=query.toLowerCase().trim();return records.filter(event=>(!q||[event.user,event.action,event.resource,event.detail,event.source].join(" ").toLowerCase().includes(q))&&(user==="All Users"||event.user===user)&&(action==="All Actions"||event.action===action)&&(resource==="All Resources"||event.resource===resource))},[action,query,records,resource,user]);
 const stats=useMemo(()=>({Total:records.length,Success:records.filter(e=>e.status==="Success").length,Warning:0,Failed:0,Blocked:0}),[records]);
 function exportCsv(){const rows=[["Event ID","Timestamp","User","Action","Resource","Details"],...filtered.map(e=>[e.id,e.timestamp,e.user,e.action,e.resource,e.detail])];const csv=rows.map(row=>row.map(cell=>`"${cell.replaceAll('"','""')}"`).join(",")).join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download="divu-audit-current-view.csv";link.click();URL.revokeObjectURL(url)}
 return <div className="space-y-4 pb-6"><header className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2"><h1 className="text-2xl font-bold tracking-tight">Audit Log Center</h1><span className="rounded-full bg-emerald-500/10 px-2 py-1 font-mono text-[8px] uppercase text-emerald-600">Live gateway data</span></div><p className="mt-1 text-xs text-muted-foreground">Backend audit records. Search and filters are applied locally to the latest records returned by the server.</p></div><div className="flex gap-2"><button onClick={()=>void load()} disabled={loading} className="inline-flex h-9 items-center gap-2 rounded-lg border px-3 text-xs font-semibold disabled:opacity-40"><RefreshCw className="size-3.5"/>Refresh</button><button onClick={exportCsv} disabled={!filtered.length} title="Client-side export of the current fetched view" className="inline-flex h-9 items-center gap-2 rounded-lg bg-blue-600 px-4 text-xs font-semibold text-white disabled:opacity-40"><Download className="size-3.5"/>Export current view</button></div></header>
 <div className="grid grid-cols-2 gap-2 lg:grid-cols-5">{(["Total","Success","Warning","Failed","Blocked"] as const).map(key=><div key={key} className="rounded-xl border bg-card p-4"><strong className="text-lg">{stats[key]}</strong><p className="mt-1 text-[10px] text-muted-foreground">{key} events</p></div>)}</div>
 {error&&<div role="alert" className="rounded-xl border border-destructive/30 bg-destructive/10 p-4 text-xs text-destructive">{error}<button onClick={()=>void load()} className="ml-3 underline">Retry</button></div>}
 <section className="flex flex-col gap-2 rounded-xl border bg-card p-2 lg:flex-row"><div className="flex min-w-0 flex-1 items-center gap-2"><Filter className="size-4 text-muted-foreground"/><label className="flex h-9 min-w-0 flex-1 items-center gap-2 rounded-lg border bg-muted/20 px-3"><Search className="size-3.5 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search user, action, resource, detail..." className="min-w-0 flex-1 bg-transparent text-[11px] outline-none"/></label></div><div className="grid grid-cols-1 gap-2 sm:grid-cols-3"><Select label="Filter by user" value={user} onChange={setUser}><option>All Users</option>{users.map(item=><option key={item}>{item}</option>)}</Select><Select label="Filter by action" value={action} onChange={setAction}><option>All Actions</option>{actions.map(item=><option key={item}>{item}</option>)}</Select><Select label="Filter by resource" value={resource} onChange={setResource}><option>All Resources</option>{resources.map(item=><option key={item}>{item}</option>)}</Select></div></section>
 <section className="overflow-hidden rounded-xl border bg-card"><header className="flex justify-between bg-muted/50 px-4 py-3 font-mono text-[9px] uppercase text-muted-foreground"><span>Gateway audit events · newest first</span><span>{filtered.length} results</span></header>{loading?<div role="status" className="m-4 h-40 animate-pulse rounded-lg bg-muted"/>:filtered.length?filtered.map(event=><AuditEventRow key={event.id} event={event} onSelect={setSelected}/>):<p className="p-10 text-center text-sm text-muted-foreground">No audit events match the current view.</p>}</section>{selected&&<AuditEventDetailModal event={selected} onClose={()=>setSelected(null)}/>}</div>}
