export const backendCapabilities = {
  auth: true,
  dashboard: true,
  operations: true,
  products: true,
  sensors: true,
  audit: true,
  aiAlerts: true,
  aiChat: true,
  aiRisk: true,
  aiNotifications: true,
  aiRules: true,
  aiSettings: true,
  aiLiveEvents: true,
  aiDataGeneration: true,
  aiSyntheticTelemetry: true,
  aiProductionSimulation: true,
  users: false,
  roles: false,
  departments: false,
  assets: false,
  governance: false,
  approvals: false,
  notifications: false,
  reports: false,
  financial: false,
  securityOperations: false,
  apiClients: false,
  dataSources: false,
  profile: false,
  settings: false,
} as const;

export type BackendCapability = keyof typeof backendCapabilities;
