export const backendCapabilities = {
  auth: true,
  dashboard: true,
  operations: true,
  products: true,
  sensors: true,
  audit: true,
  aiAlerts: true,
  aiChat: true,
  aiRisk: true,
  aiNotifications: true,
  aiRules: true,
  aiSettings: true,
  aiLiveEvents: true,
  aiDataGeneration: true,
  aiSyntheticTelemetry: true,
  aiProductionSimulation: true,
  users: true,
  roles: true,
  departments: false,
  assets: false,
  governance: true,
  approvals: true,
  notifications: true,
  reports: true,
  financial: true,
  securityOperations: true,
  apiClients: false,
  dataSources: true,
  profile: true,
  settings: true,
} as const;

export type BackendCapability = keyof typeof backendCapabilities;
