import { apiRequest } from "@/lib/api-client";
import { normalizeArrayResponse } from "@/lib/api-normalizers";

export type DataGeneratorScenario = "normal" | "degradation" | "anomaly" | "failure";
export type DataGeneratorStatus = "running" | "paused" | "stopped";
export type DataGenerator = { generatorId:string; name:string; facilityId:number; hallId:number; productionLineId:number; stationIds:number[]; runIds:Record<string,number>; scenario:DataGeneratorScenario; intervalMs:number; durationMinutes:number|null; autoCreateRuns:boolean; allowExistingStations:boolean; status:DataGeneratorStatus; readingsGenerated:number; createdBy:number; createdAt:string; startedAt:string; pausedAt:string|null; stoppedAt:string|null; lastGeneratedAt:string|null; nextEmitAt:string|null; lastError:string|null };
export type CreateDataGeneratorRequest = { name:string; facilityId:number; hallId:number; productionLineId:number; stationIds:number[]; scenario:DataGeneratorScenario; intervalMs:number; durationMinutes?:number; autoCreateRuns:boolean; allowExistingStations:boolean };
export type SyntheticSensorReading = { readingId:number; value:number; readingTs:string; runId:number; sensorId:number; sensorName:string; sensorType:string; stationId:number; source:"ai-generated"; isSynthetic:boolean };
export type SyntheticProductionMetric = { metricId:number; generatorId:string; stationId:number; runId:number; producedCount:number; goodCount:number; scrapCount:number; cycleTimeSeconds:number; throughputPerHour:number; generatedAt:string; source:"ai-generated"; isSynthetic:boolean };
export type GeneratorReadingsEvent = { generatorId:string; count:number; sample:Array<{readingId:number;stationId:number;sensorType:string;value:number}> };
export type GeneratorControlResponse = DataGenerator;
export type GeneratedDeletionRequest = { generatorId?:string; generationBatchId?:string; facilityId?:number; fromUtc?:string; toUtc?:string; deleteGenerator:boolean; deleteGenerationBatch:boolean; reason:string };
export type GeneratedDeletionApproval = { requestId:string; status:"pending" };
type RawGenerator={generator_id:string;name:string;facility_id:number;hall_id:number;production_line_id:number;station_ids:number[];run_ids:Record<string,number>;scenario:DataGeneratorScenario;interval_ms:number;duration_minutes:number|null;auto_create_runs:boolean;allow_existing_stations:boolean;status:DataGeneratorStatus;readings_generated:number;created_by:number;created_at:string;started_at:string;paused_at:string|null;stopped_at:string|null;last_generated_at:string|null;next_emit_at:string|null;last_error:string|null};
type RawReading={reading_id:number;value:number;reading_ts:string;run_id:number;sensor_id:number;sensor_name:string;sensor_type:string;station_id:number;source:string;is_synthetic:boolean};
type RawMetric={metric_id:number;generator_id:string;station_id:number;run_id:number;produced_count:number;good_count:number;scrap_count:number;cycle_time_seconds:number;throughput_per_hour:number;generated_at:string;source:string;is_synthetic:boolean};
const generator=(x:RawGenerator):DataGenerator=>({generatorId:x.generator_id,name:x.name,facilityId:x.facility_id,hallId:x.hall_id,productionLineId:x.production_line_id,stationIds:x.station_ids,runIds:x.run_ids,scenario:x.scenario,intervalMs:x.interval_ms,durationMinutes:x.duration_minutes,autoCreateRuns:x.auto_create_runs,allowExistingStations:x.allow_existing_stations,status:x.status,readingsGenerated:x.readings_generated,createdBy:x.created_by,createdAt:x.created_at,startedAt:x.started_at,pausedAt:x.paused_at,stoppedAt:x.stopped_at,lastGeneratedAt:x.last_generated_at,nextEmitAt:x.next_emit_at,lastError:x.last_error});
export const dataGeneratorsApi={list:async()=>normalizeArrayResponse<RawGenerator>(await apiRequest<unknown>("/api/backend/ai/data-generators"),["generators","items","data"],"data generators").map(generator),create:async(x:CreateDataGeneratorRequest)=>generator(await apiRequest<RawGenerator>("/api/backend/ai/data-generators",{method:"POST",body:JSON.stringify(x)})),control:async(id:string,action:"pause"|"resume"|"stop")=>generator(await apiRequest<RawGenerator>(`/api/backend/ai/data-generators/${id}/${action}`,{method:"POST",body:"{}"})),requestGeneratorDeletion:async(id:string,reason:string)=>apiRequest<GeneratedDeletionApproval>(`/api/backend/ai/data-generators/${id}`,{method:"DELETE",body:JSON.stringify({reason})}),requestGeneratorDataDeletion:async(id:string,reason:string)=>apiRequest<GeneratedDeletionApproval>(`/api/backend/ai/data-generators/${id}/data`,{method:"DELETE",body:JSON.stringify({reason})}),requestBatchDeletion:async(id:string,reason:string)=>apiRequest<GeneratedDeletionApproval>(`/api/backend/ai/generation-batches/${id}`,{method:"DELETE",body:JSON.stringify({reason})}),requestScopedDeletion:async(request:GeneratedDeletionRequest)=>apiRequest<GeneratedDeletionApproval>("/api/backend/ai/generated-data/deletion-requests",{method:"POST",body:JSON.stringify(request)}),readings:async(id:string,limit=200)=>normalizeArrayResponse<RawReading>(await apiRequest<unknown>(`/api/backend/ai/data-generators/${id}/readings?limit=${limit}`),["readings","items","data"],"generator readings").map(x=>({readingId:x.reading_id,value:x.value,readingTs:x.reading_ts,runId:x.run_id,sensorId:x.sensor_id,sensorName:x.sensor_name,sensorType:x.sensor_type,stationId:x.station_id,source:"ai-generated" as const,isSynthetic:x.is_synthetic})),metrics:async(id:string,limit=200)=>normalizeArrayResponse<RawMetric>(await apiRequest<unknown>(`/api/backend/ai/data-generators/${id}/metrics?limit=${limit}`),["metrics","items","data"],"generator metrics").map(x=>({metricId:x.metric_id,generatorId:x.generator_id,stationId:x.station_id,runId:x.run_id,producedCount:x.produced_count,goodCount:x.good_count,scrapCount:x.scrap_count,cycleTimeSeconds:x.cycle_time_seconds,throughputPerHour:x.throughput_per_hour,generatedAt:x.generated_at,source:"ai-generated" as const,isSynthetic:x.is_synthetic}))};
