"use client";

import { useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, DollarSign, Search } from "lucide-react";
import { DowntimeSeverityBadge, DowntimeStatusBadge } from "./downtime-badges";
import type { DowntimeEvent, DowntimeEventStatus, DowntimeSeverity } from "./downtime-data";

function duration(minutes: number) { return `${Math.floor(minutes / 60) ? `${Math.floor(minutes / 60)}h ` : ""}${minutes % 60}m`; }
export function ActiveEventsTable({ events }: { events: DowntimeEvent[] }) {
  const [site, setSite] = useState("All Sites"); const [status, setStatus] = useState<"All" | DowntimeEventStatus>("All"); const [severity, setSeverity] = useState<"All" | DowntimeSeverity>("All"); const [query, setQuery] = useState("");
  const sites = [...new Set(events.map((event) => event.location.siteName))];
  const filtered = useMemo(() => events.filter((event) => { const text = `${event.factorName} ${event.location.assetName} ${event.location.lineName}`.toLowerCase(); return (!query || text.includes(query.toLowerCase())) && (site === "All Sites" || event.location.siteName === site) && (status === "All" || event.status === status) && (severity === "All" || event.severity === severity); }), [events, query, severity, site, status]);
  const active = events.filter((event) => event.status === "Active" || event.status === "Escalated").length; const investigating = events.filter((event) => event.status === "Investigating").length; const resolved = events.filter((event) => event.status === "Resolved").length; const cost = events.reduce((sum, event) => sum + event.estimatedCost, 0);
  return <div className="space-y-4"><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[{ label: "Active / Escalated", value: active, icon: AlertTriangle, style: "bg-[var(--dv-badge-cr-bg)] text-[var(--dv-badge-cr-text)]" }, { label: "Investigating", value: investigating, icon: Search, style: "bg-[var(--dv-badge-wa-bg)] text-[var(--dv-badge-wa-text)]" }, { label: "Resolved Today", value: resolved, icon: CheckCircle2, style: "bg-[var(--dv-badge-ok-bg)] text-[var(--dv-badge-ok-text)]" }, { label: "Estimated Cost Today", value: `$${cost.toLocaleString()}`, icon: DollarSign, style: "bg-card text-foreground" }].map((item) => <article key={item.label} className={`rounded-xl border p-4 shadow-[var(--dv-shadow)] ${item.style}`}><item.icon className="size-4" /><p className="mt-2 text-xl font-bold">{item.value}</p><p className="mt-1 text-[9px] opacity-75">{item.label}</p></article>)}</div>
    <div className="flex flex-col gap-2 rounded-xl border bg-card p-3 sm:flex-row"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search events..." className="h-10 min-w-0 flex-1 rounded-lg border bg-background px-3 text-xs outline-none focus:ring-2 focus:ring-ring/30" />{[[site, setSite, ["All Sites", ...sites]], [severity, setSeverity, ["All", "Critical", "High", "Medium", "Low"]], [status, setStatus, ["All", "Active", "Investigating", "Resolved", "Escalated"]]].map(([value, setter, options], index) => <select key={index} value={value as string} onChange={(event) => (setter as (value: never) => void)(event.target.value as never)} className="h-10 rounded-lg border bg-background px-3 text-xs">{(options as string[]).map((option) => <option key={option}>{option}</option>)}</select>)}</div>
    <div className="overflow-hidden rounded-xl border bg-card shadow-[var(--dv-shadow)]"><div className="overflow-x-auto"><table className="w-full min-w-[1250px] text-left"><thead className="border-b bg-muted/35 font-mono text-[9px] uppercase tracking-[0.1em] text-muted-foreground"><tr>{["Factor", "Location", "Asset", "Start Time", "Duration", "Severity", "Status", "Est. Cost", "Technician", "Resolution"].map((heading) => <th key={heading} className="px-3 py-3">{heading}</th>)}</tr></thead><tbody className="divide-y">{filtered.map((event) => <tr key={event.id} className="text-[10px] hover:bg-muted/25"><td className="px-3 py-3"><p className="font-semibold">{event.factorName}</p><p className="mt-1 font-mono text-[8px] text-muted-foreground">{event.factorCode} · {event.auditRef}</p></td><td className="px-3 py-3"><p>{event.location.siteName}</p><p className="mt-1 text-muted-foreground">{event.location.lineName} · {event.location.stationName}</p></td><td className="px-3 py-3"><p>{event.location.assetName}</p><p className="mt-1 font-mono text-[8px] text-muted-foreground">{event.location.assetId} · {event.location.sensorIds.length} triggers</p></td><td className="px-3 py-3 font-mono">{event.startTime}</td><td className="px-3 py-3 font-mono font-semibold">{duration(event.durationMinutes)}</td><td className="px-3 py-3"><DowntimeSeverityBadge severity={event.severity} /></td><td className="px-3 py-3"><DowntimeStatusBadge status={event.status} /></td><td className="px-3 py-3 font-mono font-semibold">${event.estimatedCost.toLocaleString()}</td><td className="px-3 py-3">{event.technician}</td><td className="max-w-56 px-3 py-3 text-muted-foreground">{event.resolution}</td></tr>)}</tbody></table></div></div>
  </div>;
}
