import type { SensorType } from "@/components/sensors/sensors-data";

export type DowntimeCategory = "Mechanical" | "Electrical" | "Material" | "Operational" | "Planned";
export type DowntimeSeverity = "Critical" | "High" | "Medium" | "Low";
export type DowntimeEventStatus = "Active" | "Investigating" | "Resolved" | "Escalated";

export type DowntimeFactor = {
  id: string; code: string; name: string; category: DowntimeCategory; severity: DowntimeSeverity; description: string;
  occurrences: number; averageDurationMinutes: number; impactScore: number; aiRisk: number;
  appliesTo: { siteIds: string[]; hallIds: string[]; lineIds: string[]; assetTypes: string[]; assetIds: string[]; sensorTypes: SensorType[] };
  costs: { estimatedRepairCost: number; estimatedProductionLoss: number; averageCostPerHour: number; targetResolutionMinutes: number; escalationMinutes: number };
  rootCause: string; recommendedAction: string;
  governance: { policy: string; classification: "Public" | "Internal" | "Confidential" | "Restricted"; retentionPolicy: string };
  ai: { predictiveFailureAnalysis: boolean; rootCauseSuggestions: boolean; maintenanceRecommendations: boolean };
};

export type DowntimeEvent = {
  id: string; factorId: string; factorName: string; factorCode: string; category: DowntimeCategory; severity: DowntimeSeverity; status: DowntimeEventStatus;
  location: { siteId: string; siteName: string; hallId: string; hallName: string; lineId: string; lineName: string; stationId: string; stationName: string; assetId: string; assetName: string; sensorIds: string[] };
  startTime: string; durationMinutes: number; estimatedCost: number; technician: string; resolution: string; auditRef: string;
};

const factor = (value: DowntimeFactor) => value;
export const initialDowntimeFactors: DowntimeFactor[] = [
  factor({ id: "factor-1", code: "MF-101", name: "Mechanical Failure", category: "Mechanical", severity: "Critical", description: "Equipment mechanical component failure requiring repair", occurrences: 23, averageDurationMinutes: 145, impactScore: 9, aiRisk: 88, appliesTo: { siteIds: ["site-detroit", "site-stuttgart"], hallIds: ["det-hall-a"], lineIds: ["det-line-a", "det-line-b"], assetTypes: ["CNC Mill", "Hydraulic Press"], assetIds: ["AST-0011", "AST-0021"], sensorTypes: ["Vibration", "Temperature"] }, costs: { estimatedRepairCost: 4500, estimatedProductionLoss: 18000, averageCostPerHour: 2200, targetResolutionMinutes: 120, escalationMinutes: 30 }, rootCause: "Bearing wear from excessive load and inadequate lubrication schedules.", recommendedAction: "Replace bearings, shorten PM intervals, and maintain vibration monitoring.", governance: { policy: "Operations Log Archive", classification: "Confidential", retentionPolicy: "5 Years" }, ai: { predictiveFailureAnalysis: true, rootCauseSuggestions: true, maintenanceRecommendations: true } }),
  factor({ id: "factor-2", code: "EL-205", name: "Electrical Issue", category: "Electrical", severity: "High", description: "Power supply or electrical control-system malfunction", occurrences: 18, averageDurationMinutes: 95, impactScore: 8, aiRisk: 74, appliesTo: { siteIds: ["site-detroit"], hallIds: ["det-hall-b", "det-hall-c"], lineIds: ["det-line-c", "det-line-e"], assetTypes: ["Welding Robot", "Assembly Robot"], assetIds: ["AST-0012", "AST-0031"], sensorTypes: ["Current", "Energy"] }, costs: { estimatedRepairCost: 2200, estimatedProductionLoss: 9500, averageCostPerHour: 1800, targetResolutionMinutes: 90, escalationMinutes: 20 }, rootCause: "Voltage fluctuations from aging distribution equipment.", recommendedAction: "Inspect transformers and install regulated backup power.", governance: { policy: "Standard Operational Policy", classification: "Internal", retentionPolicy: "3 Years" }, ai: { predictiveFailureAnalysis: true, rootCauseSuggestions: true, maintenanceRecommendations: false } }),
  factor({ id: "factor-3", code: "MS-305", name: "Material Shortage", category: "Material", severity: "High", description: "Insufficient raw materials or supplies to continue production", occurrences: 31, averageDurationMinutes: 180, impactScore: 7, aiRisk: 62, appliesTo: { siteIds: ["site-detroit", "site-stuttgart", "site-osaka"], hallIds: [], lineIds: [], assetTypes: [], assetIds: [], sensorTypes: [] }, costs: { estimatedRepairCost: 500, estimatedProductionLoss: 22000, averageCostPerHour: 3200, targetResolutionMinutes: 240, escalationMinutes: 60 }, rootCause: "Supply delays and insufficient safety stock.", recommendedAction: "Increase critical-material safety stock and diversify suppliers.", governance: { policy: "Financial Records Compliance", classification: "Internal", retentionPolicy: "7 Years" }, ai: { predictiveFailureAnalysis: false, rootCauseSuggestions: true, maintenanceRecommendations: false } }),
  factor({ id: "factor-4", code: "OP-410", name: "Operator Error", category: "Operational", severity: "Medium", description: "Human error requiring corrective action or equipment reset", occurrences: 42, averageDurationMinutes: 45, impactScore: 5, aiRisk: 41, appliesTo: { siteIds: ["site-detroit", "site-stuttgart"], hallIds: [], lineIds: [], assetTypes: [], assetIds: [], sensorTypes: [] }, costs: { estimatedRepairCost: 200, estimatedProductionLoss: 3200, averageCostPerHour: 950, targetResolutionMinutes: 45, escalationMinutes: 15 }, rootCause: "Inconsistent SOP training and unclear operator guidance.", recommendedAction: "Require SOP recertification and improve HMI guidance.", governance: { policy: "Standard Operational Policy", classification: "Internal", retentionPolicy: "2 Years" }, ai: { predictiveFailureAnalysis: false, rootCauseSuggestions: false, maintenanceRecommendations: false } }),
  factor({ id: "factor-5", code: "PM-500", name: "Preventive Maintenance", category: "Planned", severity: "Low", description: "Scheduled maintenance to prevent equipment failures", occurrences: 15, averageDurationMinutes: 120, impactScore: 3, aiRisk: 15, appliesTo: { siteIds: ["site-detroit", "site-stuttgart", "site-osaka"], hallIds: [], lineIds: [], assetTypes: ["CNC Mill", "Hydraulic Press", "Stamping Press"], assetIds: [], sensorTypes: [] }, costs: { estimatedRepairCost: 1200, estimatedProductionLoss: 8000, averageCostPerHour: 1100, targetResolutionMinutes: 120, escalationMinutes: 0 }, rootCause: "Scheduled according to OEM requirements.", recommendedAction: "Continue schedule and use predictive evidence to optimize intervals.", governance: { policy: "Operations Log Archive", classification: "Internal", retentionPolicy: "5 Years" }, ai: { predictiveFailureAnalysis: true, rootCauseSuggestions: false, maintenanceRecommendations: true } }),
  factor({ id: "factor-6", code: "MF-102", name: "Hydraulic Leak", category: "Mechanical", severity: "Critical", description: "Hydraulic system fluid leak requiring immediate repair", occurrences: 8, averageDurationMinutes: 210, impactScore: 9, aiRisk: 92, appliesTo: { siteIds: ["site-detroit", "site-stuttgart"], hallIds: ["det-hall-b", "stu-hall-1"], lineIds: ["det-line-c", "stu-line-1"], assetTypes: ["Hydraulic Press", "Stamping Press"], assetIds: ["AST-0021", "AST-0041"], sensorTypes: ["Pressure", "Temperature"] }, costs: { estimatedRepairCost: 6800, estimatedProductionLoss: 28000, averageCostPerHour: 3500, targetResolutionMinutes: 180, escalationMinutes: 20 }, rootCause: "Seal degradation under high-cycle pressure fatigue.", recommendedAction: "Replace seals on the PM cycle and improve fluid temperature stability.", governance: { policy: "Operations Log Archive", classification: "Confidential", retentionPolicy: "5 Years" }, ai: { predictiveFailureAnalysis: true, rootCauseSuggestions: true, maintenanceRecommendations: true } }),
];

const detA = { siteId: "site-detroit", siteName: "Detroit Assembly Plant", hallId: "det-hall-a", hallName: "Hall A — Body Shop", lineId: "det-line-a", lineName: "Line A", stationId: "det-line-a-station-1", stationName: "Station 1" };
export const downtimeEvents: DowntimeEvent[] = [
  { id: "event-1", factorId: "factor-1", factorName: "Mechanical Failure", factorCode: "MF-101", category: "Mechanical", severity: "Critical", status: "Active", location: { ...detA, assetId: "AST-0011", assetName: "CNC Milling Machine #1", sensorIds: ["SNS-1001", "SNS-3001"] }, startTime: "2026-07-13 07:22", durationMinutes: 83, estimatedCost: 3200, technician: "Carlos Rivera", resolution: "Parts ordered — ETA 2h", auditRef: "AUD-DT-8401" },
  { id: "event-2", factorId: "factor-6", factorName: "Hydraulic Leak", factorCode: "MF-102", category: "Mechanical", severity: "Critical", status: "Escalated", location: { siteId: "site-detroit", siteName: "Detroit Assembly Plant", hallId: "det-hall-b", hallName: "Hall B — Paint Shop", lineId: "det-line-c", lineName: "Line C", stationId: "det-line-c-station-1", stationName: "Station 1", assetId: "AST-0021", assetName: "Hydraulic Press #7", sensorIds: ["SNS-2001"] }, startTime: "2026-07-13 05:48", durationMinutes: 142, estimatedCost: 7400, technician: "Mike Davis", resolution: "Escalated to Plant Manager", auditRef: "AUD-DT-8402" },
  { id: "event-3", factorId: "factor-2", factorName: "Electrical Issue", factorCode: "EL-205", category: "Electrical", severity: "High", status: "Investigating", location: { siteId: "site-detroit", siteName: "Detroit Assembly Plant", hallId: "det-hall-c", hallName: "Hall C — General Assembly", lineId: "det-line-e", lineName: "Line E", stationId: "det-line-e-station-2", stationName: "Station 2", assetId: "AST-0031", assetName: "Assembly Station Alpha", sensorIds: ["SNS-4001"] }, startTime: "2026-07-13 08:15", durationMinutes: 35, estimatedCost: 1100, technician: "Sarah Johnson", resolution: "Control board under diagnostics", auditRef: "AUD-DT-8403" },
  { id: "event-4", factorId: "factor-4", factorName: "Operator Error", factorCode: "OP-410", category: "Operational", severity: "Medium", status: "Resolved", location: { siteId: "site-stuttgart", siteName: "Stuttgart Manufacturing Hub", hallId: "stu-hall-2", hallName: "Hall 2 — Welding", lineId: "stu-line-3", lineName: "Line 3", stationId: "stu-line-3-station-4", stationName: "Station 4", assetId: "AST-0061", assetName: "Packaging Unit #2", sensorIds: [] }, startTime: "2026-07-13 09:02", durationMinutes: 18, estimatedCost: 320, technician: "Anna Müller", resolution: "Reset complete, production resumed", auditRef: "AUD-DT-8404" },
  { id: "event-5", factorId: "factor-1", factorName: "Mechanical Failure", factorCode: "MF-101", category: "Mechanical", severity: "Critical", status: "Resolved", location: { siteId: "site-stuttgart", siteName: "Stuttgart Manufacturing Hub", hallId: "stu-hall-1", hallName: "Hall 1 — Stamping", lineId: "stu-line-1", lineName: "Line 1", stationId: "stu-line-1-station-1", stationName: "Station 1", assetId: "AST-0041", assetName: "Stamping Press Mk-II", sensorIds: ["SNS-6001"] }, startTime: "2026-07-13 06:30", durationMinutes: 210, estimatedCost: 5100, technician: "Anna Müller", resolution: "Bearing replaced, QC passed", auditRef: "AUD-DT-8405" },
  { id: "event-6", factorId: "factor-3", factorName: "Material Shortage", factorCode: "MS-305", category: "Material", severity: "High", status: "Active", location: { siteId: "site-osaka", siteName: "Osaka Production Site", hallId: "osa-hall-a", hallName: "Hall A — Precision Machining", lineId: "osa-line-alpha", lineName: "Line α", stationId: "osa-line-alpha-station-1", stationName: "Station 1", assetId: "AST-0051", assetName: "CNC Lathe #4", sensorIds: ["SNS-6002"] }, startTime: "2026-07-13 04:00", durationMinutes: 310, estimatedCost: 9800, technician: "Hiro Tanaka", resolution: "Emergency supply order placed", auditRef: "AUD-DT-8406" },
  { id: "event-7", factorId: "factor-5", factorName: "Preventive Maintenance", factorCode: "PM-500", category: "Planned", severity: "Low", status: "Resolved", location: { siteId: "site-detroit", siteName: "Detroit Assembly Plant", hallId: "det-hall-c", hallName: "Hall C — General Assembly", lineId: "det-line-f", lineName: "Line F", stationId: "det-line-f-station-1", stationName: "Station 1", assetId: "AST-0032", assetName: "Paint Booth Controller", sensorIds: ["SNS-5002"] }, startTime: "2026-07-13 06:00", durationMinutes: 90, estimatedCost: 1200, technician: "Elena Petrov", resolution: "PM complete — calibration verified", auditRef: "AUD-DT-8407" },
];

export const monthlyDowntime = [{ label: "Jan", hours: 142, cost: 48000, mttr: 2.4, mtbf: 38 }, { label: "Feb", hours: 118, cost: 39000, mttr: 2.1, mtbf: 42 }, { label: "Mar", hours: 195, cost: 67000, mttr: 3.1, mtbf: 29 }, { label: "Apr", hours: 87, cost: 28000, mttr: 1.8, mtbf: 51 }, { label: "May", hours: 163, cost: 54000, mttr: 2.8, mtbf: 35 }, { label: "Jun", hours: 201, cost: 72000, mttr: 3.4, mtbf: 27 }, { label: "Jul", hours: 94, cost: 31000, mttr: 2, mtbf: 48 }];
export const downtimeByCategory = [{ label: "Mechanical", value: 312 }, { label: "Electrical", value: 148 }, { label: "Material", value: 241 }, { label: "Operational", value: 82 }, { label: "Planned", value: 104 }];
export const downtimeBySite = [{ label: "Detroit", value: 420 }, { label: "Stuttgart", value: 190 }, { label: "Osaka", value: 142 }];
export const downtimeByAssetType = [{ label: "Hydraulic Press", value: 142 }, { label: "CNC Mill", value: 98 }, { label: "Stamping Press", value: 87 }, { label: "Welding Robot", value: 62 }, { label: "Conveyor", value: 48 }];
export const factorCategories: DowntimeCategory[] = ["Mechanical", "Electrical", "Material", "Operational", "Planned"];
export const factorSeverities: DowntimeSeverity[] = ["Critical", "High", "Medium", "Low"];
export const downtimePolicies = ["Operations Log Archive", "Standard Operational Policy", "Sensor Telemetry Retention", "Financial Records Compliance"];
