import { AlertTriangle, Boxes, Building2, Clock3, DollarSign, Edit3, Radio, Trash2, TrendingUp } from "lucide-react";
import { DowntimeSeverityBadge } from "./downtime-badges";
import type { DowntimeFactor } from "./downtime-data";

function duration(minutes: number) { const hours = Math.floor(minutes / 60); const remainder = minutes % 60; return `${hours ? `${hours}h ` : ""}${remainder}m`; }
export function DowntimeFactorCard({ factor, onEdit, onDelete }: { factor: DowntimeFactor; onEdit: (factor: DowntimeFactor) => void; onDelete: (factor: DowntimeFactor) => void }) {
  return <article className="rounded-xl border bg-card p-4 shadow-[var(--dv-shadow)]"><div className="flex items-start gap-3"><div className="grid size-9 shrink-0 place-items-center rounded-lg bg-[var(--dv-badge-cr-bg)] text-[var(--dv-badge-cr-text)]"><AlertTriangle className="size-4" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-sm font-bold">{factor.name}</h2><span className="rounded bg-muted px-2 py-1 font-mono text-[8px] text-muted-foreground">{factor.code}</span></div><div className="mt-1.5 flex flex-wrap gap-2"><span className="rounded bg-primary/10 px-2 py-1 font-mono text-[8px] text-primary">{factor.category}</span><DowntimeSeverityBadge severity={factor.severity} /></div><p className="mt-2 text-xs leading-5 text-muted-foreground">{factor.description}</p></div><div className="flex gap-1"><button type="button" onClick={() => onEdit(factor)} aria-label={`Edit ${factor.name}`} className="grid size-8 place-items-center rounded-md border text-muted-foreground hover:text-primary"><Edit3 className="size-3.5" /></button><button type="button" onClick={() => onDelete(factor)} aria-label={`Delete ${factor.name}`} className="grid size-8 place-items-center rounded-md border text-muted-foreground hover:bg-destructive/10 hover:text-destructive"><Trash2 className="size-3.5" /></button></div></div>
    <div className="mt-4 grid grid-cols-3 gap-3 border-t pt-3"><div><p className="text-[9px] text-muted-foreground">Occurrences</p><p className="mt-1 font-mono text-sm font-bold">{factor.occurrences}</p></div><div><p className="text-[9px] text-muted-foreground">Avg Duration</p><p className="mt-1 flex items-center gap-1 font-mono text-xs"><Clock3 className="size-3" />{duration(factor.averageDurationMinutes)}</p></div><div><p className="text-[9px] text-muted-foreground">Impact</p><p className="mt-1 flex items-center gap-1 font-mono text-xs font-bold text-[var(--dv-badge-cr-text)]"><TrendingUp className="size-3" />{factor.impactScore}/10</p></div></div>
    <div className="mt-3 grid grid-cols-2 gap-3 border-t pt-3 sm:grid-cols-4"><div><p className="text-[8px] text-muted-foreground">Assets Linked</p><p className="mt-1 flex items-center gap-1 font-mono text-[10px]"><Boxes className="size-3" />{factor.appliesTo.assetIds.length}</p></div><div><p className="text-[8px] text-muted-foreground">Sites Affected</p><p className="mt-1 flex items-center gap-1 font-mono text-[10px]"><Building2 className="size-3" />{factor.appliesTo.siteIds.length}</p></div><div><p className="text-[8px] text-muted-foreground">Avg Repair</p><p className="mt-1 flex items-center gap-1 font-mono text-[10px]"><DollarSign className="size-3" />{factor.costs.estimatedRepairCost.toLocaleString()}</p></div><div><p className="text-[8px] text-muted-foreground">AI Risk</p><p className="mt-1 flex items-center gap-1 font-mono text-[10px] text-[var(--dv-badge-cr-text)]"><Radio className="size-3" />{factor.aiRisk}%</p></div></div>
    {!!factor.appliesTo.sensorTypes.length && <div className="mt-3 flex flex-wrap gap-1.5">{factor.appliesTo.sensorTypes.map((type) => <span key={type} className="rounded border border-primary/20 bg-primary/5 px-2 py-1 font-mono text-[8px] text-primary">{type}</span>)}</div>}
  </article>;
}
