export type ClientStatus = "Active" | "Expiring Soon" | "Disabled" | "Revoked";
export type ClientRisk = "Low" | "Medium" | "High" | "Critical";
export type Environment = "Production" | "Staging" | "Development";

export type ApiClient = {
  id: string; name: string; owner: string; environment: Environment; description: string;
  token: string; tokenPrefix: string; tokenSuffix: string; status: ClientStatus; risk: ClientRisk;
  expires: string; expiryDate: string; requests: string; failed: number; unauthorized: number;
  lastUsed: string; created: string; lastRotation: string; secretAge: string; tls: string;
  authType: string; rateLimit: string; averageResponse: string; whitelist: string[];
  scopes: string[]; modules: string[];
};

export const allScopes = ["Read All", "Write All", "Admin", "Read Sensors", "Read Assets", "Write Sensors", "Read Financial", "Read Audit"];

export const apiClients: ApiClient[] = [
  { id: "api-01", name: "SCADA Integration", owner: "Carlos Rivera", environment: "Production", description: "Reads sensor data for SCADA system visualization", token: "sk_live_••••••••••••4f2a", tokenPrefix: "sk_live_", tokenSuffix: "4f2a", status: "Active", risk: "Low", expires: "185d", expiryDate: "Jan 14, 2027", requests: "284.3K", failed: 42, unauthorized: 0, lastUsed: "2h ago", created: "Jan 14, 2026", lastRotation: "30d ago", secretAge: "30 days", tls: "TLS 1.3", authType: "Bearer Token", rateLimit: "1,200 req/min", averageResponse: "124ms", whitelist: ["10.10.1.50", "10.10.1.51"], scopes: ["Read Sensors", "Read Assets", "Read Audit"], modules: ["Sensors", "Assets", "Audit"] },
  { id: "api-02", name: "ERP Connector", owner: "Admin User", environment: "Production", description: "Synchronizes production and financial records with ERP", token: "sk_live_••••••••••••8c1e", tokenPrefix: "sk_live_", tokenSuffix: "8c1e", status: "Expiring Soon", risk: "Medium", expires: "Today", expiryDate: "Jul 13, 2026", requests: "54.1K", failed: 128, unauthorized: 3, lastUsed: "1h ago", created: "Jul 13, 2025", lastRotation: "89d ago", secretAge: "89 days", tls: "TLS 1.3", authType: "Bearer Token", rateLimit: "600 req/min", averageResponse: "218ms", whitelist: ["10.10.5.24"], scopes: ["Read All", "Read Financial"], modules: ["Operations", "Financial"] },
  { id: "api-03", name: "BI Dashboard Feed", owner: "Elena Vasquez", environment: "Production", description: "Feeds approved operational metrics into business intelligence dashboards", token: "sk_live_••••••••••••2d7b", tokenPrefix: "sk_live_", tokenSuffix: "2d7b", status: "Active", risk: "Low", expires: "275d", expiryDate: "Apr 14, 2027", requests: "18.6K", failed: 7, unauthorized: 0, lastUsed: "5h ago", created: "Apr 14, 2026", lastRotation: "14d ago", secretAge: "14 days", tls: "TLS 1.3", authType: "Bearer Token", rateLimit: "300 req/min", averageResponse: "98ms", whitelist: ["10.15.2.19"], scopes: ["Read Assets", "Read Financial"], modules: ["Assets", "Financial", "Analytics"] },
  { id: "api-04", name: "Mobile App — Operators", owner: "Anna Müller", environment: "Production", description: "Operator mobile access to production assets and sensors", token: "sk_live_••••••••••••9b3c", tokenPrefix: "sk_live_", tokenSuffix: "9b3c", status: "Active", risk: "High", expires: "305d", expiryDate: "May 14, 2027", requests: "92.5K", failed: 210, unauthorized: 14, lastUsed: "39m ago", created: "May 14, 2026", lastRotation: "45d ago", secretAge: "45 days", tls: "TLS 1.3", authType: "Bearer Token", rateLimit: "500 req/min", averageResponse: "176ms", whitelist: [], scopes: ["Read Sensors", "Read Assets", "Write Sensors"], modules: ["Sensors", "Assets"] },
  { id: "api-05", name: "Compliance Exporter", owner: "James Okafor", environment: "Staging", description: "Exports governance evidence for compliance reviews", token: "sk_stg_••••••••••••5e6f", tokenPrefix: "sk_stg_", tokenSuffix: "5e6f", status: "Active", risk: "Low", expires: "60d", expiryDate: "Sep 11, 2026", requests: "4.8K", failed: 2, unauthorized: 0, lastUsed: "Yesterday", created: "Mar 11, 2026", lastRotation: "7d ago", secretAge: "7 days", tls: "TLS 1.3", authType: "Bearer Token", rateLimit: "120 req/min", averageResponse: "245ms", whitelist: ["10.30.8.11"], scopes: ["Read Audit", "Read Assets"], modules: ["Audit", "Governance"] },
  { id: "api-06", name: "Dev Sandbox Client", owner: "Admin User", environment: "Development", description: "Development client for integration testing", token: "sk_dev_••••••••••••1a4d", tokenPrefix: "sk_dev_", tokenSuffix: "1a4d", status: "Active", risk: "Low", expires: "16d", expiryDate: "Jul 29, 2026", requests: "1.2K", failed: 88, unauthorized: 0, lastUsed: "3h ago", created: "Jun 29, 2026", lastRotation: "14d ago", secretAge: "14 days", tls: "TLS 1.3", authType: "Bearer Token", rateLimit: "100 req/min", averageResponse: "84ms", whitelist: [], scopes: ["Read All", "Write Sensors"], modules: ["Development Sandbox"] },
  { id: "api-07", name: "Legacy MQTT Bridge", owner: "John Smith", environment: "Production", description: "Legacy MQTT integration pending security remediation", token: "sk_live_••••••••••••7c9a", tokenPrefix: "sk_live_", tokenSuffix: "7c9a", status: "Disabled", risk: "High", expires: "Expired 30d ago", expiryDate: "Jun 13, 2026", requests: "0", failed: 0, unauthorized: 0, lastUsed: "45d ago", created: "Jun 13, 2024", lastRotation: "390d ago", secretAge: "390 days", tls: "TLS 1.1", authType: "Bearer Token", rateLimit: "100 req/min", averageResponse: "—", whitelist: ["10.12.0.41"], scopes: ["Read Sensors"], modules: ["Sensors"] },
  { id: "api-08", name: "Security Scan Bot", owner: "Unknown", environment: "Production", description: "Revoked automation client associated with abusive traffic", token: "sk_live_••••••••••••8x11", tokenPrefix: "sk_live_", tokenSuffix: "8x11", status: "Revoked", risk: "Critical", expires: "Never", expiryDate: "Never", requests: "8.8K", failed: 3200, unauthorized: 1840, lastUsed: "5d ago", created: "Feb 2, 2026", lastRotation: "Never", secretAge: "162 days", tls: "TLS 1.2", authType: "Bearer Token", rateLimit: "60 req/min", averageResponse: "38ms", whitelist: [], scopes: [], modules: [] },
];

export const alertGroups = [
  { severity: "Critical", alerts: ["Security Scan Bot: 1,840 unauthorized requests detected", "Security Scan Bot: client revoked — access permanently blocked"] },
  { severity: "High", alerts: ["ERP Connector: token expires today", "Mobile App — Operators: 14 unauthorized requests — abnormal activity", "Mobile App — Operators: 210 failed requests — high error rate", "Security Scan Bot: 3,200 failed requests — high error rate"] },
  { severity: "Medium", alerts: ["Legacy MQTT Bridge: deprecated TLS 1.1 — upgrade to TLS 1.3"] },
] as const;

