"use client";

// FEATURE: Generator lifecycle actions are kept distinct from generated-record deletion.
import { useCallback, useEffect, useRef, useState } from "react";
import { Square, Trash2, X } from "lucide-react";
import { ApiError } from "@/lib/api-client";
import { dataGeneratorsApi, type DataGenerator } from "@/lib/data-generators";

type DeleteKind="configuration"|"data";
const confirmationPhrase="DELETE GENERATED DATA";
function message(cause:unknown){if(cause instanceof ApiError){if(cause.status===403)return "You do not have permission to manage generated data for this facility.";if(cause.status===404)return "The selected generator or generation batch no longer exists.";if(cause.status===409)return "A deletion request is already pending or the selected generated data cannot be deleted in its current state.";if(cause.status===400)return "The deletion request is incomplete. Confirm the scope, reason, and required phrase.";if(cause.status===0)return "The request timed out before confirmation. Refresh the inventory before trying again."}return "Generated-data services are temporarily unavailable. No data was deleted."}

function GeneratorDeletionDialog({generator,kind,close,submitted}:{generator:DataGenerator;kind:DeleteKind;close:()=>void;submitted:()=>Promise<void>}){
 const[reason,setReason]=useState("");const[phrase,setPhrase]=useState("");const[pending,setPending]=useState(false);const[error,setError]=useState("");const first=useRef<HTMLTextAreaElement>(null);
 useEffect(()=>{first.current?.focus();const escape=(event:KeyboardEvent)=>event.key==="Escape"&&!pending&&close();window.addEventListener("keydown",escape);return()=>window.removeEventListener("keydown",escape)},[close,pending]);
 async function submit(){if(!reason.trim()||phrase!==confirmationPhrase)return;setPending(true);try{// VALIDATION: Exact phrase is forwarded to the approval-backed backend route.
 const request={reason:reason.trim(),confirmationPhrase} as const;if(kind==="configuration")await dataGeneratorsApi.requestGeneratorDeletion(generator.generatorId,request);else await dataGeneratorsApi.requestGeneratorDataDeletion(generator.generatorId,request);await submitted();close()}catch(cause){setError(message(cause))}finally{setPending(false)}}
 return <div className="fixed inset-0 z-50 grid place-items-center bg-black/65 p-4"><section role="dialog" aria-modal="true" aria-labelledby="generator-delete-title" aria-describedby="generator-delete-description" aria-busy={pending} className="w-full max-w-lg rounded-xl border bg-background shadow-2xl"><header className="flex gap-3 border-b p-5"><div className="flex-1"><h3 id="generator-delete-title" className="font-bold">{kind==="configuration"?"Delete Generator Configuration":"Request Generator Data Deletion"}</h3><p id="generator-delete-description" className="mt-1 text-xs text-muted-foreground">This submits an approval request; it does not claim immediate deletion.</p></div><button onClick={close} disabled={pending} aria-label="Close generator deletion dialog" className="grid size-9 place-items-center rounded-lg border"><X className="size-4"/></button></header><div className="space-y-4 p-5"><dl className="grid grid-cols-2 gap-2 rounded-lg bg-muted/40 p-3 text-xs"><div><dt>Generator</dt><dd className="font-mono">{generator.generatorId}</dd></div><div><dt>Scope</dt><dd>Facility {generator.facilityId} → Hall {generator.hallId} → Line {generator.productionLineId}</dd></div><div><dt>Generated readings</dt><dd>{generator.readingsGenerated}</dd></div><div><dt>Approval</dt><dd>Required</dd></div></dl><p className="rounded-lg border border-emerald-500/30 bg-emerald-500/10 p-3 text-xs">Manual and live records are excluded. Existing facilities, hierarchy, assets, stations, streams, and sensors are preserved.</p><label className="block text-xs">Reason<textarea ref={first} value={reason} onChange={event=>setReason(event.target.value)} className="mt-1 min-h-24 w-full rounded-lg border bg-background p-3"/></label><label className="block text-xs">Type <strong>{confirmationPhrase}</strong><input value={phrase} onChange={event=>setPhrase(event.target.value)} className="mt-1 h-10 w-full rounded-lg border bg-background px-3 font-mono"/></label>{error&&<p role="alert" className="rounded-lg bg-destructive/10 p-3 text-xs text-destructive">{error}</p>}</div><footer className="flex justify-end gap-2 border-t p-4"><button onClick={close} disabled={pending} className="h-10 rounded-lg border px-4 text-xs">Cancel</button><button onClick={()=>void submit()} disabled={pending||!reason.trim()||phrase!==confirmationPhrase} className="h-10 rounded-lg bg-destructive px-4 text-xs font-bold text-destructive-foreground disabled:opacity-40">{pending?"Submitting…":"Submit Deletion Request"}</button></footer></section></div>
}

export function GeneratorManagementActions({canManage}:{canManage:boolean}){
 const[items,setItems]=useState<DataGenerator[]>([]);const[target,setTarget]=useState<{item:DataGenerator;kind:DeleteKind}|null>(null);const[pending,setPending]=useState("");const[error,setError]=useState("");const[success,setSuccess]=useState("");
 const load=useCallback(async()=>{try{setItems(await dataGeneratorsApi.list());setError("")}catch{setError("Generator configurations are temporarily unavailable.")}},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 async function stop(item:DataGenerator){setPending(item.generatorId);try{await dataGeneratorsApi.control(item.generatorId,"stop");setSuccess("Generator stopped. Existing generated records were preserved.");await load()}catch(cause){setError(cause instanceof Error?cause.message:"Generator could not be stopped.")}finally{setPending("")}}
 async function submitted(){setSuccess("Generated-data deletion request submitted for approval.");await load();window.dispatchEvent(new Event("divu-approvals-changed"));window.dispatchEvent(new Event("divu-dashboard-stale"))}
 if(!canManage)return null;
 return <section className="rounded-xl border bg-card p-4"><h3 className="text-sm font-bold">Generator Management</h3><p className="mt-1 text-xs text-muted-foreground">Stopping generation and deletion requests are separate actions.</p>{success&&<p role="status" className="mt-3 rounded-lg bg-emerald-500/10 p-3 text-xs text-emerald-700">{success}</p>}{error&&<p role="alert" className="mt-3 rounded-lg bg-destructive/10 p-3 text-xs text-destructive">{error}</p>}<div className="mt-3 space-y-2">{items.map(item=><article key={item.generatorId} className="rounded-lg border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><strong className="text-xs">{item.name}</strong><p className="font-mono text-xs text-muted-foreground">{item.generatorId} · {item.status}</p></div><div className="flex flex-wrap gap-2">{item.status!=="stopped"&&<button disabled={pending===item.generatorId} onClick={()=>void stop(item)} className="inline-flex items-center gap-1 rounded border px-2 py-1 text-xs"><Square className="size-3"/>Stop Generator</button>}<button onClick={()=>setTarget({item,kind:"configuration"})} className="inline-flex items-center gap-1 rounded border border-destructive/30 px-2 py-1 text-xs text-destructive"><Trash2 className="size-3"/>Delete Generator Configuration</button><button onClick={()=>setTarget({item,kind:"data"})} className="rounded border border-destructive/30 px-2 py-1 text-xs text-destructive">Request Generator Data Deletion</button></div></div></article>)}</div>{target&&<GeneratorDeletionDialog generator={target.item} kind={target.kind} close={()=>setTarget(null)} submitted={submitted}/>}</section>
}
