"use client";

import { useMemo, useState, type FormEvent } from "react";
import { Cpu, X } from "lucide-react";

import { apiRequest } from "@/lib/api-client";
import type { AssetWriteDto, FacilityWorkspace } from "@/lib/backend-dtos";

const field="mt-1 h-10 w-full rounded-lg border bg-background px-3 text-xs outline-none focus:ring-2 focus:ring-ring/30 disabled:opacity-50";

export function CanonicalAssetForm({hierarchy,onClose,onCreated}:{hierarchy:FacilityWorkspace;onClose:()=>void;onCreated:()=>Promise<void>}) {
  const[facilityId,setFacilityId]=useState("");const[hallId,setHallId]=useState("");const[lineId,setLineId]=useState("");const[stationId,setStationId]=useState("");
  const[form,setForm]=useState({assetName:"",machineType:"",manufacturer:"",model:"",serialNumber:"",firmwareVersion:"",installationDate:"",criticality:"medium",status:"active",description:"",aiMonitoringEnabled:true});
  const[pending,setPending]=useState(false);const[error,setError]=useState("");
  const facility=hierarchy.facilities.find(item=>item.facilityId===Number(facilityId));const halls=facility?.halls??[];
  const hall=halls.find(item=>item.hallId===Number(hallId));const lines=hall?.lines??[];
  const line=lines.find(item=>item.productionLineId===Number(lineId));const stations=line?.stations??[];
  const generatedCode=useMemo(()=>stationId?`AST-${stationId}-${form.assetName.trim().replace(/[^a-z0-9]+/gi,"-").replace(/^-|-$/g,"").toUpperCase().slice(0,16)||"NEW"}`:"Generated after station selection",[form.assetName,stationId]);
  function change(key:string,value:string|boolean){setForm(current=>({...current,[key]:value}))}
  async function submit(event:FormEvent){event.preventDefault();if(!stationId)return;setPending(true);setError("");const body:AssetWriteDto={stationId:Number(stationId),assetName:form.assetName.trim(),machineType:form.machineType,manufacturer:form.manufacturer||null,model:form.model||null,serialNumber:form.serialNumber||null,firmwareVersion:form.firmwareVersion||null,installationDate:form.installationDate||null,criticality:form.criticality,status:form.status,description:form.description||null,aiMonitoringEnabled:form.aiMonitoringEnabled,source:"manual",isSynthetic:false};try{await apiRequest("/api/backend/assets",{method:"POST",body:JSON.stringify(body)});await onCreated();onClose()}catch(cause){setError(cause instanceof Error?cause.message:"Asset creation failed.")}finally{setPending(false)}}
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/60 sm:items-center sm:p-5" onMouseDown={event=>event.target===event.currentTarget&&!pending&&onClose()}><section role="dialog" aria-modal="true" aria-labelledby="create-asset-title" className="flex max-h-[95vh] w-full max-w-3xl flex-col overflow-hidden rounded-t-2xl border bg-background shadow-2xl sm:rounded-2xl"><header className="flex items-start gap-3 border-b p-5"><Cpu className="mt-1 size-5 text-primary"/><div className="flex-1"><h2 id="create-asset-title" className="font-bold">Create Asset</h2><p className="mt-1 font-mono text-[9px] text-muted-foreground">Asset code: {generatedCode}</p></div><button disabled={pending} onClick={onClose} aria-label="Close Create Asset dialog" className="grid size-9 place-items-center rounded-lg border"><X className="size-4"/></button></header><form id="canonical-asset-form" onSubmit={submit} className="min-h-0 flex-1 space-y-5 overflow-y-auto p-5">
    <fieldset><legend className="mb-3 font-mono text-[10px] font-semibold uppercase text-primary">Factory hierarchy</legend><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs">Location<select required value={facilityId} onChange={event=>{setFacilityId(event.target.value);setHallId("");setLineId("");setStationId("")}} className={field}><option value="">Select location</option>{hierarchy.facilities.map(item=><option key={item.facilityId} value={item.facilityId}>{item.name}</option>)}</select></label><label className="text-xs">Hall<select required disabled={!facility} value={hallId} onChange={event=>{setHallId(event.target.value);setLineId("");setStationId("")}} className={field}><option value="">Select hall</option>{halls.map(item=><option key={item.hallId} value={item.hallId}>{item.name}</option>)}</select></label><label className="text-xs">Line<select required disabled={!hall} value={lineId} onChange={event=>{setLineId(event.target.value);setStationId("")}} className={field}><option value="">Select line</option>{lines.map(item=><option key={item.productionLineId} value={item.productionLineId}>{item.name}</option>)}</select></label><label className="text-xs">Station<select required disabled={!line} value={stationId} onChange={event=>setStationId(event.target.value)} className={field}><option value="">Select station</option>{stations.map(item=><option key={item.stationId} value={item.stationId}>{item.name}</option>)}</select></label></div></fieldset>
    <fieldset><legend className="mb-3 font-mono text-[10px] font-semibold uppercase text-primary">Asset metadata</legend><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs">Asset name<input required value={form.assetName} onChange={event=>change("assetName",event.target.value)} className={field}/></label><label className="text-xs">Machine type<input required value={form.machineType} onChange={event=>change("machineType",event.target.value)} className={field}/></label>{[["manufacturer","Manufacturer"],["model","Model"],["serialNumber","Serial number"],["firmwareVersion","Firmware version"]].map(([key,label])=><label key={key} className="text-xs">{label}<input value={String(form[key as keyof typeof form])} onChange={event=>change(key,event.target.value)} className={field}/></label>)}<label className="text-xs">Installation date<input type="date" value={form.installationDate} onChange={event=>change("installationDate",event.target.value)} className={field}/></label><label className="text-xs">Criticality<select value={form.criticality} onChange={event=>change("criticality",event.target.value)} className={field}>{["low","medium","high","critical"].map(item=><option key={item}>{item}</option>)}</select></label><label className="text-xs">Status<select value={form.status} onChange={event=>change("status",event.target.value)} className={field}>{["active","inactive","maintenance","retired"].map(item=><option key={item}>{item}</option>)}</select></label><label className="text-xs sm:col-span-2">Description<textarea value={form.description} onChange={event=>change("description",event.target.value)} className="mt-1 min-h-20 w-full rounded-lg border bg-background p-3 text-xs"/></label><label className="flex items-center gap-2 text-xs sm:col-span-2"><input type="checkbox" checked={form.aiMonitoringEnabled} onChange={event=>change("aiMonitoringEnabled",event.target.checked)}/>Enable Olive AI monitoring</label></div></fieldset>{error&&<p role="alert" className="rounded-lg border border-destructive/30 bg-destructive/10 p-3 text-xs text-destructive">{error}</p>}</form><footer className="flex justify-end gap-2 border-t p-4"><button type="button" disabled={pending} onClick={onClose} className="h-10 rounded-lg border px-4 text-xs">Cancel</button><button form="canonical-asset-form" disabled={pending||!stationId||!form.assetName.trim()||!form.machineType.trim()} className="h-10 rounded-lg bg-primary px-5 text-xs font-semibold text-primary-foreground disabled:opacity-40">{pending?"Creating…":"Create Asset"}</button></footer></section></div>
}
