"use client";

import { useMemo, useState, type FormEvent, type ReactNode } from "react";
import { Factory, KeyRound, X } from "lucide-react";

import type { AccessLevel, Facility, FacilityStatus, SiteAccess } from "./facilities-data";

function ModalFrame({ title, description, icon, onClose, children }: { title: string; description: string; icon: ReactNode; onClose: () => void; children: ReactNode }) {
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/65 p-0 backdrop-blur-sm sm:items-center sm:p-5" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section role="dialog" aria-modal="true" aria-labelledby="facility-modal-title" className="max-h-[94vh] w-full overflow-y-auto rounded-t-2xl border bg-background shadow-2xl sm:max-w-3xl sm:rounded-2xl"><header className="sticky top-0 z-10 flex items-start gap-3 border-b bg-background/95 p-5 backdrop-blur"><div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary">{icon}</div><div className="min-w-0 flex-1"><h2 id="facility-modal-title" className="text-lg font-bold">{title}</h2><p className="mt-0.5 text-xs text-muted-foreground">{description}</p></div><button type="button" onClick={onClose} aria-label="Close dialog" className="flex size-9 items-center justify-center rounded-lg border text-muted-foreground hover:text-foreground"><X className="size-4" /></button></header>{children}</section></div>;
}

const inputClass = "h-10 w-full rounded-lg border bg-background px-3 text-sm outline-none transition-shadow focus:ring-2 focus:ring-ring/30";
const labelClass = "space-y-1.5 text-xs font-medium";

export function RegisterSiteModal({ onClose, onSave }: { onClose: () => void; onSave: (facility: Facility) => void }) {
  const [name, setName] = useState("");
  const [code, setCode] = useState("");
  const [city, setCity] = useState("");
  const [country, setCountry] = useState("");
  const [manager, setManager] = useState("");
  const [hallCount, setHallCount] = useState(2);
  const [linesPerHall, setLinesPerHall] = useState(2);
  const [stationsPerLine, setStationsPerLine] = useState(3);
  const [status, setStatus] = useState<FacilityStatus>("Active");

  function submit(event: FormEvent) {
    event.preventDefault();
    const safeCode = code.trim().toUpperCase() || `SITE-${Date.now().toString().slice(-4)}`;
    const halls = Array.from({ length: hallCount }, (_, hallIndex) => ({ id: `${safeCode.toLowerCase()}-hall-${hallIndex + 1}`, name: `Hall ${hallIndex + 1}`, code: `H${hallIndex + 1}`, lines: Array.from({ length: linesPerHall }, (_, lineIndex) => ({ id: `${safeCode.toLowerCase()}-line-${hallIndex + 1}-${lineIndex + 1}`, name: `Production Line ${lineIndex + 1}`, code: `L${hallIndex + 1}${lineIndex + 1}`, oee: 0, availability: 0, performance: 0, quality: 0, outputPerHour: 0, sensorCount: 0, assetCount: 0, downtimeHours: 0, stations: Array.from({ length: stationsPerLine }, (_, stationIndex) => ({ id: `${safeCode.toLowerCase()}-station-${hallIndex + 1}-${lineIndex + 1}-${stationIndex + 1}`, name: `Station ${stationIndex + 1}`, status: "Standby" as const, oee: 0, availability: 0, performance: 0, quality: 0, sensorIds: [], assetIds: [], metricKeys: [], downtimeHours: 0 })) })) }));
    onSave({ id: `facility-${safeCode.toLowerCase()}-${Date.now()}`, name: name.trim(), code: safeCode, facilityType: "Plant", company: "DIVU Industrial", manager: manager.trim(), status, location: { city: city.trim(), region: "", country: country.trim() }, timezone: "Local", shiftPattern: "Three-shift", capacityPerDay: "Pending", sensorCount: 0, assetCount: 0, complianceScore: 100, lastActivity: "Just registered", halls });
  }

  return <ModalFrame title="Register Manufacturing Site" description="Create a facility and its initial operating hierarchy." icon={<Factory className="size-5" />} onClose={onClose}><form onSubmit={submit} className="space-y-6 p-5"><fieldset className="space-y-3"><legend className="font-mono text-[10px] font-semibold uppercase tracking-[0.12em] text-primary">Site identity</legend><div className="grid gap-3 sm:grid-cols-2"><label className={labelClass}>Facility name<input required value={name} onChange={(e) => setName(e.target.value)} className={inputClass} placeholder="North Assembly Plant" /></label><label className={labelClass}>Site code<input value={code} onChange={(e) => setCode(e.target.value)} className={inputClass} placeholder="NAP-01" /></label><label className={labelClass}>City<input required value={city} onChange={(e) => setCity(e.target.value)} className={inputClass} /></label><label className={labelClass}>Country<input required value={country} onChange={(e) => setCountry(e.target.value)} className={inputClass} /></label></div></fieldset><fieldset className="space-y-3"><legend className="font-mono text-[10px] font-semibold uppercase tracking-[0.12em] text-primary">Facility operations</legend><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className={labelClass}>Site manager<input required value={manager} onChange={(e) => setManager(e.target.value)} className={inputClass} /></label><label className={labelClass}>Halls<input type="number" min={1} max={20} value={hallCount} onChange={(e) => setHallCount(Number(e.target.value))} className={inputClass} /></label><label className={labelClass}>Lines per hall<input type="number" min={1} max={20} value={linesPerHall} onChange={(e) => setLinesPerHall(Number(e.target.value))} className={inputClass} /></label><label className={labelClass}>Stations per line<input type="number" min={1} max={50} value={stationsPerLine} onChange={(e) => setStationsPerLine(Number(e.target.value))} className={inputClass} /></label></div></fieldset><fieldset className="space-y-3"><legend className="font-mono text-[10px] font-semibold uppercase tracking-[0.12em] text-primary">Security &amp; compliance</legend><label className={`${labelClass} block max-w-xs`}>Initial operating status<select value={status} onChange={(e) => setStatus(e.target.value as FacilityStatus)} className={inputClass}>{["Active", "Maintenance", "Standby", "Inactive"].map((item) => <option key={item}>{item}</option>)}</select></label></fieldset><footer className="flex flex-col-reverse gap-2 border-t pt-4 sm:flex-row sm:justify-end"><button type="button" onClick={onClose} className="h-10 rounded-lg border px-4 text-sm font-semibold hover:bg-muted">Cancel</button><button type="submit" className="h-10 rounded-lg bg-primary px-4 text-sm font-semibold text-primary-foreground hover:bg-primary/90">Register Site</button></footer></form></ModalFrame>;
}

export function GrantAccessModal({ facilities, onClose, onSave }: { facilities: Facility[]; onClose: () => void; onSave: (access: SiteAccess) => void }) {
  const [userName, setUserName] = useState("");
  const [role, setRole] = useState("");
  const [facilityId, setFacilityId] = useState(facilities[0]?.id ?? "");
  const [hallId, setHallId] = useState("");
  const [lineId, setLineId] = useState("");
  const [stationId, setStationId] = useState("");
  const [accessLevel, setAccessLevel] = useState<AccessLevel>("View");
  const [expiresAt, setExpiresAt] = useState("");
  const facility = facilities.find((item) => item.id === facilityId);
  const halls = facility?.halls ?? [];
  const lines = useMemo(() => halls.find((hall) => hall.id === hallId)?.lines ?? [], [halls, hallId]);
  const stations = useMemo(() => lines.find((line) => line.id === lineId)?.stations ?? [], [lines, lineId]);
  function submit(event: FormEvent) { event.preventDefault(); const hall = halls.find((item) => item.id === hallId); const line = lines.find((item) => item.id === lineId); const station = stations.find((item) => item.id === stationId); onSave({ id: `access-${Date.now()}`, userName: userName.trim(), platformRole: role.trim(), operationalRole: accessLevel === "Admin" ? "Site Administrator" : `${accessLevel} Operator`, facilityId, hall: hall?.name ?? "All Halls", productionLine: line?.name ?? "All Lines", station: station?.name, accessLevel, effectiveDate: new Date().toISOString().slice(0, 10), expiryDate: expiresAt || undefined, status: "Active" }); }
  return <ModalFrame title="Grant Operational Access" description="Assign facility access at site, hall, line, or station scope." icon={<KeyRound className="size-5" />} onClose={onClose}><form onSubmit={submit} className="space-y-5 p-5"><div className="grid gap-3 sm:grid-cols-2"><label className={labelClass}>User name<input required value={userName} onChange={(e) => setUserName(e.target.value)} className={inputClass} /></label><label className={labelClass}>Role<input required value={role} onChange={(e) => setRole(e.target.value)} className={inputClass} placeholder="Line supervisor" /></label><label className={labelClass}>Facility<select required value={facilityId} onChange={(e) => { setFacilityId(e.target.value); setHallId(""); setLineId(""); setStationId(""); }} className={inputClass}>{facilities.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className={labelClass}>Hall (optional)<select value={hallId} onChange={(e) => { setHallId(e.target.value); setLineId(""); setStationId(""); }} className={inputClass}><option value="">All halls</option>{halls.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className={labelClass}>Production line (optional)<select value={lineId} disabled={!hallId} onChange={(e) => { setLineId(e.target.value); setStationId(""); }} className={inputClass}><option value="">All lines</option>{lines.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className={labelClass}>Station (optional)<select value={stationId} disabled={!lineId} onChange={(e) => setStationId(e.target.value)} className={inputClass}><option value="">All stations</option>{stations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className={labelClass}>Access level<select value={accessLevel} onChange={(e) => setAccessLevel(e.target.value as AccessLevel)} className={inputClass}>{["View", "Operate", "Manage", "Admin"].map((item) => <option key={item}>{item}</option>)}</select></label><label className={labelClass}>Expiry date (optional)<input type="date" value={expiresAt} onChange={(e) => setExpiresAt(e.target.value)} className={inputClass} /></label></div><footer className="flex flex-col-reverse gap-2 border-t pt-4 sm:flex-row sm:justify-end"><button type="button" onClick={onClose} className="h-10 rounded-lg border px-4 text-sm font-semibold hover:bg-muted">Cancel</button><button type="submit" className="h-10 rounded-lg bg-primary px-4 text-sm font-semibold text-primary-foreground hover:bg-primary/90">Grant Access</button></footer></form></ModalFrame>;
}
