"use client";

import { useState } from "react";
import { Pencil, X } from "lucide-react";

export type HierarchyEditTarget = { kind:"facility"|"hall"|"line"|"station"; id:number; name:string; code:string; status:string };

const inputClass="mt-1.5 h-10 w-full rounded-lg border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring/30";

export function HierarchyEditModal({target,onClose,onSave,pending,error}:{target:HierarchyEditTarget;onClose:()=>void;onSave:(value:{name:string;code:string|null;status:"active"|"inactive"|"maintenance"|"retired"})=>void;pending:boolean;error:string}) {
  const[name,setName]=useState(target.name);const[code,setCode]=useState(target.code);const[status,setStatus]=useState<"active"|"inactive"|"maintenance"|"retired">((["active","inactive","maintenance","retired"].includes(target.status.toLowerCase())?target.status.toLowerCase():"active") as "active"|"inactive"|"maintenance"|"retired");
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/65 backdrop-blur-sm sm:items-center sm:p-5" onMouseDown={event=>event.target===event.currentTarget&&!pending&&onClose()}><section role="dialog" aria-modal="true" aria-labelledby="hierarchy-edit-title" className="w-full max-w-lg rounded-t-2xl border bg-background shadow-2xl sm:rounded-2xl"><header className="flex items-start gap-3 border-b p-5"><span className="grid size-10 place-items-center rounded-xl bg-primary/10 text-primary"><Pencil className="size-5"/></span><div className="min-w-0 flex-1"><h2 id="hierarchy-edit-title" className="text-lg font-bold">Edit {target.kind}</h2><p className="mt-1 text-xs text-muted-foreground">Update the existing hierarchy record securely.</p></div><button type="button" disabled={pending} onClick={onClose} aria-label="Close hierarchy edit" className="grid size-9 place-items-center rounded-lg border disabled:opacity-40"><X className="size-4"/></button></header><form onSubmit={event=>{event.preventDefault();onSave({name:name.trim(),code:code.trim()||null,status})}} className="space-y-4 p-5"><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-medium">Name<input required maxLength={200} value={name} onChange={event=>setName(event.target.value)} className={inputClass}/></label><label className="text-xs font-medium">{target.kind==="station"?"Station code":"Code"}<input maxLength={50} value={code} onChange={event=>setCode(event.target.value)} className={inputClass}/></label><label className="text-xs font-medium">Status<select value={status} onChange={event=>setStatus(event.target.value as typeof status)} className={inputClass}>{["active","inactive","maintenance","retired"].map(value=><option key={value}>{value}</option>)}</select></label></div>{error&&<p role="alert" className="rounded-lg bg-destructive/10 p-3 text-xs text-destructive">{error}</p>}<footer className="flex justify-end gap-2 border-t pt-4"><button type="button" disabled={pending} onClick={onClose} className="h-10 rounded-lg border px-4 text-xs">Cancel</button><button disabled={pending||!name.trim()} className="h-10 rounded-lg bg-primary px-4 text-xs font-semibold text-primary-foreground disabled:opacity-40">{pending?"Saving…":"Save changes"}</button></footer></form></section></div>
}
