"use client";

import { useState } from "react";
import { Check, RotateCcw, Save, ShieldCheck } from "lucide-react";

const tabs = ["General", "Appearance", "Notifications", "Security", "Data & AI", "Integrations", "Audit & Compliance"] as const;
type Tab = typeof tabs[number];
const defaultFlags: Record<string, boolean> = {
  multiSite:true, telemetry:true, predictive:true, financial:true, governance:true, securityMonitoring:true, compact:false, contrast:false, collapse:false, dense:false, aiInsights:true, criticalFirst:true,
  email:true, push:true, digest:false, apiAlerts:true, incidentAlerts:true, downtimeAlerts:true, sensorAlerts:true, reportAlerts:true, governanceAlerts:true, importAlerts:true,
  adminMfa:true, managerMfa:true, autoLock:true, rbac:true, roleApproval:true, deleteApproval:true, permissionAudit:true, financeRestricted:true, apiAdmin:true, failedLoginIncident:true, apiIncident:true, criticalEscalation:true, tokenAbuse:true, lockedAccount:true,
  sensorData:true, assetHealth:true, downtimeData:true, financialData:true, governanceData:true, apiData:true, auditData:true, reportData:true, pattern:true, pmAlerts:true, rootCause:true, costForecast:true, anomaly:true, suspiciousApi:true, failedLogin:true, compliance:true, reportInsights:true, autoNotifications:true, autoSecurity:true, autoDowntime:true,
  ipWhitelist:true, tls:true, tokenReminder:true, revokeAbuse:true, apiAudit:true, auditLogins:true, auditRoles:true, auditDeletes:true, auditApprovals:true, auditTokenCreate:true, auditTokenRevoke:true, auditExports:true, auditImports:true, auditGovernance:true,
};
const input = "mt-1.5 h-10 w-full rounded-lg border bg-background px-3 text-xs outline-none focus:ring-2 focus:ring-ring/30";

function Card({ title, hint, children }: { title: string; hint?: string; children: React.ReactNode }) { return <section className="rounded-xl border bg-card shadow-[var(--dv-shadow)]"><header className="border-b px-4 py-3"><h2 className="text-sm font-bold">{title}</h2>{hint && <p className="mt-1 text-[10px] text-muted-foreground">{hint}</p>}</header><div className="space-y-4 p-4">{children}</div></section>; }
function Toggle({ label, checked, onChange, detail }: { label: string; checked: boolean; onChange: () => void; detail?: string }) { return <button type="button" role="switch" aria-checked={checked} onClick={onChange} className="flex w-full items-center justify-between gap-4 rounded-lg border bg-background/50 p-3 text-left"><span><span className="block text-xs font-medium">{label}</span>{detail && <span className="mt-1 block text-[9px] text-muted-foreground">{detail}</span>}</span><span className={`relative h-5 w-9 shrink-0 rounded-full transition-colors ${checked ? "bg-primary" : "bg-muted"}`}><span className={`absolute top-0.5 size-4 rounded-full bg-white shadow transition-transform ${checked ? "translate-x-[18px]" : "translate-x-0.5"}`}/></span></button>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-[10px] font-semibold text-muted-foreground">{label}{children}</label>; }

export function SettingsPage() {
  const [tab,setTab] = useState<Tab>("General"); const [flags,setFlags] = useState(defaultFlags); const [saved,setSaved] = useState(""); const [theme,setTheme] = useState("System"); const [simulator,setSimulator] = useState("Running"); const [agent,setAgent] = useState("Active");
  const toggle = (key:string) => setFlags((state) => ({...state,[key]:!state[key]}));
  function applyTheme(value:string){ setTheme(value); const dark = value === "Dark" || (value === "System" && matchMedia("(prefers-color-scheme: dark)").matches); document.documentElement.classList.toggle("dark",dark); localStorage.setItem("divu-theme", value === "System" ? (dark ? "dark" : "light") : value.toLowerCase()); }
  function reset(){ setFlags(defaultFlags); setTheme("System"); setSimulator("Running"); setAgent("Active"); setSaved("Defaults restored."); applyTheme("System"); }
  const toggleList = (items:[string,string][]) => <div className="grid gap-2 sm:grid-cols-2">{items.map(([key,label]) => <Toggle key={key} label={label} checked={flags[key]} onChange={() => toggle(key)}/>)}</div>;
  return <div className="space-y-5 pb-8"><header className="flex items-start justify-between gap-4"><div className="min-w-0"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-primary">Platform</p><h1 className="mt-1 text-2xl font-bold tracking-tight">Platform Settings</h1><p className="mt-1 max-w-3xl text-sm text-muted-foreground">Manage system preferences, security controls, notification rules, data simulation, and AI agent behavior.</p></div><div className="flex shrink-0 flex-nowrap gap-2"><button type="button" onClick={reset} className="inline-flex h-10 items-center gap-2 whitespace-nowrap rounded-lg border px-3 text-xs font-semibold hover:bg-muted sm:px-4"><RotateCcw className="size-4"/><span className="hidden sm:inline">Reset Defaults</span><span className="sm:hidden">Reset</span></button><button type="button" onClick={() => setSaved("Settings saved successfully.")} className="inline-flex h-10 items-center gap-2 whitespace-nowrap rounded-lg bg-primary px-3 text-xs font-semibold text-primary-foreground sm:px-4"><Save className="size-4"/><span className="hidden sm:inline">Save Changes</span><span className="sm:hidden">Save</span></button></div></header>{saved && <div role="status" className="flex items-center gap-2 rounded-lg border border-emerald-500/30 bg-emerald-500/10 p-3 text-xs text-emerald-700 dark:text-emerald-300"><Check className="size-4"/>{saved}</div>}
  <nav className="overflow-x-auto border-b"><div className="flex min-w-max" role="tablist">{tabs.map((item) => <button type="button" role="tab" aria-selected={tab===item} key={item} onClick={() => setTab(item)} className={`h-12 border-b-2 px-4 text-xs font-medium ${tab===item?"border-primary text-primary":"border-transparent text-muted-foreground"}`}>{item}</button>)}</div></nav>
  <div className="grid gap-4 xl:grid-cols-2">
  {tab === "General" && <><Card title="Organization Profile"><div className="grid gap-3 sm:grid-cols-2">{[["Organization Name","Divu Analytics"],["Platform Name","DIVU Industrial IoT"],["Environment","Development"],["Default Site","Detroit Assembly"],["Time Zone","America/Edmonton"],["Date Format","YYYY-MM-DD"],["Currency","CAD"],["Language","English"]].map(([label,value]) => <Field key={label} label={label}><input defaultValue={value} className={input}/></Field>)}</div></Card><Card title="Operational Scope" hint="These settings control which modules are active across the platform.">{toggleList([["multiSite","Multi-site operations enabled"],["telemetry","Manufacturing telemetry enabled"],["predictive","Predictive maintenance enabled"],["financial","Financial analytics enabled"],["governance","Governance enforcement enabled"],["securityMonitoring","Security monitoring enabled"]])}</Card></>}
  {tab === "Appearance" && <><Card title="Theme Preferences"><Field label="Theme Mode"><select value={theme} onChange={(e)=>applyTheme(e.target.value)} className={input}>{["Light","Dark","System"].map(x=><option key={x}>{x}</option>)}</select></Field>{toggleList([["compact","Compact Mode"],["contrast","High Contrast Mode"],["collapse","Sidebar Collapse"],["dense","Dense Tables"]])}</Card><Card title="Dashboard Preferences"><div className="grid gap-3 sm:grid-cols-2"><Field label="Default Landing Page"><select className={input}>{["Dashboard","Operations","Financial","Security Operations","Reports"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Default Chart Range"><select className={input}>{["7 days","30 days","YTD"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Default Site Filter"><select className={input}>{["All Sites","Detroit","Frankfurt","Osaka","São Paulo","Dubai"].map(x=><option key={x}>{x}</option>)}</select></Field></div>{toggleList([["aiInsights","Show AI Insights"],["criticalFirst","Show Critical Alerts First"]])}</Card></>}
  {tab === "Notifications" && <><Card title="Notification Preferences">{toggleList([["email","Email Notifications"],["push","Alert Push Notifications"],["digest","Weekly Summary Digest"],["apiAlerts","API Activity Alerts"],["incidentAlerts","Security Incident Alerts"],["downtimeAlerts","Downtime Alerts"],["sensorAlerts","Sensor Threshold Alerts"],["reportAlerts","Report Completion Alerts"],["governanceAlerts","Governance Policy Alerts"],["importAlerts","Failed Data Import Alerts"]])}<p className="text-[9px] text-muted-foreground">TODO: persist preferences through the user settings API.</p></Card><Card title="Notification Severity Rules">{["Critical: Email + Push + In-App","High: Push + In-App","Medium: In-App","Low: In-App only"].map(x=><div key={x} className="rounded-lg border p-3 text-xs"><input type="checkbox" defaultChecked className="mr-2 accent-[var(--primary)]"/>{x}</div>)}</Card></>}
  {tab === "Security" && <><Card title="Account Security Defaults">{toggleList([["adminMfa","Require MFA for Administrators"],["managerMfa","Require MFA for Plant Managers"],["autoLock","Auto-lock account after failed attempts"]])}<div className="grid grid-cols-2 gap-3">{[["Failed login threshold","3"],["Session timeout","30 minutes"],["Password rotation","90 days"],["API token warning","30 days before expiry"]].map(([l,v])=><Field key={l} label={l}><input defaultValue={v} className={input}/></Field>)}</div></Card><Card title="Access Control">{toggleList([["rbac","RBAC enabled"],["roleApproval","Approval required for role changes"],["deleteApproval","Approval required for delete actions"],["permissionAudit","Audit all permission changes"],["financeRestricted","Restrict financial dashboard to finance roles"],["apiAdmin","Restrict API token generation to administrators"]])}</Card><Card title="Security Operations Automation">{toggleList([["failedLoginIncident","Auto-create incident for repeated failed logins"],["apiIncident","Auto-create incident for unauthorized API activity"],["criticalEscalation","Auto-escalate critical security events"],["tokenAbuse","Notify Security Team on token abuse"],["lockedAccount","Notify Admin User on locked account"]])}</Card></>}
  {tab === "Data & AI" && <><Card title="Manufacturing Data Simulator" hint="Local realistic industrial data generation"><Field label="Simulator Status"><select value={simulator} onChange={(e)=>setSimulator(e.target.value)} className={input}><option>Running</option><option>Paused</option></select></Field><Field label="Data Refresh Interval"><select className={input}>{["5 seconds","30 seconds","1 minute","5 minutes"].map(x=><option key={x}>{x}</option>)}</select></Field>{toggleList([["sensorData","Generate Sensor Data"],["assetHealth","Generate Asset Health Data"],["downtimeData","Generate Downtime Events"],["financialData","Generate Financial Metrics"],["governanceData","Generate Governance Events"],["apiData","Generate API Security Events"],["auditData","Generate Audit Log Events"],["reportData","Generate Report Data"]])}<Field label="Site simulation coverage"><select multiple defaultValue={["Detroit Assembly","Frankfurt Industrial","Osaka Production"]} className="mt-1.5 min-h-28 w-full rounded-lg border bg-background p-2 text-xs">{["Detroit Assembly","Frankfurt Industrial","Osaka Production","São Paulo","Dubai"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Data source realism"><select className={input}>{["Normal Operating Mode","Maintenance Spike Mode","Downtime Incident Mode","Security Attack Simulation Mode","Financial Loss Simulation Mode"].map(x=><option key={x}>{x}</option>)}</select></Field></Card><Card title="AI Agent Rules"><Field label="Agent Status"><select value={agent} onChange={(e)=>setAgent(e.target.value)} className={input}><option>Active</option><option>Paused</option></select></Field>{toggleList([["pattern","Pattern Detection Enabled"],["pmAlerts","Predictive Maintenance Alerts"],["rootCause","Root Cause Suggestions"],["costForecast","Downtime Cost Forecasting"],["anomaly","Sensor Anomaly Detection"],["suspiciousApi","Suspicious API Detection"],["failedLogin","Failed Login Detection"],["compliance","Governance Compliance Detection"],["reportInsights","Report Insight Generation"],["autoNotifications","Auto-create Notifications"],["autoSecurity","Auto-create Security Incidents"],["autoDowntime","Auto-create Downtime Alerts"]])}<Field label="Agent confidence threshold"><select className={input}>{["60%","70%","80%","90%"].map(x=><option key={x}>{x}</option>)}</select></Field><div className="rounded-lg border bg-muted/30 p-3 text-[10px] leading-5">Security → Security Operations · API → API Security · Downtime → Downtime · Sensor → Sensors · Governance → Data Governance · Reports → Reports · Approvals → Activity</div><p className="text-[10px] leading-5 text-muted-foreground">The simulator generates realistic manufacturing data, while the AI agent monitors patterns and triggers alerts, notifications, and module-specific events.</p></Card></>}
  {tab === "Integrations" && <><Card title="Connected Data Sources">{[["Calgary Plant IoT Sensors","IoT Sensor","Connected","2026-07-13 14:22"],["Toronto PLC Network","PLC","Connected","2026-07-13 14:20"],["SAP ERP","ERP","Warning","2026-07-13 14:00"],["Maintenance Management System","MMS","Failed","2026-07-13 11:45"]].map(([name,type,status,last])=><div key={name} className="rounded-lg border p-3"><div className="flex flex-wrap items-start justify-between gap-2"><div><strong className="text-xs">{name}</strong><p className="mt-1 text-[9px] text-muted-foreground">{type} · Encryption: Enabled · Validation: {status === "Connected" ? "Enabled" : status === "Warning" ? "Pending" : "Failed"} · {last}</p></div><span className="rounded bg-muted px-2 py-1 font-mono text-[8px]">{status}</span></div><div className="mt-3 flex gap-2">{["View","Test Connection","Edit"].map(x=><button type="button" key={x} onClick={()=>setSaved(`${x} completed for ${name}.`)} className="h-7 rounded-md border px-2 text-[9px] hover:bg-muted">{x}</button>)}</div></div>)}</Card><Card title="API Security Defaults">{toggleList([["ipWhitelist","Require IP whitelist"],["tls","Require TLS 1.3"],["tokenReminder","Token rotation reminder"],["revokeAbuse","Revoke token after critical abuse"],["apiAudit","Audit all API client actions"]])}<Field label="Default token expiry"><select className={input}><option>365 days</option></select></Field></Card></>}
  {tab === "Audit & Compliance" && <><Card title="Audit Log Policy">{toggleList([["auditLogins","Audit user logins"],["auditRoles","Audit role changes"],["auditDeletes","Audit delete requests"],["auditApprovals","Audit approvals and declines"],["auditTokenCreate","Audit API token creation"],["auditTokenRevoke","Audit API token revocation"],["auditExports","Audit report exports"],["auditImports","Audit data imports"],["auditGovernance","Audit governance changes"]])}<div className="grid grid-cols-2 gap-3">{[["Audit log retention","5 years"],["Security event retention","7 years"],["Sensor telemetry retention","2 years"],["Financial record retention","7 years"],["Governance policy retention","5 years"]].map(([l,v])=><Field key={l} label={l}><input defaultValue={v} className={input}/></Field>)}</div></Card><Card title="Compliance Controls">{["Tamper-evident audit logs enabled","RBAC policy enforced","MFA policy active","Data classification active","Retention policies active","Export tracking active","Security incident tracking active"].map(x=><div key={x} className="flex items-center gap-2 rounded-lg border p-3 text-xs"><ShieldCheck className="size-4 text-emerald-500"/>{x}</div>)}</Card></>}
  </div></div>;
}
