"use client";

import { useState, type FormEvent, type ReactNode } from "react";
import { Plus, Radio, X } from "lucide-react";

import type { IndustrialAsset } from "@/components/assets/assets-data";
import type { Facility } from "@/components/facilities/facilities-data";

import { sensorPolicies, sensorProtocols, sensorTypes, type IndustrialSensor, type SensorClassification, type SensorType } from "./sensors-data";

const inputClass = "h-10 w-full rounded-lg border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring/30 disabled:cursor-not-allowed disabled:opacity-55";
const labelClass = "space-y-1.5 text-xs font-medium";
function FormSection({ title, children }: { title: string; children: ReactNode }) { return <fieldset className="space-y-3 border-t pt-5 first:border-t-0 first:pt-0"><legend className="mb-3 font-mono text-[10px] font-semibold uppercase tracking-[0.12em] text-primary">{title}</legend>{children}</fieldset>; }

export function RegisterSensorModal({ facilities, assets, nextSensorId, onClose, onSave }: { facilities: Facility[]; assets: IndustrialAsset[]; nextSensorId: string; onClose: () => void; onSave: (sensor: IndustrialSensor) => void }) {
  const [name, setName] = useState(""); const [type, setType] = useState<"" | SensorType>(""); const [unit, setUnit] = useState("");
  const [siteId, setSiteId] = useState(""); const [hallId, setHallId] = useState(""); const [lineId, setLineId] = useState(""); const [stationId, setStationId] = useState(""); const [assetId, setAssetId] = useState("");
  const [protocol, setProtocol] = useState("OPC-UA"); const [samplingFrequency, setSamplingFrequency] = useState("1s"); const [dataSource, setDataSource] = useState("Telemetry Gateway"); const [firmwareVersion, setFirmwareVersion] = useState(""); const [ipAddress, setIpAddress] = useState(""); const [installationDate, setInstallationDate] = useState("");
  const [min, setMin] = useState("0"); const [warnLow, setWarnLow] = useState(""); const [warnHigh, setWarnHigh] = useState(""); const [max, setMax] = useState("");
  const [policy, setPolicy] = useState(sensorPolicies[0]); const [classification, setClassification] = useState<SensorClassification>("Internal"); const [encryptionRequired, setEncryptionRequired] = useState(true);
  const [calibrationInterval, setCalibrationInterval] = useState("6 months"); const [predictiveMonitoring, setPredictiveMonitoring] = useState(true); const [anomalyDetection, setAnomalyDetection] = useState(true);
  const facility = facilities.find((item) => item.id === siteId); const halls = facility?.halls ?? []; const hall = halls.find((item) => item.id === hallId); const lines = hall?.lines ?? []; const line = lines.find((item) => item.id === lineId); const stations = line?.stations ?? []; const station = stations.find((item) => item.id === stationId); const availableAssets = assets.filter((asset) => asset.location.stationId === stationId); const asset = assets.find((item) => item.assetId === assetId);

  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!facility || !hall || !line || !station || !asset || !type) return;
    const threshold = { min: Number(min), warnLow: Number(warnLow), warnHigh: Number(warnHigh), max: Number(max) };
    onSave({ id: nextSensorId.toLowerCase(), sensorId: nextSensorId, name: name.trim(), type, unit: unit.trim(), location: { siteId: facility.id, siteName: facility.name, hallId: hall.id, hallName: hall.name, lineId: line.id, lineName: line.name, stationId: station.id, stationName: station.name, assetId: asset.assetId, assetName: asset.name }, status: "Active", reading: threshold.min, health: 100, battery: 100, lastUpdated: "Just now", thresholds: threshold, history: Array(12).fill(threshold.min), network: { protocol, samplingFrequency, dataSource, firmwareVersion: firmwareVersion.trim(), ipAddress: ipAddress.trim(), installationDate }, governance: { policy, classification, encryptionRequired }, calibration: { interval: calibrationInterval, lastCalibration: installationDate, nextCalibration: "", status: calibrationInterval === "Not Required" ? "Not Required" : "Current" }, monitoring: { predictiveMonitoring, anomalyDetection, anomalyDetected: false, failureRisk: "Low" } });
  }

  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/65 p-0 backdrop-blur-sm sm:items-center sm:p-5" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section role="dialog" aria-modal="true" aria-labelledby="register-sensor-title" className="flex max-h-[95vh] w-full flex-col overflow-hidden rounded-t-2xl border bg-background shadow-2xl sm:max-w-3xl sm:rounded-2xl"><header className="flex shrink-0 items-start gap-3 border-b p-5"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><Radio className="size-5" /></div><div className="min-w-0 flex-1"><h2 id="register-sensor-title" className="text-lg font-bold">Register New Sensor</h2><p className="mt-0.5 font-mono text-[10px] text-muted-foreground">Sensor ID auto-generated: <span className="text-primary">{nextSensorId}</span></p></div><button type="button" onClick={onClose} aria-label="Close Register New Sensor modal" className="grid size-9 place-items-center rounded-lg border text-muted-foreground hover:bg-muted hover:text-foreground"><X className="size-4" /></button></header><form id="register-sensor-form" onSubmit={submit} className="min-h-0 flex-1 space-y-5 overflow-y-auto p-5">
    <FormSection title="General Information"><div className="grid gap-3 sm:grid-cols-2"><label className={`${labelClass} sm:col-span-2`}>Sensor Name<input required value={name} onChange={(event) => setName(event.target.value)} className={inputClass} placeholder="Spindle Temp A1" /></label><label className={labelClass}>Sensor Type<select required value={type} onChange={(event) => setType(event.target.value as SensorType)} className={inputClass}><option value="">Select sensor type</option>{sensorTypes.map((item) => <option key={item}>{item}</option>)}</select></label><label className={labelClass}>Unit<input required value={unit} onChange={(event) => setUnit(event.target.value)} className={inputClass} placeholder="°F, PSI, mm/s, A, %RH, RPM, kWh" /></label></div></FormSection>
    <FormSection title="Operational Location"><div className="grid gap-3 sm:grid-cols-2"><label className={labelClass}>Site<select required value={siteId} onChange={(event) => { setSiteId(event.target.value); setHallId(""); setLineId(""); setStationId(""); setAssetId(""); }} className={inputClass}><option value="">Select site</option>{facilities.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className={labelClass}>Hall<select required disabled={!siteId} value={hallId} onChange={(event) => { setHallId(event.target.value); setLineId(""); setStationId(""); setAssetId(""); }} className={inputClass}><option value="">Select hall</option>{halls.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className={labelClass}>Production Line<select required disabled={!hallId} value={lineId} onChange={(event) => { setLineId(event.target.value); setStationId(""); setAssetId(""); }} className={inputClass}><option value="">Select line</option>{lines.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className={labelClass}>Station<select required disabled={!lineId} value={stationId} onChange={(event) => { setStationId(event.target.value); setAssetId(""); }} className={inputClass}><option value="">Select station</option>{stations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className={`${labelClass} sm:col-span-2`}>Linked Asset<select required disabled={!stationId} value={assetId} onChange={(event) => setAssetId(event.target.value)} className={inputClass}><option value="">{stationId && !availableAssets.length ? "No registered assets at this station" : "Select asset"}</option>{availableAssets.map((item) => <option key={item.assetId} value={item.assetId}>{item.assetId} — {item.name}</option>)}</select></label></div></FormSection>
    <FormSection title="Network & Connectivity"><div className="grid gap-3 sm:grid-cols-2"><label className={labelClass}>Communication Protocol<select value={protocol} onChange={(event) => setProtocol(event.target.value)} className={inputClass}>{sensorProtocols.map((item) => <option key={item}>{item}</option>)}</select></label><label className={labelClass}>Sampling Frequency<select value={samplingFrequency} onChange={(event) => setSamplingFrequency(event.target.value)} className={inputClass}>{["100ms", "500ms", "1s", "5s", "30s", "1m"].map((item) => <option key={item}>{item}</option>)}</select></label><label className={labelClass}>Data Source<select value={dataSource} onChange={(event) => setDataSource(event.target.value)} className={inputClass}>{["Telemetry Gateway", "PLC", "SCADA", "Edge Gateway", "API", "Manual"].map((item) => <option key={item}>{item}</option>)}</select></label><label className={labelClass}>Firmware Version<input required value={firmwareVersion} onChange={(event) => setFirmwareVersion(event.target.value)} className={inputClass} placeholder="4.1.2" /></label><label className={labelClass}>IP Address<input required value={ipAddress} onChange={(event) => setIpAddress(event.target.value)} className={inputClass} placeholder="192.168.x.x" /></label><label className={labelClass}>Installation Date<input required type="date" value={installationDate} onChange={(event) => setInstallationDate(event.target.value)} className={inputClass} /></label></div></FormSection>
    <FormSection title="Thresholds"><div className="grid grid-cols-2 gap-3"><label className={labelClass}>Min<input required type="number" step="any" value={min} onChange={(event) => setMin(event.target.value)} className={inputClass} /></label><label className={labelClass}>Warn Low<input required type="number" step="any" value={warnLow} onChange={(event) => setWarnLow(event.target.value)} className={inputClass} /></label><label className={labelClass}>Warn High<input required type="number" step="any" value={warnHigh} onChange={(event) => setWarnHigh(event.target.value)} className={inputClass} /></label><label className={labelClass}>Max<input required type="number" step="any" value={max} onChange={(event) => setMax(event.target.value)} className={inputClass} /></label></div></FormSection>
    <FormSection title="Governance"><div className="grid gap-3 sm:grid-cols-2"><label className={labelClass}>Governance Policy<select value={policy} onChange={(event) => setPolicy(event.target.value)} className={inputClass}>{sensorPolicies.map((item) => <option key={item}>{item}</option>)}</select></label><label className={labelClass}>Classification<select value={classification} onChange={(event) => setClassification(event.target.value as SensorClassification)} className={inputClass}>{["Public", "Internal", "Confidential", "Restricted"].map((item) => <option key={item}>{item}</option>)}</select></label><label className="flex items-center gap-2 text-xs font-medium sm:col-span-2"><input type="checkbox" checked={encryptionRequired} onChange={(event) => setEncryptionRequired(event.target.checked)} className="size-4 accent-[var(--primary)]" />Encryption Required</label></div></FormSection>
    <FormSection title="Calibration"><label className={`${labelClass} block`}>Calibration Interval<select value={calibrationInterval} onChange={(event) => setCalibrationInterval(event.target.value)} className={inputClass}>{["Monthly", "3 months", "6 months", "Annual", "2 years", "Not Required"].map((item) => <option key={item}>{item}</option>)}</select></label></FormSection>
    <FormSection title="AI & Monitoring"><div className="grid gap-3 sm:grid-cols-2"><label className="flex items-center gap-2 rounded-lg border p-3 text-xs font-medium"><input type="checkbox" checked={predictiveMonitoring} onChange={(event) => setPredictiveMonitoring(event.target.checked)} className="size-4 accent-[var(--primary)]" />Enable Predictive Monitoring</label><label className="flex items-center gap-2 rounded-lg border p-3 text-xs font-medium"><input type="checkbox" checked={anomalyDetection} onChange={(event) => setAnomalyDetection(event.target.checked)} className="size-4 accent-[var(--primary)]" />Enable Anomaly Detection</label></div></FormSection>
  </form><footer className="flex shrink-0 flex-col-reverse gap-2 border-t p-4 sm:flex-row sm:justify-end"><button type="button" onClick={onClose} className="h-10 rounded-lg border px-4 text-sm font-semibold hover:bg-muted">Cancel</button><button type="submit" form="register-sensor-form" className="inline-flex h-10 items-center justify-center gap-2 rounded-lg bg-primary px-5 text-sm font-semibold text-primary-foreground hover:bg-primary/90"><Plus className="size-4" />Register Sensor</button></footer></section></div>;
}
