"use client";

import { LayoutGrid, List, Search } from "lucide-react";

import type { SensorStatus } from "./sensors-data";

export type SensorViewMode = "grid" | "list";
const selectClass = "h-10 min-w-32 rounded-lg border bg-card px-3 text-xs outline-none focus:ring-2 focus:ring-ring/30";

export function SensorFilters({ query, onQueryChange, site, onSiteChange, sites, line, onLineChange, lines, status, onStatusChange, viewMode, onViewModeChange }: { query: string; onQueryChange: (value: string) => void; site: string; onSiteChange: (value: string) => void; sites: string[]; line: string; onLineChange: (value: string) => void; lines: string[]; status: "All" | SensorStatus; onStatusChange: (value: "All" | SensorStatus) => void; viewMode: SensorViewMode; onViewModeChange: (value: SensorViewMode) => void }) {
  return <div className="flex flex-col gap-3 rounded-xl border bg-card p-3 shadow-[var(--dv-shadow)] lg:flex-row lg:items-center"><label className="relative min-w-0 flex-1"><span className="sr-only">Search sensors</span><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(event) => onQueryChange(event.target.value)} placeholder="Search sensors, assets, stations..." className="h-10 w-full rounded-lg border bg-background pl-9 pr-3 text-xs outline-none focus:ring-2 focus:ring-ring/30" /></label><div className="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:flex"><select value={site} onChange={(event) => onSiteChange(event.target.value)} aria-label="Filter sensors by site" className={selectClass}><option>All Sites</option>{sites.map((item) => <option key={item}>{item}</option>)}</select><select value={line} onChange={(event) => onLineChange(event.target.value)} aria-label="Filter sensors by line" className={selectClass}><option>All Lines</option>{lines.map((item) => <option key={item}>{item}</option>)}</select><select value={status} onChange={(event) => onStatusChange(event.target.value as "All" | SensorStatus)} aria-label="Filter sensors by status" className={selectClass}><option>All</option>{["Active", "Warning", "Critical", "Offline", "Maintenance"].map((item) => <option key={item}>{item}</option>)}</select></div><div className="flex w-fit overflow-hidden rounded-lg border">{(["grid", "list"] as const).map((mode) => { const Icon = mode === "grid" ? LayoutGrid : List; return <button key={mode} type="button" aria-label={`${mode} view`} aria-pressed={viewMode === mode} onClick={() => onViewModeChange(mode)} className={`grid size-10 place-items-center ${viewMode === mode ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-muted"}`}><Icon className="size-4" /></button>; })}</div></div>;
}
