"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, Radio, RefreshCw, Search } from "lucide-react";
import { apiRequest } from "@/lib/api-client";
import type { GatewaySensorDto, SensorStreamDto } from "@/lib/backend-dtos";

type StreamDetail=SensorStreamDto&{sensors:GatewaySensorDto[]};
export function SensorsPage(){
  const[streams,setStreams]=useState<StreamDetail[]>([]);const[query,setQuery]=useState("");const[loading,setLoading]=useState(true);const[error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);try{const list=await apiRequest<SensorStreamDto[]>("/api/backend/sensors/streams");const details=await Promise.all(list.map(item=>apiRequest<StreamDetail>(`/api/backend/sensors/streams/${item.strid}`)));setStreams(details);setError("")}catch(cause){setError(cause instanceof Error?cause.message:"Sensors could not be loaded.")}finally{setLoading(false)}},[]);
  useEffect(()=>{// eslint-disable-next-line react-hooks/set-state-in-effect
    void load()
  },[load]);
  const sensors=useMemo(()=>streams.flatMap(stream=>stream.sensors.map(sensor=>({...sensor,streamId:stream.strid,streamName:stream.name,protocol:stream.protocol,station:stream.station}))),[streams]);const filtered=sensors.filter(item=>`${item.name} ${item.sensorType} ${item.status} ${item.streamName} ${item.station??""}`.toLowerCase().includes(query.toLowerCase()));const active=sensors.filter(item=>item.status.toLowerCase()==="active").length;
  return <div className="space-y-5 pb-5"><header className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-mono text-[10px] font-semibold uppercase tracking-[0.14em] text-primary">Sensors</p><h1 className="mt-1.5 text-2xl font-bold tracking-tight">Sensor Intelligence Center</h1><p className="mt-1 text-sm text-muted-foreground">Backend sensor inventory, protocol, stream and latest status</p></div><div className="flex gap-2"><Link href="/local-ai" className="inline-flex h-10 items-center rounded-lg border px-4 text-xs font-semibold">Open Olive Live Data</Link><button onClick={()=>void load()} className="inline-flex h-10 items-center gap-2 rounded-lg border px-4 text-xs"><RefreshCw className="size-4"/>Refresh</button></div></header>{error&&<p role="alert" className="flex items-center gap-2 rounded-lg border border-destructive/30 bg-destructive/10 p-3 text-xs text-destructive"><AlertTriangle className="size-4"/>{error}</p>}<div className="grid gap-3 sm:grid-cols-3">{[{label:"Sensor Streams",value:streams.length},{label:"Sensors",value:sensors.length},{label:"Active Sensors",value:active}].map(item=><article key={item.label} className="rounded-xl border bg-card p-4"><Radio className="size-4 text-primary"/><p className="mt-3 text-xl font-bold">{item.value}</p><p className="text-[10px] text-muted-foreground">{item.label}</p></article>)}</div><label className="relative block"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search sensors, types, streams or stations…" className="h-10 w-full rounded-lg border bg-background pl-9 pr-3 text-xs"/></label>{loading?<div className="h-64 animate-pulse rounded-xl bg-muted"/>:<div className="grid gap-3 lg:grid-cols-2 xl:grid-cols-3">{filtered.map(item=><article key={item.sid} className="rounded-xl border bg-card p-4 shadow-[var(--dv-shadow)]"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{item.name}</h2><p className="mt-1 font-mono text-[9px] text-muted-foreground">Sensor #{item.sid} · {item.sensorType}</p></div><span className="rounded-full bg-muted px-2 py-1 text-[9px] uppercase">{item.status}</span></div><dl className="mt-4 space-y-2 text-xs"><div className="flex justify-between gap-3"><dt className="text-muted-foreground">Stream</dt><dd>{item.streamName}</dd></div><div className="flex justify-between gap-3"><dt className="text-muted-foreground">Protocol</dt><dd>{item.protocol}</dd></div><div className="flex justify-between gap-3"><dt className="text-muted-foreground">Station</dt><dd className="text-right">{item.station??"Unavailable"}</dd></div></dl></article>)}{!filtered.length&&<p className="col-span-full rounded-xl border p-12 text-center text-sm text-muted-foreground">No sensors match the current search.</p>}</div>}</div>
}
