import { Radio } from "lucide-react";

import { SensorHealthIndicator } from "./sensor-health-indicator";
import { SensorStatusBadge } from "./sensor-status-badge";
import { SensorThresholdBar } from "./sensor-threshold-bar";
import type { IndustrialSensor } from "./sensors-data";

export function SensorListView({ sensors }: { sensors: IndustrialSensor[] }) {
  return <div className="overflow-hidden rounded-xl border bg-card shadow-[var(--dv-shadow)]"><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left"><thead className="border-b bg-muted/35 font-mono text-[9px] uppercase tracking-[0.1em] text-muted-foreground"><tr><th className="px-4 py-3">Sensor</th><th className="px-4 py-3">Reading</th><th className="px-4 py-3">Location / Asset</th><th className="px-4 py-3">Status</th><th className="w-48 px-4 py-3">Threshold</th><th className="w-28 px-4 py-3">Health</th><th className="px-4 py-3">Network</th><th className="px-4 py-3">Updated</th></tr></thead><tbody className="divide-y">{sensors.map((sensor) => <tr key={sensor.id} className="text-xs hover:bg-muted/25"><td className="px-4 py-3"><p className="font-semibold">{sensor.name}</p><p className="mt-1 font-mono text-[9px] text-muted-foreground">{sensor.sensorId} · {sensor.type}</p></td><td className="px-4 py-3"><p className="text-base font-bold">{sensor.status === "Offline" ? "—" : sensor.reading}</p><p className="text-[10px] text-muted-foreground">{sensor.unit}</p></td><td className="max-w-64 px-4 py-3"><p className="truncate font-medium">{sensor.location.assetName}</p><p className="mt-1 truncate text-[9px] text-muted-foreground">{sensor.location.siteName} · {sensor.location.lineName} · {sensor.location.stationName}</p></td><td className="px-4 py-3"><SensorStatusBadge status={sensor.status} /></td><td className="px-4 py-3"><SensorThresholdBar sensor={sensor} /></td><td className="px-4 py-3"><SensorHealthIndicator label="Health" value={sensor.health} /></td><td className="px-4 py-3"><p className="font-mono text-[10px]">{sensor.network.protocol}</p><p className="mt-1 text-[9px] text-muted-foreground">{sensor.governance.encryptionRequired ? "Encrypted" : "Unencrypted"}</p></td><td className="px-4 py-3 text-[10px] text-muted-foreground">{sensor.lastUpdated}</td></tr>)}</tbody></table></div>{!sensors.length && <div className="p-12 text-center text-sm text-muted-foreground"><Radio className="mx-auto mb-3 size-9 opacity-40" />No sensors match the selected filters.</div>}</div>;
}
