import { Activity, Battery, Clock3, Droplets, Flame, Gauge, LockKeyhole, MapPin, Radio, RotateCcw, ShieldCheck, Thermometer, Zap } from "lucide-react";

import { SensorHealthIndicator } from "./sensor-health-indicator";
import { SensorStatusBadge, sensorStatusBorders } from "./sensor-status-badge";
import { SensorThresholdBar } from "./sensor-threshold-bar";
import type { IndustrialSensor, SensorType } from "./sensors-data";

const icons: Record<SensorType, React.ElementType> = { Temperature: Thermometer, Pressure: Gauge, Vibration: Activity, Current: Zap, Humidity: Droplets, RPM: RotateCcw, Energy: Flame };

export function SensorCard({ sensor }: { sensor: IndustrialSensor }) {
  const Icon = icons[sensor.type];
  return <article className={`relative overflow-hidden rounded-xl border bg-card p-4 shadow-[var(--dv-shadow)] transition-all hover:-translate-y-0.5 hover:shadow-[var(--dv-shadow-m)] ${sensorStatusBorders[sensor.status]}`}>{(sensor.status === "Critical" || sensor.status === "Warning") && <span className={`absolute inset-x-0 top-0 h-0.5 ${sensor.status === "Critical" ? "bg-[var(--dv-badge-cr-text)]" : "bg-[var(--dv-badge-wa-text)]"}`} />}<div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-start gap-2.5"><div className="grid size-9 shrink-0 place-items-center rounded-lg bg-primary/10 text-primary"><Icon className="size-4" /></div><div className="min-w-0"><p className="text-[9px] text-muted-foreground">{sensor.type} · <span className="font-mono">{sensor.sensorId}</span></p><h2 className="truncate text-sm font-bold">{sensor.name}</h2></div></div><SensorStatusBadge status={sensor.status} /></div><div className="mt-4"><p className="text-3xl font-bold leading-none tabular-nums">{sensor.status === "Offline" ? "—" : sensor.reading}</p><p className="mt-1 text-xs text-muted-foreground">{sensor.unit}</p></div><div className="mt-3"><SensorThresholdBar sensor={sensor} /></div><div className="mt-3 flex min-w-0 items-center gap-2 rounded-lg bg-muted/45 px-2.5 py-2 font-mono text-[8px] text-muted-foreground"><ShieldCheck className="size-3 shrink-0 text-primary" /><span className="truncate">{sensor.governance.policy}</span><span className="ml-auto shrink-0 rounded bg-background px-1.5 py-0.5 uppercase">{sensor.governance.classification}</span>{sensor.governance.encryptionRequired && <LockKeyhole className="size-3 shrink-0 text-primary" aria-label="Encrypted telemetry" />}</div><div className="mt-3 grid grid-cols-3 gap-3 border-t pt-3"><SensorHealthIndicator label="Health" value={sensor.health} /><SensorHealthIndicator label="Battery" value={sensor.battery} kind="battery" /><div><p className="text-[9px] text-muted-foreground">Updated</p><p className="mt-1 flex items-center gap-1 text-[10px]"><Clock3 className="size-3" />{sensor.lastUpdated}</p><p className="mt-1 truncate text-[9px] text-muted-foreground"><MapPin className="mr-1 inline size-3" />{sensor.location.stationName}</p></div></div><div className="mt-3 flex flex-wrap items-center gap-2 border-t pt-3 font-mono text-[8px] text-muted-foreground"><span className="flex min-w-0 items-center gap-1"><Radio className="size-3 text-primary" /><span className="truncate">{sensor.location.assetName}</span></span><span className="ml-auto flex items-center gap-1"><Battery className="size-3" />{sensor.network.protocol}</span></div></article>;
}
