"use client";
/* eslint-disable react-hooks/set-state-in-effect */

import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, Bell, CheckCircle2, X } from "lucide-react";

import { apiRequest } from "@/lib/api-client";
import type { CanonicalNotificationDto } from "@/lib/backend-dtos";
import { normalizeNotifications } from "@/lib/normalize-notifications";

export function NotificationDrawer({open,onClose}:{open:boolean;onClose:()=>void}) {
  const[data,setData]=useState<CanonicalNotificationDto[]>([]);const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[unreadOnly,setUnreadOnly]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setError("");try{setData(normalizeNotifications(await apiRequest<unknown>("/api/backend/notifications")))}catch(cause){setData([]);setError(cause instanceof Error?cause.message:"Notifications are unavailable.")}finally{setLoading(false)}},[]);
  useEffect(()=>{if(!open)return;const escape=(event:KeyboardEvent)=>event.key==="Escape"&&onClose();window.addEventListener("keydown",escape);void load();return()=>window.removeEventListener("keydown",escape)},[load,onClose,open]);
  const visible=useMemo(()=>unreadOnly?data.filter(item=>!item.read_at_utc):data,[data,unreadOnly]);
  async function markRead(id:number){try{await apiRequest(`/api/backend/notifications/${id}/read`,{method:"PATCH",body:"{}"});await load()}catch(cause){setError(cause instanceof Error?cause.message:"The notification could not be updated.")}}
  async function markAll(){try{await apiRequest("/api/backend/notifications/read-all",{method:"POST",body:"{}"});await load()}catch(cause){setError(cause instanceof Error?cause.message:"Notifications could not be updated.")}}
  if(!open)return null;
  return <div className="fixed inset-0 z-[70] bg-black/45" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><aside role="dialog" aria-modal="true" aria-labelledby="notifications-title" className="ml-auto flex h-full w-[min(32rem,96vw)] flex-col border-l bg-background shadow-2xl"><header className="flex items-start gap-3 border-b p-5"><span className="grid size-10 place-items-center rounded-xl bg-primary/10 text-primary"><Bell className="size-5"/></span><div className="flex-1"><h2 id="notifications-title" className="font-bold">Notifications</h2><p className="mt-1 text-xs text-muted-foreground">Canonical account and operations notifications</p></div><button onClick={onClose} aria-label="Close notifications" className="grid size-9 place-items-center rounded-lg border"><X className="size-4"/></button></header><div className="flex gap-2 border-b p-3"><button onClick={()=>void markAll()} disabled={loading||!data.some(item=>!item.read_at_utc)} className="h-8 rounded-lg border px-3 text-xs disabled:opacity-40">Mark all read</button><button onClick={()=>setUnreadOnly(value=>!value)} className={`h-8 rounded-lg border px-3 text-xs ${unreadOnly?"bg-primary text-primary-foreground":""}`}>Unread only</button></div>{error&&<p role="alert" className="m-3 flex items-center gap-2 rounded-lg bg-destructive/10 p-3 text-xs text-destructive"><AlertTriangle className="size-4"/>{error}</p>}<div className="min-h-0 flex-1 space-y-3 overflow-y-auto p-4">{loading?<div role="status" className="h-40 animate-pulse rounded-xl bg-muted"/>:visible.map(item=>{const read=Boolean(item.read_at_utc);return <article key={item.notification_id} className={`rounded-xl border p-4 ${read?"bg-card":"border-primary/30 bg-primary/5"}`}><div className="flex gap-3"><CheckCircle2 className={`size-4 ${read?"text-muted-foreground":"text-primary"}`}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="text-xs font-bold">{item.title}</h3><span className="rounded bg-muted px-2 py-0.5 font-mono text-[8px] uppercase">{item.notification_type}</span></div><p className="mt-2 text-[11px] leading-5">{item.message}</p><p className="mt-2 text-[9px] text-muted-foreground">{new Date(item.created_at_utc).toLocaleString()}</p>{!read&&<button onClick={()=>void markRead(item.notification_id)} className="mt-3 h-7 rounded-md border px-2 text-[9px]">Mark read</button>}</div></div></article>})}{!loading&&!visible.length&&!error&&<p className="py-16 text-center text-xs text-muted-foreground">{data.length?"No unread notifications.":"No notifications exist for your account."}</p>}</div></aside></div>
}
