import type { DivuNotification } from "./notification-types";

export const initialNotifications: DivuNotification[] = [
  { id: "n1", title: "Critical API Abuse", type: "Security", severity: "Critical", read: false, message: "Security Scan Bot generated 1,840 unauthorized API requests. Token revoked and investigation escalated.", time: "5 min ago", source: "API Security", route: "/api-security", actions: ["View API Client", "Open Investigation", "Mark Read"] },
  { id: "n2", title: "Multiple Failed Logins", type: "Security", severity: "High", read: false, message: "Sarah Johnson account was locked after 3 failed login attempts from Osaka.", time: "12 min ago", source: "Security Operations", route: "/security-ops", actions: ["View Incident", "Acknowledge", "Mark Read"] },
  { id: "n3", title: "Sensor Threshold Warning", type: "Operations", severity: "High", read: false, message: "Hydraulic Pressure P1 exceeded max threshold at Detroit Assembly Line C.", time: "18 min ago", source: "Sensors", route: "/sensors", actions: ["View Sensor", "Create Downtime Event", "Mark Read"] },
  { id: "n4", title: "Downtime Factor Approved", type: "Approval", severity: "Medium", read: true, message: "Mechanical Failure downtime factor was approved by Admin User.", time: "1 hour ago", source: "Activity", route: "/activity", actions: ["View Request", "Restore Action"] },
  { id: "n5", title: "Report Generated", type: "Report", severity: "Low", read: true, message: "Scrap Analysis report completed successfully with 578 records.", time: "2 hours ago", source: "Reports", route: "/reports", actions: ["View Report", "Download"] },
  { id: "n6", title: "Data Import Failed", type: "Operations", severity: "High", read: false, message: "Maintenance Management System import failed. Connection timeout from MMS host.", time: "3 hours ago", source: "Data Input", route: "/data-input", actions: ["View Import", "Retry", "Mark Read"] },
  { id: "n7", title: "Governance Policy Updated", type: "Governance", severity: "Medium", read: true, message: "Sensor Telemetry Retention policy was updated and assigned to 16 sensors.", time: "4 hours ago", source: "Data Governance", route: "/governance", actions: ["View Policy"] },
  { id: "n8", title: "Olive Predictive Alert", type: "Operations", severity: "High", read: false, message: "Olive detected an early failure pattern on CNC Lathe #4. Maintenance recommended within 14 days.", time: "5 hours ago", source: "Assets", route: "/assets", actions: ["View Asset", "Create Maintenance Task", "Mark Read"] },
  { id: "n9", title: "Role Change Request", type: "Approval", severity: "Medium", read: false, message: "Marcus Lee requested permission update for Viewer Role Permissions.", time: "Yesterday", source: "Activity", route: "/activity", actions: ["Review Request", "Assign Manager"] },
  { id: "n10", title: "API Token Expiring", type: "Security", severity: "Medium", read: true, message: "ERP Connector API token expires today. Rotate secret to prevent service interruption.", time: "Yesterday", source: "API Security", route: "/api-security", actions: ["Rotate Token", "View Client"] },
];
